// Code generated by main. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/replicatedhq/ship-operator/pkg/client/shipwatchclientset/typed/ship/v1beta1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeShipV1beta1 struct {
	*testing.Fake
}

func (c *FakeShipV1beta1) ShipWatches(namespace string) v1beta1.ShipWatchInterface {
	return &FakeShipWatches{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeShipV1beta1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
