apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: app-downstream-version
spec:
  database: kotsadm-postgres
  name: app_downstream_version
  requires: []
  schema:
    postgres:
      primaryKey:
        - app_id
        - cluster_id
        - sequence
      columns:
      - name: app_id
        type: text
      - name: cluster_id
        type: text
      - name: sequence
        type: integer
      - name: parent_sequence
        type: integer
      - name: created_at
        type: timestamp without time zone
      - name: applied_at
        type: timestamp without time zone
      - name: version_label
        type: text
        constraints:
          notNull: true
      - name: status
        type: text
      - name: status_info
        type: text
      - name: source
        type: text
      - name: diff_summary
        type: text
      - name: diff_summary_error
        type: text
      - name: preflight_result
        type: text
      - name: preflight_result_created_at
        type: timestamp without time zone
      - name: preflight_ignore_permissions
        type: boolean
        default: "false"
      - name: git_commit_url
        type: text
      - name: git_deployable
        type: boolean
        default: "true"
