apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: ship-user-local
spec:
  database: kotsadm-postgres
  name: ship_user_local
  requires: []
  schema:
    postgres:
      indexes:
        - columns: [email]
          isUnique: true
      primaryKey:
      - user_id
      columns:
      - name: user_id
        type: text
        constraints:
          notNull: true
      - name: password_bcrypt
        type: text
        constraints:
          notNull: true
      - name: first_name
        type: text
      - name: last_name
        type: text
      - name: email
        type: text
        constraints:
          notNull: true