 
apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: user-app
spec:
  database: kotsadm-postgres
  name: user_app
  requires: []
  schema:
    postgres:
      primaryKey:
      - user_id
      - app_id
      columns:
      - name: user_id
        type: text
      - name: app_id
        type: text