---
apiVersion: v1
kind: Service
metadata:
  name: kotsadm-postgres
  labels:
    app: kotsadm-postgres
spec:
  type: NodePort
  ports:
  - name: postgres
    port: 5432
    targetPort: postgres
    nodePort: 30432
  selector:
    app: kotsadm-postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: kotsadm-postgres
  labels:
    app: kotsadm-postgres
type: Opaque
data:
  password: "cGFzc3dvcmQ="
  uri: "cG9zdGdyZXNxbDovL2tvdHNhZG06cGFzc3dvcmRAa290c2FkbS1wb3N0Z3Jlcy9rb3RzYWRtP2Nvbm5lY3RfdGltZW91dD0xMCZhcHBsaWNhdGlvbl9uYW1lPXNoaXAmc3NsbW9kZT1kaXNhYmxl"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kotsadm-postgres
spec:
  selector:
    matchLabels:
      app: kotsadm-postgres
  serviceName: kotsadm-postgres
  template:
    metadata:
      labels:
        app: kotsadm-postgres
    spec:
      securityContext:
        runAsUser: 70 # the default 'postgres' user
        fsGroup: 70
      containers:
      - name: postgres
        image: postgres:10.18-alpine
        imagePullPolicy: IfNotPresent
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/devpgdata
        - name: POSTGRES_USER
          value: kotsadm
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB
          value: kotsadm
        ports:
        - name: postgres
          containerPort: 5432
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - pg_isready -U kotsadm -h 127.0.0.1 -p 5432
          initialDelaySeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - pg_isready -U kotsadm -h 127.0.0.1 -p 5432
          initialDelaySeconds: 1
          timeoutSeconds: 1
          periodSeconds: 1
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/postgresql/data

      volumes:
      - name: datadir
        persistentVolumeClaim:
          claimName: datadir

  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: 1Gi
