FROM golang:1.16 as deps

RUN go get github.com/go-delve/delve/cmd/dlv@v1.7.2

ENV PROJECTPATH=/go/src/github.com/replicatedhq/kots
WORKDIR $PROJECTPATH
COPY Makefile ./
COPY Makefile.build ./
COPY go.mod ./
COPY go.sum ./
COPY cmd ./cmd
COPY pkg ./pkg
COPY web/webcontent.go ./web/webcontent.go
COPY web/dist ./web/dist
COPY kotskinds ./kotskinds

RUN make kotsadm
