apiVersion: skaffold/v2beta2
kind: Config

profiles:
  - name: kotsstore
    activation: 
      - env: KOTSSTORE=
    deploy:
      kustomize:
        paths: 
          - "./kustomize/overlays/kotsstore"
  - name: debug
    activation:
      - env: DEBUG_KOTSADM=1
    patches:
      - op: add
        path: /build/artifacts/1/docker/buildArgs
        value:
          DEBUG_KOTSADM: 1

build:
  local:
    concurrency: 0
    useBuildkit: true

  artifacts:
    - image: kotsadm-web
      context: "./web"
      sync:
        manual:
          - src: "src/**/*.jsx"
            dest: "./"
          - src: "src/**/*.js"
            dest: "./"
          - src: "src/**/*.png"
            dest: "./"
          - src: "src/**/*.scss"
            dest: "./"
          - src: "src/**/*.css"
            dest: "./"
      docker:
        dockerfile: ./skaffold.Dockerfile

    - image: kotsadm
      context: "./"
      docker:
        dockerfile: ./hack/dev/skaffold.Dockerfile

    - image: kotsadm-migrations
      context: "./migrations"
      docker:
        dockerfile: ./skaffold.Dockerfile

    - image: kurl-proxy
      context: "./kurl_proxy"
      docker:
        dockerfile: ./skaffold.Dockerfile

deploy:
  statusCheckDeadlineSeconds: 240
  kustomize:
    paths:
      - "./kustomize/overlays/dev"

portForward:
  - resourceType: service
    resourceName: kotsadm
    port: 3000
    localPort: 30000
  - resourceType: service
    resourceName: kurl-proxy
    port: 8800
    localPort: 30880
