apiVersion: skaffold/v2beta2
kind: Config

profiles:
  - name: kotsstore
    activation: 
      - env: KOTSSTORE=
    deploy:
      kustomize:
        paths: 
          - "./kustomize/overlays/kotsstore"

build:
  insecureRegistries:
  - localhost:5000
  - k3d-replicated-registry.localhost:5000

  local:
    concurrency: 0
    useBuildkit: true

  artifacts:
    - image: kotsadm-web
      context: "./web"
      sync:
        manual:
          - src: "src/**/*.jsx"
            dest: "./"
          - src: "src/**/*.js"
            dest: "./"
          - src: "src/**/*.png"
            dest: "./"
          - src: "src/**/*.scss"
            dest: "./"
          - src: "src/**/*.css"
            dest: "./"
      docker:
        dockerfile: ./Dockerfile.skaffold

    - image: kotsadm
      context: "./"
      docker:
        dockerfile: ./hack/dev/Dockerfile.skaffold

    - image: kotsadm-migrations
      context: "./migrations"
      docker:
        dockerfile: ./Dockerfile.skaffold

    - image: kurl-proxy
      context: "./kurl_proxy"
      docker:
        dockerfile: ./Dockerfile.skaffold

deploy:
  statusCheckDeadlineSeconds: 240
  kustomize:
    paths:
      - "./kustomize/overlays/dev"

portForward:
  - resourceType: service
    resourceName: kotsadm
    port: 3000
    localPort: 30000
  - resourceType: statefulset
    resourceName: kotsadm-postgres
    port: 5432
    localPort: 30432
  - resourceType: deployment
    resourceName: kurl-proxy-kotsadm
    port: 8080
    localPort: 30880
