apiVersion: v1
kind: Service
metadata:
  name: kotsadm
  labels:
    kots.io/kotsadm: "true"
    kots.io/backup: velero
    app: kotsadm
spec:
  type: NodePort
  ports:
    - name: http
      port: 3000
      targetPort: http
      nodePort: 30808
    - name: dlv
      port: 30001
      targetPort: dlv
      nodePort: 30001
  selector:
    app: kotsadm
