apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotsadm
spec:
  template:
    spec:
      containers:
        - name: kotsadm
          env:
            - name: STORAGE_BASEURI
              value: "docker://kotsadm-storage-registry:5000"
            - name: STORAGE_BASEURI_PLAINHTTP
              value: "true"
