bases:
  - ../../base
  - ../../../web/kustomize/overlays/dev
  - ../../../operator/kustomize/overlays/dev
  - ../../../kurl_proxy/kustomize/overlays/dev

resources:
  - ./dex-postgres-secret.yaml
  - ./configmap-init-dex-db.yaml

patches:
  - ./deployment.yaml
  - ./service.yaml
