apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotsadm
spec:
  template:
    spec:
      volumes:
        - name: host-cacerts
          hostPath:
            path: "${KOTSADM_TRUSTED_CERT_MOUNT}"
            type: File
      containers:
      - name: kotsadm
        volumeMounts:
        - mountPath: /etc/ssl/certs/ca-certificates.crt
          name: host-cacerts
