apiVersion: v1
kind: ConfigMap
metadata:
  name: kotsadm-storage-registry-config
  labels:
    app: docker-registry
    release: kots
data:
  config.yml: |-
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    http:
      addr: :5000
      headers:
        X-Content-Type-Options:
        - nosniff
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
    version: 0.1
---
apiVersion: v1
kind: Service
metadata:
  name: kotsadm-storage-registry
  labels:
    app: docker-registry
    release: kots
spec:
  type: ClusterIP
  ports:
    - port: 5000
      protocol: TCP
      name: registry
      targetPort: 5000
  selector:
    app: docker-registry
    release: kots
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kotsadm-storage-registry
  labels:
    app: docker-registry
    release: kots
spec:
  selector:
    matchLabels:
      app: docker-registry
      release: kots
  replicas: 1
  serviceName: kotsadm-storage-registry
  template:
    metadata:
      labels:
        app: docker-registry
        release: kots
      annotations:
        checksum/config: 149b8559e0123ecd57d5a161f88b51b44d7194aefb604f36e44dba2514952398
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      containers:
        - name: docker-registry
          image: "registry:2.7.1"
          imagePullPolicy: IfNotPresent
          command:
          - /bin/registry
          - serve
          - /etc/docker/registry/config.yml
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /
              port: 5000
          readinessProbe:
            httpGet:
              path: /
              port: 5000
          resources:
            {}
          env:
            - name: REGISTRY_HTTP_SECRET
              value: "password"
            - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
              value: "/var/lib/registry"
          volumeMounts:
            - name: registry-data
              mountPath: /var/lib/registry/
            - name: "kotsadm-storage-registry-config"
              mountPath: "/etc/docker/registry"
      volumes:
        - name: registry-data
          persistentVolumeClaim:
            claimName: registry-data
        - name: kotsadm-storage-registry-config
          configMap:
            name: kotsadm-storage-registry-config
  volumeClaimTemplates:
  - metadata:
      name: registry-data
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: 5Gi
