import { SessionStore } from "../session/session_store";
import { UserStore } from "../user";
import { ClusterStore } from "../cluster";
import { WatchStore } from "../watch/watch_store";
import { NotificationStore } from "../notification";
import { UpdateStore } from "../update/update_store";
import { UnforkStore } from "../unfork/unfork_store";
import { InitStore } from "../init/init_store";
import { FeatureStore } from "../feature/feature_store";
import { GithubNonceStore } from "../user/store";
import { HealthzStore } from "../healthz/healthz_store";
import { WatchDownload } from "../watch/download";
import { EditStore } from "../edit";
import { PendingStore } from "../pending";
import { HelmChartStore } from "../helmchart";
import { TroubleshootStore } from "../troubleshoot";
import { LicenseStore } from "../license";
import { KotsLicenseStore } from "../klicenses";
import { GithubInstallationsStore } from "../github_installation/github_installation_store";
import { PreflightStore } from "../preflight/preflight_store";
import { KotsAppStore } from "../kots_app/kots_app_store";
import { KotsAppStatusStore } from "../kots_app/kots_app_status_store";
import { KurlStore } from "../kurl/kurl_store";
import { MetricStore } from "../monitoring/metric_store";
import { ParamsStore } from "../params/params_store";

export interface Stores {
  sessionStore: SessionStore;
  userStore: UserStore;
  githubNonceStore: GithubNonceStore;
  clusterStore: ClusterStore;
  watchStore: WatchStore;
  notificationStore: NotificationStore;
  updateStore: UpdateStore;
  unforkStore: UnforkStore;
  initStore: InitStore;
  pendingStore: PendingStore;
  featureStore: FeatureStore;
  healthzStore: HealthzStore;
  watchDownload: WatchDownload;
  editStore: EditStore;
  helmChartStore: HelmChartStore;
  troubleshootStore: TroubleshootStore;
  licenseStore: LicenseStore;
  kotsLicenseStore: KotsLicenseStore;
  githubInstall: GithubInstallationsStore;
  preflightStore: PreflightStore;
  kotsAppStore: KotsAppStore;
  kotsAppStatusStore: KotsAppStatusStore;
  kurlStore: KurlStore;
  metricStore: MetricStore;
  paramsStore: ParamsStore;
}
