apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: app
spec:
  name: app
  schema:
    rqlite:
      strict: true
      primaryKey:
      - id
      columns:
      - name: id
        type: text
        constraints:
          notNull: true
      - name: name
        type: text
        constraints:
          notNull: true
      - name: icon_uri
        type: text
      - name: created_at
        type: integer
        constraints:
          notNull: true
      - name: updated_at
        type: integer
      - name: slug
        type: text
        constraints:
          notNull: true
      - name: upstream_uri
        type: text
        constraints:
          notNull: true
      - name: license
        type: text
      - name: current_sequence
        type: integer
      - name: last_update_check_at
        type: integer
      - name: is_all_users
        type: integer
      - name: registry_hostname
        type: text
      - name: registry_username
        type: text
      - name: registry_password
        type: text
      - name: registry_password_enc
        type: text
      - name: namespace
        type: text
      - name: registry_is_readonly
        type: integer
      - name: last_registry_sync
        type: integer
      - name: last_license_sync
        type: integer
      - name: install_state
        type: text
      - name: is_airgap
        type: integer
        default: 0
      - name: snapshot_ttl_new
        type: text
        default: '720h'
        constraints:
          notNull: true
      - name: snapshot_schedule
        type: text
      - name: restore_in_progress_name
        type: text
      - name: restore_undeploy_status
        type: text
      - name: update_checker_spec
        type: text
        default: '@default'
      - name: semver_auto_deploy
        type: text
        default: 'disabled'
      - name: channel_changed
        type: integer
        default: 0
        constraints:
          notNull: true
      - name: channel_id
        type: text
