apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: app-downstream
spec:
  name: app_downstream
  requires: []
  schema:
    rqlite:
      strict: true
      primaryKey:
        - app_id
        - cluster_id
      columns:
      - name: app_id
        type: text
        constraints:
          notNull: true
      - name: cluster_id
        type: text
        constraints:
          notNull: true
      - name: downstream_name
        type: text
        constraints:
          notNull: true
      - name: current_sequence
        type: integer
