apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: app-version
spec:
  name: app_version
  requires: []
  schema:
    rqlite:
      strict: true
      primaryKey:
        - app_id
        - sequence
      columns:
      - name: app_id
        type: text
        constraints:
          notNull: true
      - name: sequence
        type: integer
        constraints:
          notNull: true
      - name: update_cursor
        type: text
      - name: channel_id
        type: text
      - name: channel_name
        type: text
      - name: upstream_released_at
        type: integer
      - name: created_at
        type: integer
      - name: version_label
        type: text
        constraints:
          notNull: true
      - name: is_required
        type: integer
        constraints:
          notNull: true
        default: 0
      - name: release_notes
        type: text
      - name: supportbundle_spec
        type: text
      - name: preflight_spec
        type: text
      - name: analyzer_spec
        type: text
      - name: app_spec
        type: text
      - name: kots_app_spec
        type: text
      - name: kots_installation_spec
        type: text
      - name: kots_license
        type: text
      - name: config_spec
        type: text
      - name: applied_at
        type: integer
      - name: status
        type: text
      - name: encryption_key
        type: text
      - name: backup_spec
        type: text
      - name: identity_spec
        type: text
      - name: branding_archive
        type: text
      - name: embeddedcluster_config
        type: text
