apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: app-status
spec:
  name: app_status
  requires: []
  schema:
    rqlite:
      strict: true
      primaryKey:
        - app_id
      columns:
      - name: app_id
        type: text
        constraints:
          notNull: true
      - name: resource_states
        type: text
      - name: updated_at
        type: integer
      - name: sequence
        type: integer
