apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: app-downstream-output
spec:
  database: kotsadm-postgres
  name: app_downstream_output
  requires: []
  schema:
    postgres:
      primaryKey:
        - app_id
        - cluster_id
        - downstream_sequence
      columns:
      - name: app_id
        type: text
        constraints:
          notNull: true
      - name: cluster_id
        type: text
        constraints:
          notNull: true
      - name: downstream_sequence
        type: integer
        constraints:
          notNull: true
      - name: dryrun_stdout
        type: text
      - name: dryrun_stderr
        type: text
      - name: apply_stdout
        type: text
      - name: apply_stderr
        type: text
      - name: helm_stdout
        type: text
      - name: helm_stderr
        type: text
      - name: is_error
        type: boolean