apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: cluster
spec:
  name: cluster
  schema:
    rqlite:
      strict: true
      primaryKey:
      - id
      indexes:
      - columns:
        - token
        name: cluster_token_key
        isUnique: true
      columns:
      - name: id
        type: text
        constraints:
          notNull: true
      - name: title
        type: text
        constraints:
          notNull: true
      - name: slug
        type: text
        constraints:
          notNull: true
      - name: created_at
        type: integer
        constraints:
          notNull: true
      - name: updated_at
        type: integer
      - name: token
        type: text
      - name: cluster_type
        type: text
        constraints:
          notNull: true
        default: 'gitops'
      - name: is_all_users
        type: integer
        constraints:
          notNull: true
        default: 0
      - name: snapshot_schedule
        type: text
      - name: snapshot_ttl
        type: text
        default: '720h'
        constraints:
          notNull: true
