apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: embedded-cluster-tokens
spec:
  name: embedded_cluster_tokens
  requires: []
  schema:
    rqlite:
      strict: true
      primaryKey:
      - token
      columns:
      - name: token
        type: text
        constraints:
          notNull: true
      - name: roles
        type: text
        constraints:
          notNull: true
