apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: instance-report
spec:
  name: instance_report
  requires: []
  schema:
    rqlite:
      strict: true
      primaryKey:
        - created_at
      columns:
      - name: created_at
        type: integer
      - name: license_id
        type: text
      - name: instance_id
        type: text
      - name: cluster_id
        type: text
      - name: app_status
        type: text
      - name: is_kurl
        type: integer
      - name: kurl_node_count_total
        type: integer
      - name: kurl_node_count_ready
        type: integer
      - name: k8s_version
        type: text
      - name: kots_version
        type: text
      - name: kots_install_id
        type: text
      - name: kurl_install_id
        type: text
      - name: embedded_cluster_id
        type: text
      - name: is_gitops_enabled
        type: integer
      - name: gitops_provider
        type: text
# downstream stuff
      - name: downstream_channel_id
        type: text
      - name: downstream_channel_sequence
        type: integer
      - name: downstream_channel_name
        type: text
      - name: downstream_sequence
        type: integer
      - name: downstream_source
        type: text
      - name: install_status
        type: text
      - name: preflight_state
        type: text
      - name: skip_preflights
        type: integer
      - name: repl_helm_installs
        type: integer
      - name: native_helm_installs
        type: integer