apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: kotsadm-params
spec:
  name: kotsadm_params
  requires: []
  schema:
    rqlite:
      strict: true
      primaryKey:
      - key
      columns:
      - name: key
        type: text
        constraints:
          notNull: true
      - name: value
        type: text
        constraints:
          notNull: true
