apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: pending-supportbundle
spec:
  name: pending_supportbundle
  requires: []
  schema:
    rqlite:
      strict: true
      primaryKey:
        - id
      columns:
      - name: id
        type: text
        constraints:
          notNull: true
      - name: app_id
        type: text
        constraints:
          notNull: true
      - name: cluster_id
        type: text
        constraints:
          notNull: true
      - name: created_at
        type: integer
