apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: plan
spec:
  name: plan
  schema:
    rqlite:
      strict: true
      primaryKey:
      - app_id
      - version_label
      columns:
      - name: app_id
        type: text
        constraints:
          notNull: true
      - name: version_label
        type: text
        constraints:
          notNull: true
      - name: created_at
        type: integer
        constraints:
          notNull: true
      - name: updated_at
        type: integer
        constraints:
          notNull: true
      - name: status
        type: text
        constraints:
          notNull: true
      - name: plan
        type: text
        constraints:
          notNull: true
