apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: preflight-spec
spec:
  name: preflight_spec
  schema:
    rqlite:
      strict: true
      primaryKey:
      - watch_id
      - sequence
      columns:
      - name: watch_id
        type: text
        constraints:
          notNull: true
      - name: sequence
        type: integer
        constraints:
          notNull: true
      - name: spec
        type: text
        constraints:
          notNull: true