apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: preflight-result
spec:
  name: preflight_result
  requires: []
  schema:
    rqlite:
      strict: true
      primaryKey:
      - id
      columns:
      - name: id
        type: text
        constraints:
          notNull: true
      - name: watch_id
        type: text
        constraints:
          notNull: true
      - name: result
        type: text
        constraints:
          notNull: true
      - name: created_at
        type: integer
        constraints:
          notNull: true

