apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: scheduled-instance-snapshots
spec:
  name: scheduled_instance_snapshots
  schema:
    rqlite:
      strict: true
      primaryKey:
      - id
      columns:
      - name: id
        type: text
        constraints:
          notNull: true
      - name: cluster_id
        type: text
        constraints:
          notNull: true
      - name: scheduled_timestamp
        type: integer
        constraints:
          notNull: true
      - name: backup_name
        type: text
