## no longer used, must keep for migrations to complete
apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: session
spec:
  name: session
  requires: []
  schema:
    rqlite:
      strict: true
      primaryKey:
      - id
      columns:
      - name: id
        type: text
        constraints:
          notNull: true
      - name: user_id
        type: text
        constraints:
          notNull: true
      - name: metadata
        type: text
        constraints:
          notNull: true
      - name: issued_at
        type: integer
      - name: expire_at
        type: integer
        constraints:
          notNull: true
