apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: ship-user
spec:
  name: ship_user
  requires: []
  schema:
    rqlite:
      strict: true
      primaryKey:
      - id
      columns:
      - name: id
        type: text
        constraints:
          notNull: true
      - name: created_at
        type: integer
      - name: github_id
        type: integer
      - name: last_login
        type: integer
      