## no longer used, must keep for migrations to complete
apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: supportbundle
spec:
  name: supportbundle
  requires: []
  schema:
    rqlite:
      strict: true
      primaryKey:
      - id
      columns:
      - name: id
        type: text
        constraints:
          notNull: true
      - name: slug # TODO: unique????
        type: text
        constraints:
          notNull: true
      - name: watch_id
        type: text
        constraints:
          notNull: true
      - name: name
        type: text
      - name: size
        type: integer
      - name: status
        type: text
        constraints:
          notNull: true
      - name: tree_index
        type: text
      - name: analysis_id
        type: text
      - name: created_at
        type: integer
        constraints:
          notNull: true
      - name: uploaded_at
        type: integer
      - name: shared_at
        type: integer
      - name: is_archived
        type: integer
      - name: redact_report
        type: text
