apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: supportbundle-analysis
spec:
  name: supportbundle_analysis
  requires: []
  schema:
    rqlite:
      strict: true
      primaryKey:
      - id
      columns:
      - name: id
        type: text
        constraints:
          notNull: true
      - name: supportbundle_id
        type: text
        constraints:
          notNull: true
      - name: error
        type: text
      - name: max_severity
        type: text
      - name: insights
        type: text
      - name: created_at
        type: integer
        constraints:
          notNull: true
