apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: user-app
spec:
  name: user_app
  requires: []
  schema:
    rqlite:
      strict: true
      primaryKey:
      - user_id
      - app_id
      columns:
      - name: user_id
        type: text
        constraints:
          notNull: true
      - name: app_id
        type: text
        constraints:
          notNull: true