name: Test kURL Add-On
description: Test kURL Add-On

inputs:
  addon_version:
    type: string
    description: "Kots version (without the 'v')."
    required: true
  addon_package_url:
    type: string
    description: "S3 package url (from actions/kurl-addon-kots-generate)"
    required: true
  priority:
    type: number
    description: 'Testgrid run priority.'
    default: 0
  testgrid_api_token:
    type: string
    description: "Testgrid API token."
    required: true
outputs:
  testgrid_run_message:
    description: "Testgrid run message"
    value: ${{ steps.testgrid-run.outputs.message }}

runs:
  using: "composite"
  steps:

    - name: set outputs
      id: vars
      shell: bash
      run: |
        echo "sha_short=${GITHUB_SHA:0:7}" >> "$GITHUB_OUTPUT"
        echo "ref_name=${GITHUB_REF_NAME//\//"-"}" >> "$GITHUB_OUTPUT" # replace forward slashes

    - uses: replicatedhq/kurl/.github/actions/addon-testgrid-tester@main
      id: testgrid-run
      with:
        addon: "kotsadm"
        version: "${{ inputs.addon_version }}"
        package-url: "${{ inputs.addon_package_url }}"
        testgrid-spec-path: "${{ github.action_path }}/../../../deploy/kurl/kotsadm/template/testgrid"
        testgrid-os-spec-path: "${{ github.action_path }}/../../../deploy/kurl/kotsadm/testgrid-os-spec.yaml"
        testgrid-run-prefix: "KOTS-${{ inputs.addon_version }}-${{ steps.vars.outputs.ref_name }}-${{ steps.vars.outputs.sha_short }}"
        testgrid-api-token: "${{ inputs.testgrid_api_token }}"
        priority: "${{ inputs.priority }}"
