apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotsadm-web
spec:
  selector:
    matchLabels:
      app: kotsadm-web
  template:
    metadata:
      labels:
        app: kotsadm-web
    spec:
      containers:
        - name: kotsadm-web
          image: kotsadm-web-dev
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
