FROM golang:1.24-alpine

RUN apk add --no-cache ca-certificates curl git make bash

WORKDIR /replicatedhq/kots/kurl_proxy

COPY ./bin/kurl_proxy /kurl_proxy

ADD ./assets /assets

ENTRYPOINT ["/kurl_proxy"]
