FROM golang:1.14 as builder

ENV PROJECTPATH=/go/src/github.com/replicatedhq/kots/kotsadm/kurl_proxy
WORKDIR $PROJECTPATH
ADD Makefile ./
ADD go.mod ./
ADD go.sum ./
ADD cmd ./cmd

RUN make build

FROM scratch
ADD assets /assets
COPY --from=builder /go/src/github.com/replicatedhq/kots/kotsadm/kurl_proxy/bin/kurl_proxy /kurl_proxy

ENTRYPOINT ["/kurl_proxy"]
