name: 'KOTS GKE Delete'
description: 'Composite action for deleting a GKE cluster used for KOTS tests'
inputs:
  service-key:
    description: 'Service key to authenticate a Google Cloud service account'
    required: false

  cluster-region:
    description: GKE cluster region to use
    default: 'us-west1'
    required: false

  project:
    description: Google Cloud project name
    default: 'replicated-qa'
    required: false

runs:
  using: "composite"
  steps:
    - name: Generate GKE cluster name
      id: cluster-name
      shell: bash
      run: |
        echo "cluster_name=kots-ci-${{ github.run_id }}-${{ github.run_attempt }}-$(echo '${{ github.job }}' | cut -c -18)" >> $GITHUB_OUTPUT
      
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ inputs.service-key }}

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        install_components: 'gke-gcloud-auth-plugin'

    - name: Get GKE cluster credentials for kubectl
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ steps.cluster-name.outputs.cluster_name }}
        location: ${{ inputs.cluster-region }}
        project_id: ${{ inputs.project }}

    - name: Delete GKE cluster if flagged
      shell: bash
      run: |
        gcloud -q container clusters delete "${{ steps.cluster-name.outputs.cluster_name }}" --project "${{ inputs.project }}" --region "${{ inputs.cluster-region }}"
