FROM repldev/ship-operator-tools

# Copy in the go src
WORKDIR /go/src/github.com/replicatedhq/ship-operator-tools
COPY pkg/    pkg/
COPY cmd/    cmd/
COPY vendor/ vendor/
COPY Makefile Makefile

# Build
RUN make bin/ship-operator-tools

RUN cp bin/ship-operator-tools /usr/local/bin/ship-operator-tools

ENTRYPOINT ["/usr/local/bin/ship-operator-tools"]
