apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotsadm-web
spec:
  template:
    spec:
      imagePullSecrets:
        - name: replicatedregistrykey
      containers:
        - name: kotsadm-web
          image: registry.replicated.com/ship-enterprise/kotsadm-web
          args: ["/scripts/start-kotsadm-web.sh"]
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
            - name: kotsadm-web-scripts
              mountPath: /scripts/start-kotsadm-web.sh
              subPath: start-kotsadm-web.sh
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 1
      volumes:
      - name: kotsadm-web-scripts
        configMap:
          name: kotsadm-web-scripts
          defaultMode: 0744
