apiVersion: kots.io/v1beta1
kind: License
metadata:
  name: typeexistingclusterenvairgappedphasenewinstallrbacclusteradmin
spec:
  appSlug: qakotsregression
  channelID: 1riP4oQC5ZOaqciRwLf14I6yn2l
  channelName: type=existing cluster, env=airgapped, phase=new install, rbac=cluster
    admin
  customerName: type=existing cluster, env=airgapped, phase=new install, rbac=cluster
    admin
  endpoint: https://replicated.app
  entitlements:
    bool_field_1:
      title: Boolean Field 1
      value: true
      valueType: Boolean
    expires_at:
      description: License Expiration
      title: Expiration
      value: ""
      valueType: String
    hidden_field_1:
      isHidden: true
      title: Hidden Field 1
      value: hide me updated
      valueType: String
    int_field_1:
      title: Integer Field 1
      value: 123
      valueType: Integer
    required_field_1:
      title: Required Field 1
      value: require me
      valueType: String
    str_field_1:
      title: String Field 1
      value: abc
      valueType: String
    txt_field_1:
      title: Text Field 1
      value: |-
        abc
        xyz
      valueType: Text
  isAirgapSupported: true
  isGitOpsSupported: true
  isNewKotsUiEnabled: true
  isSnapshotSupported: true
  licenseID: 1riYWkuo5PdMtD4imgTYX699IdU
  licenseSequence: 10
  licenseType: prod
  signature: eyJsaWNlbnNlRGF0YSI6ImV5SmhjR2xXWlhKemFXOXVJam9pYTI5MGN5NXBieTkyTVdKbGRHRXhJaXdpYTJsdVpDSTZJa3hwWTJWdWMyVWlMQ0p0WlhSaFpHRjBZU0k2ZXlKdVlXMWxJam9pZEhsd1pXVjRhWE4wYVc1blkyeDFjM1JsY21WdWRtRnBjbWRoY0hCbFpIQm9ZWE5sYm1WM2FXNXpkR0ZzYkhKaVlXTmpiSFZ6ZEdWeVlXUnRhVzRpZlN3aWMzQmxZeUk2ZXlKc2FXTmxibk5sU1VRaU9pSXhjbWxaVjJ0MWJ6VlFaRTEwUkRScGJXZFVXVmcyT1RsSlpGVWlMQ0pzYVdObGJuTmxWSGx3WlNJNkluQnliMlFpTENKamRYTjBiMjFsY2s1aGJXVWlPaUowZVhCbFBXVjRhWE4wYVc1bklHTnNkWE4wWlhJc0lHVnVkajFoYVhKbllYQndaV1FzSUhCb1lYTmxQVzVsZHlCcGJuTjBZV3hzTENCeVltRmpQV05zZFhOMFpYSWdZV1J0YVc0aUxDSmhjSEJUYkhWbklqb2ljV0ZyYjNSemNtVm5jbVZ6YzJsdmJpSXNJbU5vWVc1dVpXeEpSQ0k2SWpGeWFWQTBiMUZETlZwUFlYRmphVkozVEdZeE5FazJlVzR5YkNJc0ltTm9ZVzV1Wld4T1lXMWxJam9pZEhsd1pUMWxlR2x6ZEdsdVp5QmpiSFZ6ZEdWeUxDQmxiblk5WVdseVoyRndjR1ZrTENCd2FHRnpaVDF1WlhjZ2FXNXpkR0ZzYkN3Z2NtSmhZejFqYkhWemRHVnlJR0ZrYldsdUlpd2liR2xqWlc1elpWTmxjWFZsYm1ObElqb3hNQ3dpWlc1a2NHOXBiblFpT2lKb2RIUndjem92TDNKbGNHeHBZMkYwWldRdVlYQndJaXdpWlc1MGFYUnNaVzFsYm5SeklqcDdJbUp2YjJ4ZlptbGxiR1JmTVNJNmV5SjBhWFJzWlNJNklrSnZiMnhsWVc0Z1JtbGxiR1FnTVNJc0luWmhiSFZsSWpwMGNuVmxMQ0oyWVd4MVpWUjVjR1VpT2lKQ2IyOXNaV0Z1SW4wc0ltVjRjR2x5WlhOZllYUWlPbnNpZEdsMGJHVWlPaUpGZUhCcGNtRjBhVzl1SWl3aVpHVnpZM0pwY0hScGIyNGlPaUpNYVdObGJuTmxJRVY0Y0dseVlYUnBiMjRpTENKMllXeDFaU0k2SWlJc0luWmhiSFZsVkhsd1pTSTZJbE4wY21sdVp5SjlMQ0pvYVdSa1pXNWZabWxsYkdSZk1TSTZleUowYVhSc1pTSTZJa2hwWkdSbGJpQkdhV1ZzWkNBeElpd2lkbUZzZFdVaU9pSm9hV1JsSUcxbElIVndaR0YwWldRaUxDSjJZV3gxWlZSNWNHVWlPaUpUZEhKcGJtY2lMQ0pwYzBocFpHUmxiaUk2ZEhKMVpYMHNJbWx1ZEY5bWFXVnNaRjh4SWpwN0luUnBkR3hsSWpvaVNXNTBaV2RsY2lCR2FXVnNaQ0F4SWl3aWRtRnNkV1VpT2pFeU15d2lkbUZzZFdWVWVYQmxJam9pU1c1MFpXZGxjaUo5TENKeVpYRjFhWEpsWkY5bWFXVnNaRjh4SWpwN0luUnBkR3hsSWpvaVVtVnhkV2x5WldRZ1JtbGxiR1FnTVNJc0luWmhiSFZsSWpvaWNtVnhkV2x5WlNCdFpTSXNJblpoYkhWbFZIbHdaU0k2SWxOMGNtbHVaeUo5TENKemRISmZabWxsYkdSZk1TSTZleUowYVhSc1pTSTZJbE4wY21sdVp5QkdhV1ZzWkNBeElpd2lkbUZzZFdVaU9pSmhZbU1pTENKMllXeDFaVlI1Y0dVaU9pSlRkSEpwYm1jaWZTd2lkSGgwWDJacFpXeGtYekVpT25zaWRHbDBiR1VpT2lKVVpYaDBJRVpwWld4a0lERWlMQ0oyWVd4MVpTSTZJbUZpWTF4dWVIbDZJaXdpZG1Gc2RXVlVlWEJsSWpvaVZHVjRkQ0o5ZlN3aWFYTkJhWEpuWVhCVGRYQndiM0owWldRaU9uUnlkV1VzSW1selIybDBUM0J6VTNWd2NHOXlkR1ZrSWpwMGNuVmxMQ0pwYzFOdVlYQnphRzkwVTNWd2NHOXlkR1ZrSWpwMGNuVmxMQ0pwYzA1bGQwdHZkSE5WYVVWdVlXSnNaV1FpT25SeWRXVjlmUT09IiwiaW5uZXJTaWduYXR1cmUiOiJleUpzYVdObGJuTmxVMmxuYm1GMGRYSmxJam9pVDJOcGIzUnpabXBZYzIwNGF5OHdhR05zVURablpEaDFVRVZLVG1SNmF6VnBRVXcyZFZabGVXSmxXa00yV214b2NuaG1UWFpsYTJGSFVVTnVkalpGTVV4dWFFdFpWRk5OYkdFNGNFOUtUSHBHWTBoRWRraHFWRGh5ZEZSclJUSlFSM2xxTmxwTmVXWXpZbFp0YVc5SllrOHpaMk56YlRSSU5rOXVURFpWY1dkcFlsZ3plazB2WnpsemFHNTJXbE5RVm5FMlRUbHNSRzFoTkU0elEyd3pTazgyWjFwVFpXeEZhbGhEUWs5TlZXZE5XSFkyVG5oYU16bEdTa0ZMZVZKaE1HbElkR3d4TW5OWFdtaDJRa05LU0RoQlZ6UjFXa1pZUTNOWlMyNU1VWFp6UTNCc05pdDRZbVpXY0RsSWFsTjRTMHhoUkhvNVpVcDJWME5PVmpSTldFZHZObFUwTkhJeWJYTlNjVVphVW5wd2MyVnpWRk5sWmxKMVVVWnhWRUV5YzB4SU1tNW5kRlIxUVhWUVEwdFRNbmRXY0hwcGJUUkJhVXBVZUdNNVZTdFVXak5UU25odWEzQlRVMVUxTHpJeWIwOUJSbk5SUFQwaUxDSndkV0pzYVdOTFpYa2lPaUl0TFMwdExVSkZSMGxPSUZCVlFreEpReUJMUlZrdExTMHRMVnh1VFVsSlFrbHFRVTVDWjJ0eGFHdHBSemwzTUVKQlVVVkdRVUZQUTBGUk9FRk5TVWxDUTJkTFEwRlJSVUYxYkZWS2J5dEtkV2xFUm05bWRGQnpNWE4xYWx4dWFGZGtOMWxCUlhoeWNraHZaemRVYjJwRE1HVnhNWEJCYkZOWFJsRnhZbWxsZVdOdVVVRTRObXhXVURoSGNXa3hhMk55Tm1rMlRrRjBhM1JPVEZGalpseHVXV2xYUkhGTE1ESjJkbFUzYVhSbFZWcExaRk5rSzB0WVpsaFlUbXd4TWtscVRtczFiR1F2UkZWc01IaFNWWE5oTDBObVUzVlRTMmhpZDFNM01IcHJVMXh1TkUxQmEweHVabFJaUzNKdGMybGhNSGM0VFU1VFpXcEdVVzV3UjA1RmExWmxjMWxrWTI1aWVXWm5kbGxzU0hwcEszRXliRXRRU21jek5qa3lOMnBPU0Z4dVJXcDZSV3hOV21GcVIycEVORmMyYmxoUk0xWnVWbFl4V1Vkck1WcGpaRXBFYldZelMzRXlNRTVYZURKR2R6ZFZaVzE2WVcwMFVDOUdXRzV5YzBoRlRGeHVTWEZSTlhGa1JEQkRhbkZsUldJck1YVldOMDlwU1V4S2FFRkVkV0Z0VlZGNGFUaFdVM05PYzFodGVqbHNRVFZRUW1OV2NqUmFjSEJNVDFaak4yTkRkbHh1TkZGSlJFRlJRVUpjYmkwdExTMHRSVTVFSUZCVlFreEpReUJMUlZrdExTMHRMVnh1SWl3aWEyVjVVMmxuYm1GMGRYSmxJam9pWlhsS2VtRlhaSFZaV0ZJeFkyMVZhVTlwU25aa2EwMTVZbXBGTlZKdWFGaE9la0paWkc1a1QxRllUbUZNZW1SdlpHMXNkbVZ0V1hkTlJWcDBaRlJDVDAxSVdsRk9XR2hQVmtob2ExWklhRlJXYkdSaFRtNXJNVlJHYUU1aVJYUjNZMnh3Yms5Rk9YRlVibFY1WW10U2MwMXRUakZpTWxsNVlrZEZkMlZYZUZWa2F6VjVZVlZTYlZwRVpHeGpiVEZTVTJ0U2MyUnRNWFJsVkVaUVZWZDRWRk5GVG5aaFZrNXBUMFZqZVdGRVFtdFhWMDVGWW0xYWRrOVZkelJXUld4UFV6QjRhR1JYV2xwaGJXaFlZVlJrTmxsVVNtbFdSa293VTJ4R1IxWnNjRkpWYXpCNVV6SktObE5IYkhsUmJWcG9VVEZDU0ZwVVNqSlVSemd4V210b2VGUnFUbFZQU0doYVltMHdjazVVVWxCaU1EUjVZbXhaY2s5SE1YQlphbVJ5Vm5wc1YyRnNUbUZVVm5CdlRqSktkRkZXY0hoWGF6bFdWVEJqTVdOR2NGSk9NVkV5VWxob2IxVnRXbUZqU0VwMVdWaGpNMVpJU25aaE1qVnNZbFJTUWsxWFJtdGpia1Y0VTNrNWJWUkdWbWxUVjBwVVZtdFpORTlWWkhOaVIwWXdaRzA1VG1GR2FGcGlhbFkyWW5rNVVsWXpVbTVpYkdNMVVXMXNkRTF0T1cxbGEzaFNXVzFGZVZWVlZuWlVNMVpIVWpBMVNWZHJOWGxWVmxKSlZtdEtkV0pJVWtaVWEyeFZZbFpyZUZKR1NUTlNWRUp3VmxOME5FOUlZemxRVTBselNXMWtjMkl5U21oaVJYUnNaVlZzYTBscWIybFpiVkpzV2xSVk1rNVVXWGRaTWxwcFRrUk9hazlYU1hsUFIwcHRUMVJvYkZsWFRtaGFiVVV5VGtSWmFXWlJQVDBpZlE9PSJ9
