steps:
  - label: build
    commands:
      - make kots test
    plugins:
      - docker#v3.2.0:
          image: replicated/gitops-builder:buildkite-go12-node10
          always-pull: true
          mount-checkout: true
          workdir: /go/src/github.com/replicatedhq/kots

  - wait

  - commands:
      - make snapshot-release
    branches: "master"
    plugins:
      - docker#v3.2.0:
          image: replicated/gitops-builder:buildkite-go12-node10
          always-pull: true
          mount-checkout: true
          workdir: /go/src/github.com/replicatedhq/kots
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "/var/lib/buildkite-agent/.docker/config.json:/home/builder/.docker/config.json"

  - label: release
    commands:
      - if [ -z "$BUILDKITE_TAG" ]; then echo "Not a tag, not releasing"; else git tag -f "$BUILDKITE_TAG" && make release; fi
    plugins:
      - docker#v3.2.0:
          always-pull: true
          image: replicated/gitops-builder:buildkite-go12-node10
          workdir: /go/src/github.com/replicatedhq/kots
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "/var/lib/buildkite-agent/.docker/config.json:/home/builder/.docker/config.json"
          environment:
            - GITHUB_TOKEN_REPLICATEDBOT
