export const NAMESPACE = "qakotsregression";
export const VENDOR_INITIAL_CHANNEL_SEQUENCE = 83;
export const VENDOR_UPDATE_CHANNEL_SEQUENCE = 84;
export const LICENSE_ID = "1quls1rUvyduplcjShmd9WFLwM2";
export const CUSTOMER_ID = "1quls067uTEUQdI04hnVZ5nvEjD";
export const CUSTOMER_NAME = "type=existing cluster, env=online, phase=upgraded install, rbac=cluster admin";
export const CHANNEL_NAME = "type=existing cluster, env=online, phase=upgraded install, rbac=cluster admin";
export const CHANNEL_ID = "1quljaTjeLhOGlxZN7tLh9nSUxT";
export const CHANNEL_SLUG = "type-existing-cluster-env-on-1";
export const VELERO_VERSION = "v1.12.1";
export const VELERO_AWS_PLUGIN_VERSION = "v1.8.1";
export const IS_EC = false;
export const IS_EXISTING_CLUSTER = true;
export const IS_AIRGAPPED = false;
export const IS_AIRGAP_SUPPORTED = true;
export const IS_MINIMAL_RBAC = false;
