/*
Copyright 2019 Replicated, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/replicatedhq/kots/kotskinds/apis/kots/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLicenses implements LicenseInterface
type FakeLicenses struct {
	Fake *FakeKotsV1beta1
	ns   string
}

var licensesResource = schema.GroupVersionResource{Group: "kots.io", Version: "v1beta1", Resource: "licenses"}

var licensesKind = schema.GroupVersionKind{Group: "kots.io", Version: "v1beta1", Kind: "License"}

// Get takes name of the license, and returns the corresponding license object, and an error if there is any.
func (c *FakeLicenses) Get(name string, options v1.GetOptions) (result *v1beta1.License, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(licensesResource, c.ns, name), &v1beta1.License{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.License), err
}

// List takes label and field selectors, and returns the list of Licenses that match those selectors.
func (c *FakeLicenses) List(opts v1.ListOptions) (result *v1beta1.LicenseList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(licensesResource, licensesKind, c.ns, opts), &v1beta1.LicenseList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.LicenseList{ListMeta: obj.(*v1beta1.LicenseList).ListMeta}
	for _, item := range obj.(*v1beta1.LicenseList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested licenses.
func (c *FakeLicenses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(licensesResource, c.ns, opts))

}

// Create takes the representation of a license and creates it.  Returns the server's representation of the license, and an error, if there is any.
func (c *FakeLicenses) Create(license *v1beta1.License) (result *v1beta1.License, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(licensesResource, c.ns, license), &v1beta1.License{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.License), err
}

// Update takes the representation of a license and updates it. Returns the server's representation of the license, and an error, if there is any.
func (c *FakeLicenses) Update(license *v1beta1.License) (result *v1beta1.License, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(licensesResource, c.ns, license), &v1beta1.License{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.License), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeLicenses) UpdateStatus(license *v1beta1.License) (*v1beta1.License, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(licensesResource, "status", c.ns, license), &v1beta1.License{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.License), err
}

// Delete takes name of the license and deletes it. Returns an error if one occurs.
func (c *FakeLicenses) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(licensesResource, c.ns, name), &v1beta1.License{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLicenses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(licensesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.LicenseList{})
	return err
}

// Patch applies the patch and returns the patched license.
func (c *FakeLicenses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.License, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(licensesResource, c.ns, name, pt, data, subresources...), &v1beta1.License{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.License), err
}
