/*
Copyright 2019 Replicated, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/replicatedhq/kots/kotskinds/apis/kots/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKurlValueses implements KurlValuesInterface
type FakeKurlValueses struct {
	Fake *FakeKotsV1beta1
	ns   string
}

var kurlvaluesesResource = schema.GroupVersionResource{Group: "kots.io", Version: "v1beta1", Resource: "kurlvalueses"}

var kurlvaluesesKind = schema.GroupVersionKind{Group: "kots.io", Version: "v1beta1", Kind: "KurlValues"}

// Get takes name of the kurlValues, and returns the corresponding kurlValues object, and an error if there is any.
func (c *FakeKurlValueses) Get(name string, options v1.GetOptions) (result *v1beta1.KurlValues, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kurlvaluesesResource, c.ns, name), &v1beta1.KurlValues{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.KurlValues), err
}

// List takes label and field selectors, and returns the list of KurlValueses that match those selectors.
func (c *FakeKurlValueses) List(opts v1.ListOptions) (result *v1beta1.KurlValuesList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kurlvaluesesResource, kurlvaluesesKind, c.ns, opts), &v1beta1.KurlValuesList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.KurlValuesList{ListMeta: obj.(*v1beta1.KurlValuesList).ListMeta}
	for _, item := range obj.(*v1beta1.KurlValuesList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kurlValueses.
func (c *FakeKurlValueses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kurlvaluesesResource, c.ns, opts))

}

// Create takes the representation of a kurlValues and creates it.  Returns the server's representation of the kurlValues, and an error, if there is any.
func (c *FakeKurlValueses) Create(kurlValues *v1beta1.KurlValues) (result *v1beta1.KurlValues, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kurlvaluesesResource, c.ns, kurlValues), &v1beta1.KurlValues{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.KurlValues), err
}

// Update takes the representation of a kurlValues and updates it. Returns the server's representation of the kurlValues, and an error, if there is any.
func (c *FakeKurlValueses) Update(kurlValues *v1beta1.KurlValues) (result *v1beta1.KurlValues, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kurlvaluesesResource, c.ns, kurlValues), &v1beta1.KurlValues{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.KurlValues), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKurlValueses) UpdateStatus(kurlValues *v1beta1.KurlValues) (*v1beta1.KurlValues, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(kurlvaluesesResource, "status", c.ns, kurlValues), &v1beta1.KurlValues{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.KurlValues), err
}

// Delete takes name of the kurlValues and deletes it. Returns an error if one occurs.
func (c *FakeKurlValueses) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(kurlvaluesesResource, c.ns, name), &v1beta1.KurlValues{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKurlValueses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kurlvaluesesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.KurlValuesList{})
	return err
}

// Patch applies the patch and returns the patched kurlValues.
func (c *FakeKurlValueses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.KurlValues, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kurlvaluesesResource, c.ns, name, pt, data, subresources...), &v1beta1.KurlValues{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.KurlValues), err
}
