/*
Copyright 2019 Replicated, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/replicatedhq/kots/kotskinds/apis/kots/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHelmCharts implements HelmChartInterface
type FakeHelmCharts struct {
	Fake *FakeKotsV1beta1
	ns   string
}

var helmchartsResource = schema.GroupVersionResource{Group: "kots.io", Version: "v1beta1", Resource: "helmcharts"}

var helmchartsKind = schema.GroupVersionKind{Group: "kots.io", Version: "v1beta1", Kind: "HelmChart"}

// Get takes name of the helmChart, and returns the corresponding helmChart object, and an error if there is any.
func (c *FakeHelmCharts) Get(name string, options v1.GetOptions) (result *v1beta1.HelmChart, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(helmchartsResource, c.ns, name), &v1beta1.HelmChart{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.HelmChart), err
}

// List takes label and field selectors, and returns the list of HelmCharts that match those selectors.
func (c *FakeHelmCharts) List(opts v1.ListOptions) (result *v1beta1.HelmChartList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(helmchartsResource, helmchartsKind, c.ns, opts), &v1beta1.HelmChartList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.HelmChartList{ListMeta: obj.(*v1beta1.HelmChartList).ListMeta}
	for _, item := range obj.(*v1beta1.HelmChartList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested helmCharts.
func (c *FakeHelmCharts) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(helmchartsResource, c.ns, opts))

}

// Create takes the representation of a helmChart and creates it.  Returns the server's representation of the helmChart, and an error, if there is any.
func (c *FakeHelmCharts) Create(helmChart *v1beta1.HelmChart) (result *v1beta1.HelmChart, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(helmchartsResource, c.ns, helmChart), &v1beta1.HelmChart{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.HelmChart), err
}

// Update takes the representation of a helmChart and updates it. Returns the server's representation of the helmChart, and an error, if there is any.
func (c *FakeHelmCharts) Update(helmChart *v1beta1.HelmChart) (result *v1beta1.HelmChart, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(helmchartsResource, c.ns, helmChart), &v1beta1.HelmChart{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.HelmChart), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHelmCharts) UpdateStatus(helmChart *v1beta1.HelmChart) (*v1beta1.HelmChart, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(helmchartsResource, "status", c.ns, helmChart), &v1beta1.HelmChart{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.HelmChart), err
}

// Delete takes name of the helmChart and deletes it. Returns an error if one occurs.
func (c *FakeHelmCharts) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(helmchartsResource, c.ns, name), &v1beta1.HelmChart{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHelmCharts) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(helmchartsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.HelmChartList{})
	return err
}

// Patch applies the patch and returns the patched helmChart.
func (c *FakeHelmCharts) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.HelmChart, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(helmchartsResource, c.ns, name, pt, data, subresources...), &v1beta1.HelmChart{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.HelmChart), err
}
