/*
Copyright 2019 Replicated, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/replicatedhq/kots/kotskinds/apis/kots/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeUnsignedLicenses implements UnsignedLicenseInterface
type FakeUnsignedLicenses struct {
	Fake *FakeKotsV1beta1
	ns   string
}

var unsignedlicensesResource = schema.GroupVersionResource{Group: "kots.io", Version: "v1beta1", Resource: "unsignedlicenses"}

var unsignedlicensesKind = schema.GroupVersionKind{Group: "kots.io", Version: "v1beta1", Kind: "UnsignedLicense"}

// Get takes name of the unsignedLicense, and returns the corresponding unsignedLicense object, and an error if there is any.
func (c *FakeUnsignedLicenses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.UnsignedLicense, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(unsignedlicensesResource, c.ns, name), &v1beta1.UnsignedLicense{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.UnsignedLicense), err
}

// List takes label and field selectors, and returns the list of UnsignedLicenses that match those selectors.
func (c *FakeUnsignedLicenses) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.UnsignedLicenseList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(unsignedlicensesResource, unsignedlicensesKind, c.ns, opts), &v1beta1.UnsignedLicenseList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.UnsignedLicenseList{ListMeta: obj.(*v1beta1.UnsignedLicenseList).ListMeta}
	for _, item := range obj.(*v1beta1.UnsignedLicenseList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested unsignedLicenses.
func (c *FakeUnsignedLicenses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(unsignedlicensesResource, c.ns, opts))

}

// Create takes the representation of a unsignedLicense and creates it.  Returns the server's representation of the unsignedLicense, and an error, if there is any.
func (c *FakeUnsignedLicenses) Create(ctx context.Context, unsignedLicense *v1beta1.UnsignedLicense, opts v1.CreateOptions) (result *v1beta1.UnsignedLicense, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(unsignedlicensesResource, c.ns, unsignedLicense), &v1beta1.UnsignedLicense{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.UnsignedLicense), err
}

// Update takes the representation of a unsignedLicense and updates it. Returns the server's representation of the unsignedLicense, and an error, if there is any.
func (c *FakeUnsignedLicenses) Update(ctx context.Context, unsignedLicense *v1beta1.UnsignedLicense, opts v1.UpdateOptions) (result *v1beta1.UnsignedLicense, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(unsignedlicensesResource, c.ns, unsignedLicense), &v1beta1.UnsignedLicense{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.UnsignedLicense), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeUnsignedLicenses) UpdateStatus(ctx context.Context, unsignedLicense *v1beta1.UnsignedLicense, opts v1.UpdateOptions) (*v1beta1.UnsignedLicense, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(unsignedlicensesResource, "status", c.ns, unsignedLicense), &v1beta1.UnsignedLicense{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.UnsignedLicense), err
}

// Delete takes name of the unsignedLicense and deletes it. Returns an error if one occurs.
func (c *FakeUnsignedLicenses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(unsignedlicensesResource, c.ns, name), &v1beta1.UnsignedLicense{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeUnsignedLicenses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(unsignedlicensesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.UnsignedLicenseList{})
	return err
}

// Patch applies the patch and returns the patched unsignedLicense.
func (c *FakeUnsignedLicenses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.UnsignedLicense, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(unsignedlicensesResource, c.ns, name, pt, data, subresources...), &v1beta1.UnsignedLicense{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.UnsignedLicense), err
}
