apiVersion: kots.io/v1beta1
kind: License
metadata:
  name: typeexistingclusterenvonlinephasenewinstallrbacclusteradmin
spec:
  appSlug: qakotsregression
  channelID: 1qukhpFn0R394Ix8OWzTO1rgOb0
  channelName: type=existing cluster, env=online, phase=new install, rbac=cluster
    admin
  customerName: type=existing cluster, env=online, phase=new install, rbac=cluster
    admin
  endpoint: https://replicated.app
  entitlements:
    bool_field_1:
      title: Boolean Field 1
      value: true
      valueType: Boolean
    expires_at:
      description: License Expiration
      title: Expiration
      value: ""
      valueType: String
    hidden_field_1:
      isHidden: true
      title: Hidden Field 1
      value: hide me
      valueType: String
    int_field_1:
      title: Integer Field 1
      value: 626
      valueType: Integer
    required_field_1:
      title: Required Field 1
      value: require me
      valueType: String
    str_field_1:
      title: String Field 1
      value: abc
      valueType: String
    txt_field_1:
      title: Text Field 1
      value: |-
        abc
        xyz
      valueType: Text
  isAirgapSupported: true
  isGitOpsSupported: true
  isSnapshotSupported: true
  licenseID: 1quknOFLcPIP6vJdr3Don0FjKXc
  licenseSequence: 4
  licenseType: prod
  signature: eyJsaWNlbnNlRGF0YSI6ImV5SmhjR2xXWlhKemFXOXVJam9pYTI5MGN5NXBieTkyTVdKbGRHRXhJaXdpYTJsdVpDSTZJa3hwWTJWdWMyVWlMQ0p0WlhSaFpHRjBZU0k2ZXlKdVlXMWxJam9pZEhsd1pXVjRhWE4wYVc1blkyeDFjM1JsY21WdWRtOXViR2x1WlhCb1lYTmxibVYzYVc1emRHRnNiSEppWVdOamJIVnpkR1Z5WVdSdGFXNGlmU3dpYzNCbFl5STZleUpzYVdObGJuTmxTVVFpT2lJeGNYVnJiazlHVEdOUVNWQTJka3BrY2pORWIyNHdSbXBMV0dNaUxDSnNhV05sYm5ObFZIbHdaU0k2SW5CeWIyUWlMQ0pqZFhOMGIyMWxjazVoYldVaU9pSjBlWEJsUFdWNGFYTjBhVzVuSUdOc2RYTjBaWElzSUdWdWRqMXZibXhwYm1Vc0lIQm9ZWE5sUFc1bGR5QnBibk4wWVd4c0xDQnlZbUZqUFdOc2RYTjBaWElnWVdSdGFXNGlMQ0poY0hCVGJIVm5Jam9pY1dGcmIzUnpjbVZuY21WemMybHZiaUlzSW1Ob1lXNXVaV3hKUkNJNklqRnhkV3RvY0VadU1GSXpPVFJKZURoUFYzcFVUekZ5WjA5aU1DSXNJbU5vWVc1dVpXeE9ZVzFsSWpvaWRIbHdaVDFsZUdsemRHbHVaeUJqYkhWemRHVnlMQ0JsYm5ZOWIyNXNhVzVsTENCd2FHRnpaVDF1WlhjZ2FXNXpkR0ZzYkN3Z2NtSmhZejFqYkhWemRHVnlJR0ZrYldsdUlpd2liR2xqWlc1elpWTmxjWFZsYm1ObElqbzBMQ0psYm1Sd2IybHVkQ0k2SW1oMGRIQnpPaTh2Y21Wd2JHbGpZWFJsWkM1aGNIQWlMQ0psYm5ScGRHeGxiV1Z1ZEhNaU9uc2lZbTl2YkY5bWFXVnNaRjh4SWpwN0luUnBkR3hsSWpvaVFtOXZiR1ZoYmlCR2FXVnNaQ0F4SWl3aWRtRnNkV1VpT25SeWRXVXNJblpoYkhWbFZIbHdaU0k2SWtKdmIyeGxZVzRpZlN3aVpYaHdhWEpsYzE5aGRDSTZleUowYVhSc1pTSTZJa1Y0Y0dseVlYUnBiMjRpTENKa1pYTmpjbWx3ZEdsdmJpSTZJa3hwWTJWdWMyVWdSWGh3YVhKaGRHbHZiaUlzSW5aaGJIVmxJam9pSWl3aWRtRnNkV1ZVZVhCbElqb2lVM1J5YVc1bkluMHNJbWhwWkdSbGJsOW1hV1ZzWkY4eElqcDdJblJwZEd4bElqb2lTR2xrWkdWdUlFWnBaV3hrSURFaUxDSjJZV3gxWlNJNkltaHBaR1VnYldVaUxDSjJZV3gxWlZSNWNHVWlPaUpUZEhKcGJtY2lMQ0pwYzBocFpHUmxiaUk2ZEhKMVpYMHNJbWx1ZEY5bWFXVnNaRjh4SWpwN0luUnBkR3hsSWpvaVNXNTBaV2RsY2lCR2FXVnNaQ0F4SWl3aWRtRnNkV1VpT2pZeU5pd2lkbUZzZFdWVWVYQmxJam9pU1c1MFpXZGxjaUo5TENKeVpYRjFhWEpsWkY5bWFXVnNaRjh4SWpwN0luUnBkR3hsSWpvaVVtVnhkV2x5WldRZ1JtbGxiR1FnTVNJc0luWmhiSFZsSWpvaWNtVnhkV2x5WlNCdFpTSXNJblpoYkhWbFZIbHdaU0k2SWxOMGNtbHVaeUo5TENKemRISmZabWxsYkdSZk1TSTZleUowYVhSc1pTSTZJbE4wY21sdVp5QkdhV1ZzWkNBeElpd2lkbUZzZFdVaU9pSmhZbU1pTENKMllXeDFaVlI1Y0dVaU9pSlRkSEpwYm1jaWZTd2lkSGgwWDJacFpXeGtYekVpT25zaWRHbDBiR1VpT2lKVVpYaDBJRVpwWld4a0lERWlMQ0oyWVd4MVpTSTZJbUZpWTF4dWVIbDZJaXdpZG1Gc2RXVlVlWEJsSWpvaVZHVjRkQ0o5ZlN3aWFYTkJhWEpuWVhCVGRYQndiM0owWldRaU9uUnlkV1VzSW1selIybDBUM0J6VTNWd2NHOXlkR1ZrSWpwMGNuVmxMQ0pwYzFOdVlYQnphRzkwVTNWd2NHOXlkR1ZrSWpwMGNuVmxmWDA9IiwiaW5uZXJTaWduYXR1cmUiOiJleUpzYVdObGJuTmxVMmxuYm1GMGRYSmxJam9pY2tOWVdWbGtiRkpUUkRaSGNXVlFTeXQzYkZKR1RIZHZaMnhKUm5Nd1J6VlhXSGRhZFRWS1FrazFUbFY2Y1d0cGNXbFBLelpwVWtGS1NUUmtPRmh3VFVKMlJuRkRWbW96TkU5cVluSmtUQzkzUW5kVlVVZEVZamhWVTJGSFpYaHZZWE12UzBsTUt6QnVlSGRQTmxZd1JHNTFZVXhoTVZWQlIwWm1hbmhqVGxGT1MwMUhOblpWVTJaT1p6VkNVVWQ2YWxodlRIUlJRbFJCWlhSS2JHVmFVV1ZCUVRGcFIyRnZXRzg0TjBWaGMzaGhaVWc0UkVOQ1dFRXhUMUpVY1ZGRFFYSTVUa0ptY0VReVZVaHNka2RRTkRWd2FtRllUWHBNVVdaT00zVjRlbnBzVms5S2JrUnpWMDVHWlRjd1oyOTJVMVF3VjNaNFQxbHphVVJQSzNOYVlrZFdibTkxUVVwTk9VZDBVbkZWUW5Kc01rWjZlWFp4V21OeE5sRm5MMkpRTHpBMU9UZDZTV28xYTJkVlpXRjJWMlkxVkc5dFNGVldVMDh4VjB0Rk5FcGpjR3BIVVVzdmMyaENUVUp2VjBKbVJEbEVZWGxuUFQwaUxDSndkV0pzYVdOTFpYa2lPaUl0TFMwdExVSkZSMGxPSUZCVlFreEpReUJMUlZrdExTMHRMVnh1VFVsSlFrbHFRVTVDWjJ0eGFHdHBSemwzTUVKQlVVVkdRVUZQUTBGUk9FRk5TVWxDUTJkTFEwRlJSVUYxYkZWS2J5dEtkV2xFUm05bWRGQnpNWE4xYWx4dWFGZGtOMWxCUlhoeWNraHZaemRVYjJwRE1HVnhNWEJCYkZOWFJsRnhZbWxsZVdOdVVVRTRObXhXVURoSGNXa3hhMk55Tm1rMlRrRjBhM1JPVEZGalpseHVXV2xYUkhGTE1ESjJkbFUzYVhSbFZWcExaRk5rSzB0WVpsaFlUbXd4TWtscVRtczFiR1F2UkZWc01IaFNWWE5oTDBObVUzVlRTMmhpZDFNM01IcHJVMXh1TkUxQmEweHVabFJaUzNKdGMybGhNSGM0VFU1VFpXcEdVVzV3UjA1RmExWmxjMWxrWTI1aWVXWm5kbGxzU0hwcEszRXliRXRRU21jek5qa3lOMnBPU0Z4dVJXcDZSV3hOV21GcVIycEVORmMyYmxoUk0xWnVWbFl4V1Vkck1WcGpaRXBFYldZelMzRXlNRTVYZURKR2R6ZFZaVzE2WVcwMFVDOUdXRzV5YzBoRlRGeHVTWEZSTlhGa1JEQkRhbkZsUldJck1YVldOMDlwU1V4S2FFRkVkV0Z0VlZGNGFUaFdVM05PYzFodGVqbHNRVFZRUW1OV2NqUmFjSEJNVDFaak4yTkRkbHh1TkZGSlJFRlJRVUpjYmkwdExTMHRSVTVFSUZCVlFreEpReUJMUlZrdExTMHRMVnh1SWl3aWEyVjVVMmxuYm1GMGRYSmxJam9pWlhsS2VtRlhaSFZaV0ZJeFkyMVZhVTlwU2xaUlZWSlJUbXhrV0UxdVRuQlJNVTV3VDFSYWJrMXVUVEZUV0ZwYVdqSTFRbU5GZUhaT1JHaFhUREZTWVdWRmJIbFhWRXBwVVROc1NrNUhNVFpTVnpreFZFaFJNVk5FVGs5TU1XUkpaRVpSY21ReWFIaFJNMlJLVFcwMGVGTkhhRTFaYXpVeVYwaEdWR05zU2paV2JsRXpUakJHUkdGc1ZsbGhSM1JHU3pKa1ZWcFZUVEZXYlRGdVUwUmFTVlJ1YjNwWldHeExaRWhDU0dKRWFFOVRSWFJPVW14Vk5GZFlhREJYYW1SMFZqSkdjVkl4VGtOWGJVMTRVVEJKY2s1RVFrSk5SbEp4WlZkT1JsWkRPVmRqTUdReFdrWlNhMXBxUlRGVGJtUlBUbGhXYWsweWR6Rk9iVlp0Vld4S1EwNUZWalZVUjBwT1YwUm5kbUpZVGtWaE1GWXpVa1pzVTFaV1pFTlhiVGxHV1RKR2VWZFZTbmhOTW5SMFZIcENVV1JIVGxsTmEyaEhWMWhhV0dKWGRFaGlla1p5VlZkSk5WVlZWbnBoUms1c1ZWaGtVMUl6V2pCa1IxWk5ZVWRvZDJOSFpHRk5lazAwVERCc1FsRldSa3BrUkdNMFlsZE9NVlJHUVhoUFdFb3lVVEphWVZReFVsRlpWMFowVkRGa01FMVdRbTVPVkZaUFdUQlNhRnBxUm10UlZ6RmhWbFZhZFZkR1VuVlhhbWg2WVcxU1VWRnBPVWhVUmtwNFUwaHZlbUl4V2paak0xRTFXbXRzV2xWRlNUTmtNakZVVDBkTk5WWXdSVGxRVTBselNXMWtjMkl5U21oaVJYUnNaVlZzYTBscWIybFpiVkpzV2xSVk1rNVVXWGRaTWxwcFRrUk9hazlYU1hsUFIwcHRUMVJvYkZsWFRtaGFiVVV5VGtSWmFXWlJQVDBpZlE9PSJ9
