apiVersion: v1
data:
  accesskey: bm90LWEta2V5
  secretkey: bm90LWEtc2VjcmV0
kind: Secret
metadata:
  labels:
    kots.io/kotsadm: 'true'
    kots.io/backup: velero
    app: kotsadm-minio
  name: kotsadm-minio
type: Opaque
