apiVersion: v1
kind: Service
metadata:
  labels:
    kots.io/kotsadm: 'true'
    kots.io/backup: velero
    app: kotsadm-minio
  name: kotsadm-minio
spec:
  ports:
  - name: service
    port: 4569
    protocol: TCP
    targetPort: 9000
  selector:
    app: kotsadm-minio
  type: ClusterIP
