apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
    release: minio
  name: kotsadm-s3
spec:
  ports:
  - name: service
    port: 4569
    protocol: TCP
    targetPort: 9000
  selector:
    app: minio
    release: minio
  type: ClusterIP
