apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kotsadm-minio
  labels:
    kots.io/kotsadm: 'true'
    kots.io/backup: velero
spec:
  serviceName: kotsadm-minio
  selector:
    matchLabels:
      app: kotsadm-minio
  template:
    metadata:
      labels:
        kots.io/kotsadm: 'true'
        kots.io/backup: velero
        app: kotsadm-minio
      name: kotsadm-minio
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - args:
          - server
          - /data
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: accesskey
              name: kotsadm-minio
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secretkey
              name: kotsadm-minio
        - name: MINIO_BROWSER
          value: "on"
        image: kotsadm/minio:0.20231101.183725
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /minio/health/live
            port: service
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: kotsadm-minio
        ports:
          - containerPort: 9000
            name: service
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /minio/health/ready
            port: service
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
          - mountPath: /data
            name: miniodata  # this is where the data is stored

  volumeClaimTemplates:
  - metadata:
      name: miniodata
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: 2Gi
