---
apiVersion: v1
kind: Service
metadata:
  name: kotsadm-rqlite
  labels:
    app: kotsadm-rqlite
spec:
  type: ClusterIP
  ports:
  - name: rqlite
    port: 4001
    targetPort: rqlite
  selector:
    app: kotsadm-rqlite
---
apiVersion: v1
kind: Service
metadata:
  name: kotsadm-rqlite-headless
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: True
  selector:
    app: kotsadm-rqlite
  ports:
    - protocol: TCP
      port: 4001
      targetPort: rqlite
---
apiVersion: v1
kind: Secret
metadata:
  name: kotsadm-rqlite
  labels:
    app: kotsadm-rqlite
type: Opaque
data:
  password: "cGFzc3dvcmQ="
  uri: aHR0cDovL2tvdHNhZG06cGFzc3dvcmRAa290c2FkbS1ycWxpdGU6NDAwMT90aW1lb3V0PTYwJmRpc2FibGVDbHVzdGVyRGlzY292ZXJ5PXRydWU=
  authconfig.json: WwogIHsKICAgICJ1c2VybmFtZSI6ICJrb3RzYWRtIiwKICAgICJwYXNzd29yZCI6ICJwYXNzd29yZCIsCiAgICAicGVybXMiOiBbImFsbCJdCiAgfSwKICB7CiAgICAidXNlcm5hbWUiOiAiKiIsCiAgICAicGVybXMiOiBbInN0YXR1cyIsICJyZWFkeSJdCiAgfQpdCg==
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kotsadm-rqlite
spec:
  replicas: 1
  serviceName: kotsadm-rqlite-headless
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      app: kotsadm-rqlite
  template:
    metadata:
      labels:
        app: kotsadm-rqlite
    spec:
      containers:
      - name: rqlite
        image: kotsadm/rqlite:8.28.1-r0
        imagePullPolicy: IfNotPresent
        args:
        - -disco-mode=dns
        - -disco-config={"name":"kotsadm-rqlite-headless"}
        - -bootstrap-expect=1
        - -auth=/auth/config.json
        - -join-as=kotsadm
        ports:
        - name: rqlite
          containerPort: 4001
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /readyz?noleader
            port: rqlite
          initialDelaySeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /readyz
            port: rqlite
          initialDelaySeconds: 1
          timeoutSeconds: 1
          periodSeconds: 1
        resources:
          limits:
            cpu: 200m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: kotsadm-rqlite
          mountPath: /rqlite/file
        - name: authconfig
          mountPath: /auth/config.json
          subPath: authconfig.json
        env:
        - name: RQLITE_PASSWORD # this is used by the support bundle collector to get the db backup from rqlite
          valueFrom:
            secretKeyRef:
              name: kotsadm-rqlite
              key: password
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      volumes:
      - name: authconfig
        secret:
          secretName: kotsadm-rqlite
          items:
          - key: authconfig.json
            path: authconfig.json
  volumeClaimTemplates:
  - metadata:
      name: kotsadm-rqlite
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: 1Gi
