export const NAMESPACE = "default";
export const INITIAL_SMALL_BUNDLE_CHANNEL_SEQUENCE = 23;
export const UPDATE_SMALL_BUNDLE_CHANNEL_SEQUENCE = 24;
export const VENDOR_INITIAL_CHANNEL_SEQUENCE = 21;
export const VENDOR_UPDATE_CHANNEL_SEQUENCE = 22;
export const LICENSE_ID = "1qoczp6VdOEizTXwu4edsxDsVyM";
export const CUSTOMER_ID = "1qoczu4KngeUMINcst9I8NtgXur";
export const CUSTOMER_NAME = "type=embedded cluster, env=airgapped, phase=new install, rbac=cluster admin";
export const CHANNEL_NAME = "type=embedded cluster, env=airgapped, phase=new install, rbac=cluster admin";
export const CHANNEL_ID = "1qocvipE0GJBTncRszwWpfARdVb";
export const CHANNEL_SLUG = "type-embedded-cluster-env-airg";
export const VELERO_VERSION = "v1.12.1";
export const VELERO_AWS_PLUGIN_VERSION = "v1.8.1";
export const IS_EC = false;
export const IS_EXISTING_CLUSTER = false;
export const IS_AIRGAPPED = true;
export const IS_AIRGAP_SUPPORTED = true;
export const IS_MINIMAL_RBAC = false;
export const DOWNLOAD_PORTAL_BASE64_PASSWORD = "OUxSUFhI";
