export const NAMESPACE = "qakotsregression";
export const INITIAL_SMALL_BUNDLE_CHANNEL_SEQUENCE = 13;
export const UPDATE_SMALL_BUNDLE_CHANNEL_SEQUENCE = 14;
export const VENDOR_INITIAL_CHANNEL_SEQUENCE = 8;
export const VENDOR_UPDATE_CHANNEL_SEQUENCE = 9;
export const LICENSE_ID = "1vsAXX5gvXKfBHqh9iigKZ0GisA";
export const CUSTOMER_ID = "1vsAXZYrhkYhr0AMbYL8gmPAAJu";
export const CUSTOMER_NAME = "type=existing cluster, env=airgapped, phase=new install, rbac=minimal rbac";
export const CHANNEL_NAME = "type=existing cluster, env=airgapped, phase=new install, rbac=minimal rbac";
export const CHANNEL_ID = "1vs9nvnrMZ13Z6aYoB34XLBLr2m";
export const CHANNEL_SLUG = "type-existing-cluster-env-airgapped-phase-new-install-rbac-minimal-rbac";
export const VELERO_VERSION = "v1.12.1";
export const VELERO_AWS_PLUGIN_VERSION = "v1.8.1";
export const IS_EC = false;
export const IS_EXISTING_CLUSTER = true;
export const IS_AIRGAPPED = true;
export const IS_AIRGAP_SUPPORTED = true;
export const IS_MINIMAL_RBAC = true;
export const DOWNLOAD_PORTAL_BASE64_PASSWORD = "SkpWSzlG";
export const SHOULD_RESET_PASSWORD = false;
export const IS_VELERO_INSTALLED = false;
