apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotsadm
  labels:
    kots.io/kotsadm: 'true'
    kots.io/backup: velero
spec:
  template:
    metadata:
      labels:
        kots.io/kotsadm: 'true'
        kots.io/backup: velero
      annotations:
        backup.velero.io/backup-volumes: backup
        pre.hook.backup.velero.io/command: '["/bin/bash", "-c", "PGPASSWORD=password pg_dump -U kotsadm -h kotsadm-postgres > /backup/kotsadm-postgres.sql"]'
        pre.hook.backup.velero.io/timeout: 3m
    spec:
      serviceAccountName: default
      containers:
        - name: kotsadm
          volumeMounts:
            - mountPath: /backup
              name: backup
            - name: kubelet-client-cert
              mountPath: /etc/kubernetes/pki/kubelet
          ports:
            - containerPort: 40000
              name: dlv
              protocol: TCP
          env:
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: kotsadm-postgres # This secret is created in the migrations directory
                  key: uri
            - name: S3_BUCKET_NAME
              value: "shipbucket"
            - name: S3_ENDPOINT
              value: http://kotsadm-s3:4569/
            - name: S3_ACCESS_KEY_ID
              value: not-a-key
            - name: S3_SECRET_ACCESS_KEY
              value: not-a-secret
            - name: S3_BUCKET_ENDPOINT
              value: "true"
            - name: DEX_PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: PGPASSWORD
                  name: kotsadm-dex-postgres
            - name: KOTSADM_LOG_LEVEL
              value: "debug"
            - name: DISABLE_SPA_SERVING
              value: "1"
              valueFrom: ~
            - name: AUTO_CREATE_CLUSTER
              value: "1"
            - name: AUTO_CREATE_CLUSTER_NAME
              value: "microk8s"
            - name: AUTO_CREATE_CLUSTER_TOKEN
              value: this-is-definitely-not-a-secret
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SHARED_PASSWORD_BCRYPT
              value: $2a$10$xZRsZCYgRDG90N1QEjBxGOBDrDGE.rpcMENV4qNNo7pozYTEPGMwS
            - name: SESSION_KEY
              value: this-is-not-too-secret
            - name: API_ENCRYPTION_KEY
              value: IvWItkB8+ezMisPjSMBknT1PdKjBx7Xc/txZqOP8Y2Oe7+Jy
            - name: REPLICATED_API_ENDPOINT
              value: http://replicated-app:3000
            - name: API_ENDPOINT
              value: http://kotsadm:3000
            - name: API_ADVERTISE_ENDPOINT
              value: http://127.0.0.1:30000
            - name: KOTSADM_ENV
              value: "dev"
            - name: ENABLE_WEB_PROXY
              value: "1"
            # - name: DISABLE_OUTBOUND_CONNECTIONS
            #   value: "true"
            - name: KURL_PROXY_TLS_CERT_PATH
              value: /etc/kurl-proxy/ca/tls.crt
            - name: KOTS_INSTALL_ID
              value: dev-1pu4oeY162e2pbLpK4JubK6hxrX
            - name: AIRGAP_UPLOAD_PARALLELISM
              value: "3"
            - name: POD_OWNER_KIND
              value: "deployment"
            - name: DEBUG
              value: "false"
      volumes:
        - emptyDir:
            medium: Memory
            sizeLimit: 1Gi
          name: backup
        - name: kubelet-client-cert
          secret:
            secretName: kubelet-client-cert
            optional: true
        - name: init-dex-db
          configMap:
            name: init-dex-db
      hostAliases:
        - ip: 172.17.0.1
          hostnames:
            - kotsadm.kotsadmdevenv.com
            - dex.kotsadmdevenv.com
