apiVersion: v1
kind: Secret
metadata:
  name: kotsadm-dex-postgres
  labels:
    kots.io/kotsadm: 'true'
    kots.io/backup: velero
    kots.io/identity: 'true'
stringData:
  PGHOST: kotsadm-postgres
  PGDATABASE: dex
  PGUSER: dex
  PGPASSWORD: password
