FROM centos/postgresql-10-centos7
# this dockerfile is used for CI *only*, the actual image used is defined here: https://github.com/replicatedhq/kots/blob/master/pkg/kotsadm/objects/postgres_objects.go#L17
