apiVersion: apps/v1
kind: Deployment
metadata:
  name: grid
spec:
  selector:
    matchLabels:
      app: grid
  template:
    metadata:
      labels:
        app: grid
    spec:
      containers:
        - name: grid
          image: selenium/standalone-chrome
          imagePullPolicy: IfNotPresent
          ports:
            - name: webdriver
              containerPort: 4444
            - name: web-interface
              containerPort: 7900
#          readinessProbe:
#            failureThreshold: 3
#            httpGet:
#              path: /healthz
#              port: grid
#              scheme: HTTP
#            initialDelaySeconds: 2
#            periodSeconds: 2
#            successThreshold: 1
#            timeoutSeconds: 1
#          livenessProbe:
#            failureThreshold: 2
#            httpGet:
#              path: /livez
#              port: grid
#              scheme: HTTP
#            initialDelaySeconds: 30
#            periodSeconds: 15
#            timeoutSeconds: 1
---

apiVersion: v1
kind: Service
metadata:
  name: grid
  labels:
    app: grid
spec:
  type: ClusterIP
  ports:
    - port: 4444
      name: webdriver
      targetPort: webdriver
    - port: 7900
      name: web-interface
      targetPort: web-interface
  selector:
    app: grid
