FROM golang:1.24.2-alpine AS dlv-builder

RUN go install github.com/go-delve/delve/cmd/dlv@v1.24.0

FROM golang:1.24.2-alpine

RUN apk add --no-cache ca-certificates s3cmd curl git make bash

# Install Kubectl 1.29
ENV KUBECTL_VERSION=v1.31.0
ENV KUBECTL_URL=https://dl.k8s.io/release/v1.31.0/bin/linux/arm64/kubectl
ENV KUBECTL_SHA256SUM=f42832db7d77897514639c6df38214a6d8ae1262ee34943364ec1ffaee6c009c
RUN curl -fsSLO "${KUBECTL_URL}" \
  && echo "${KUBECTL_SHA256SUM} kubectl" | sha256sum -c - \
  && chmod +x kubectl \
  && mv kubectl /usr/local/bin//kubectl

# Install kustomize 5
ENV KUSTOMIZE5_VERSION=5.5.0
ENV KUSTOMIZE5_URL=https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v${KUSTOMIZE5_VERSION}/kustomize_v${KUSTOMIZE5_VERSION}_linux_arm64.tar.gz
ENV KUSTOMIZE5_SHA256SUM=b4170d1acb8cfacace9f72884bef957ff56efdcd4813b66e7604aabc8b57e93d
RUN curl -fsSL -o kustomize.tar.gz "${KUSTOMIZE5_URL}" \
  && echo "${KUSTOMIZE5_SHA256SUM} kustomize.tar.gz" | sha256sum -c - \
  && tar -xzvf kustomize.tar.gz \
  && rm kustomize.tar.gz \
  && chmod a+x kustomize \
  && mv kustomize /usr/local/bin/kustomize

# Install helm v3
ENV HELM3_VERSION=3.17.0
ENV HELM3_URL=https://get.helm.sh/helm-v${HELM3_VERSION}-linux-arm64.tar.gz
ENV HELM3_SHA256SUM=c4d4be8e80082b7eaa411e3e231d62cf05d01cddfef59b0d01006a7901e11ee4
RUN cd /tmp && curl -fsSL -o helm.tar.gz "${HELM3_URL}" \
  && echo "${HELM3_SHA256SUM} helm.tar.gz" | sha256sum -c - \
  && tar -xzvf helm.tar.gz \
  && chmod a+x linux-arm64/helm \
  && mv linux-arm64/helm /usr/local/bin/helm \
  && rm -rf helm.tar.gz linux-arm64

WORKDIR /replicatedhq/kots

COPY --from=dlv-builder /go/bin/dlv /dlv
COPY ./deploy/assets /scripts
COPY ./bin/kotsadm /kotsadm
COPY ./bin/kots /kots

ARG DEBUG_KOTSADM=0
ENV DEBUG_KOTSADM=${DEBUG_KOTSADM}

COPY ./dev/dockerfiles/kotsadm/entrypoint.sh ./
ENTRYPOINT [ "./entrypoint.sh"]
