import { SSH_USER } from "../shared/constants";

export const NAMESPACE = "qakotsregression";
export const SMALL_BUNDLE_CHANNEL_RELEASE_SEQUENCE = 17;
export const VENDOR_INITIAL_CHANNEL_RELEASE_SEQUENCE = 13;
export const VENDOR_UPDATE_CHANNEL_RELEASE_SEQUENCE = 14;
export const LICENSE_ID = "1riYWkuo5PdMtD4imgTYX699IdU";
export const CUSTOMER_ID = "1riYWlpWEbuVSARQtZmZWZOv2TN";
export const CUSTOMER_NAME = "type=existing cluster, env=airgapped, phase=new install, rbac=cluster admin";
export const CHANNEL_NAME = "type=existing cluster, env=airgapped, phase=new install, rbac=cluster admin";
export const CHANNEL_ID = "1riP4oQC5ZOaqciRwLf14I6yn2l";
export const CHANNEL_SLUG = "type-existing-cluster-env-airg";
export const VELERO_VERSION = "v1.12.1";
export const VELERO_AWS_PLUGIN_VERSION = "v1.8.1";
export const IS_EC = false;
export const IS_EXISTING_CLUSTER = true;
export const IS_AIRGAPPED = true;
export const IS_AIRGAP_SUPPORTED = true;
export const IS_MINIMAL_RBAC = false;
export const DOWNLOAD_PORTAL_BASE64_PASSWORD = "SFJZQVlF";
export const SHOULD_RESET_PASSWORD = false;
export const IS_VELERO_INSTALLED = false;
export const SSH_TO_AIRGAPPED_INSTANCE = `ssh ${SSH_USER}@${process.env.AIRGAPPED_INSTANCE_IP}`;
export const SCP_TO_AIRGAPPED_INSTANCE = `scp %s ${SSH_USER}@${process.env.AIRGAPPED_INSTANCE_IP}:%s`;
