apiVersion: v1
kind: ServiceAccount
metadata:
  name: kurl-join
  labels:
    kots.io/kotsadm: "true"
    kots.io/backup: velero
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kurl-join-kube-system
  labels:
    kots.io/kotsadm: "true"
    kots.io/backup: velero
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - update
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - roles
  - rolebindings
  verbs:
  - create
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kurl-join
  namespace: kube-system
  labels:
    kots.io/kotsadm: "true"
    kots.io/backup: velero
subjects:
- kind: ServiceAccount
  name: kurl-join
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kurl-join-kube-system
