apiVersion: v1
kind: Secret
metadata:
  name: kotsadm-postgres
  labels:
    kots.io/kotsadm: 'true'
    kots.io/backup: velero
stringData:
  uri: postgresql://kotsadm:${POSTGRES_PASSWORD}@kotsadm-postgres/kotsadm?connect_timeout=10&sslmode=disable
  password: ${POSTGRES_PASSWORD}
