apiVersion: v1
kind: Secret
metadata:
  name: kotsadm-dex-postgres
  labels:
    kots.io/kotsadm: 'true'
    kots.io/backup: velero
    kots.io/identity: 'true'
stringData:
  PGPASSWORD: ${DEX_PGPASSWORD}
