apiVersion: v1
kind: Secret
metadata:
  name: kotsadm-s3
stringData:
  endpoint: ${OBJECT_STORE_CLUSTER_HOST}
  access-key-id: ${OBJECT_STORE_ACCESS_KEY}
  secret-access-key: ${OBJECT_STORE_SECRET_KEY}
  velero-local-bucket: ${VELERO_LOCAL_BUCKET}
  object-store-cluster-ip: ${OBJECT_STORE_CLUSTER_IP}
