name: action-gke
description: Start a GKE cluster
inputs:
  cluster-name:
    description: GKE cluster name to create
    required: true

  cluster-region:
    description: GKE cluster region to use
    default: "us-west1"
    required: false

  cluster-network:
    description: GKE cluster network tag
    default: "projects/replicated-qa/global/networks/default"
    required: false

  cluster-subnetwork:
    description: GKE cluster subnetwork tag
    default: "projects/replicated-qa/regions/us-west1/subnetworks/default"
    required: false

  delete:
    description: Delete the existing cluster
    default: false
    required: false

  project:
    description: Google Cloud project name
    default: "replicated-qa"
    required: false

  service-key:
    description: Google Could service account key for authentication
    required: true

runs:
  using: composite

  steps:
  - id: 'auth'
    name: 'Authenticate to Google Cloud'
    uses: 'google-github-actions/auth@v1'
    with:
      credentials_json: ${{ inputs.service-key }}

  - name: 'Setup Cloud SDK'
    uses: google-github-actions/setup-gcloud@v1

  - name: 'Find or create the GKE cluster'
    shell: bash
    run: 'gcloud container clusters describe ${{ inputs.cluster-name }} --region "${{ inputs.cluster-region }}" || gcloud container --project "${{ inputs.project }}" clusters create-auto "${{ inputs.cluster-name }}" --region "${{ inputs.cluster-region }}" --network "${{ inputs.cluster-network }}"  --subnetwork "${{ inputs.cluster-subnetwork }}"'

  - name: 'Get GKE cluster credentials for kubectl'
    uses: google-github-actions/get-gke-credentials@v1
    with:
      cluster_name: ${{ inputs.cluster-name }}
      location: ${{ inputs.cluster-region }}

  - name: 'Delete the existing cluster'
    if: inputs.delete == 'true'
    shell: bash
    run: 'gcloud -q container clusters delete ${{ inputs.cluster-name }} --region ${{ inputs.cluster-region }}'
