module.exports = {
  "password": require('./locator.VPzXbdX6IyoIOev3.json'),
  "Log_in": require('./locator.cHYAhqAAHBK0LuPp.json'),
  "Application": require('./locator.qxLGPq1QaAfWqKyI.json'),
  "Dashboard": require('./locator.V1iuuZFH9LJethS0.json'),
  "QAKots": require('./locator.q5ljuYab5jpYiH5I.json'),
  "Ready": require('./locator.Za1Aw46s8ByQck3S.json'),
  "Example_Application": require('./locator.2F8b5zQR5SxNNsKU.json'),
  "1.0.0_Sequence_0_Currently_deployed": require('./locator.zAH0cZhP87uCyxAW.json'),
  "Version_Check_for_update_Configure_": require('./locator.fL44wCR6MHatVDZn.json'),
  "License_Sync_license_type=embedded_": require('./locator.P3CZpzyduaZLhkkw.json'),
  "Snapshots_Snapshot_settings_Start_s": require('./locator.1QgV3XkicPXzmNqJ.json'),
  "Check_for_update": require('./locator.v5hd9XUN2nkGeoH0.json'),
  "Upload_new_version": require('./locator.KGnmA2xtsqjDE3rN.json'),
  "Configure_automatic_updates": require('./locator.sPphhdp17CHbRakt.json'),
  "Snapshot_settings": require('./locator.2jXfbaQdFZX3iVJa.json'),
  "Start_snapshot": require('./locator.aztNUlexJLd6Y6fT.json'),
  "Sync_license": require('./locator.ZEYap7XAV8fx2g0S.json'),
  "See_all_versions": require('./locator.wIMpNh1687FFHwbr.json'),
  "See_all_snapshots": require('./locator.Ndbimv4iepgHTZVw.json'),
  "See_license_details": require('./locator.wL8KD01B4GeKUwhG.json'),
};