export const NAMESPACE = "qakotsregression";
export const VENDOR_INITIAL_CHANNEL_SEQUENCE = 8;
export const VENDOR_UPDATE_CHANNEL_SEQUENCE = 9;
export const LICENSE_ID = "1wEWBmW4i2ALCLHvJL2dqtHjorV";
export const CUSTOMER_ID = "1wEWBiIJBCoenaCc9RUNuvvcpAP";
export const CUSTOMER_NAME = "type=existing cluster, env=airgapped, phase=upgraded install, rbac=minimal rbac";
export const CHANNEL_NAME = "type=existing cluster, env=airgapped, phase=upgraded install, rbac=minimal rbac";
export const CHANNEL_ID = "1wDtc68WxhilHs1HcXZIQEn1brd";
export const CHANNEL_SLUG = "type-existing-cluster-env-airgapped-phase-upgraded-install-rbac-minimal-rbac";
export const VELERO_VERSION = "v1.12.1";
export const VELERO_AWS_PLUGIN_VERSION = "v1.8.1";
export const IS_EC = false;
export const IS_EXISTING_CLUSTER = true;
export const IS_AIRGAPPED = true;
export const IS_AIRGAP_SUPPORTED = true;
export const IS_MINIMAL_RBAC = true;
export const DOWNLOAD_PORTAL_BASE64_PASSWORD = "MjlWVkYy";
export const SHOULD_RESET_PASSWORD = false;
export const IS_VELERO_INSTALLED = false;
