apiVersion: kots.io/v1beta1
kind: License
metadata:
  name: typeexistingclusterenvairgappedphaseupgradedinstallrbacminimalrbac
spec:
  appSlug: qakotsregression
  channelID: 1wDtc68WxhilHs1HcXZIQEn1brd
  channelName: type=existing cluster, env=airgapped, phase=upgraded install, rbac=minimal
    rbac
  customerName: type=existing cluster, env=airgapped, phase=upgraded install, rbac=minimal
    rbac
  endpoint: https://replicated.app
  entitlements:
    bool_field_1:
      title: Boolean Field 1
      value: true
      valueType: Boolean
    expires_at:
      description: License Expiration
      title: Expiration
      value: ""
      valueType: String
    hidden_field_1:
      isHidden: true
      title: Hidden Field 1
      value: hide me
      valueType: String
    int_field_1:
      title: Integer Field 1
      value: 123
      valueType: Integer
    required_field_1:
      title: Required Field 1
      value: require me required
      valueType: String
    str_field_1:
      title: String Field 1
      value: abc
      valueType: String
    txt_field_1:
      title: Text Field 1
      value: |-
        abc
        xyz
      valueType: Text
  isAirgapSupported: true
  isGitOpsSupported: true
  isNewKotsUiEnabled: true
  isSnapshotSupported: true
  licenseID: 1wEWBmW4i2ALCLHvJL2dqtHjorV
  licenseSequence: 11
  licenseType: prod
  signature: eyJsaWNlbnNlRGF0YSI6ImV5SmhjR2xXWlhKemFXOXVJam9pYTI5MGN5NXBieTkyTVdKbGRHRXhJaXdpYTJsdVpDSTZJa3hwWTJWdWMyVWlMQ0p0WlhSaFpHRjBZU0k2ZXlKdVlXMWxJam9pZEhsd1pXVjRhWE4wYVc1blkyeDFjM1JsY21WdWRtRnBjbWRoY0hCbFpIQm9ZWE5sZFhCbmNtRmtaV1JwYm5OMFlXeHNjbUpoWTIxcGJtbHRZV3h5WW1GakluMHNJbk53WldNaU9uc2liR2xqWlc1elpVbEVJam9pTVhkRlYwSnRWelJwTWtGTVEweElka3BNTW1SeGRFaHFiM0pXSWl3aWJHbGpaVzV6WlZSNWNHVWlPaUp3Y205a0lpd2lZM1Z6ZEc5dFpYSk9ZVzFsSWpvaWRIbHdaVDFsZUdsemRHbHVaeUJqYkhWemRHVnlMQ0JsYm5ZOVlXbHlaMkZ3Y0dWa0xDQndhR0Z6WlQxMWNHZHlZV1JsWkNCcGJuTjBZV3hzTENCeVltRmpQVzFwYm1sdFlXd2djbUpoWXlJc0ltRndjRk5zZFdjaU9pSnhZV3R2ZEhOeVpXZHlaWE56YVc5dUlpd2lZMmhoYm01bGJFbEVJam9pTVhkRWRHTTJPRmQ0YUdsc1NITXhTR05ZV2tsUlJXNHhZbkprSWl3aVkyaGhibTVsYkU1aGJXVWlPaUowZVhCbFBXVjRhWE4wYVc1bklHTnNkWE4wWlhJc0lHVnVkajFoYVhKbllYQndaV1FzSUhCb1lYTmxQWFZ3WjNKaFpHVmtJR2x1YzNSaGJHd3NJSEppWVdNOWJXbHVhVzFoYkNCeVltRmpJaXdpYkdsalpXNXpaVk5sY1hWbGJtTmxJam94TVN3aVpXNWtjRzlwYm5RaU9pSm9kSFJ3Y3pvdkwzSmxjR3hwWTJGMFpXUXVZWEJ3SWl3aVpXNTBhWFJzWlcxbGJuUnpJanA3SW1KdmIyeGZabWxsYkdSZk1TSTZleUowYVhSc1pTSTZJa0p2YjJ4bFlXNGdSbWxsYkdRZ01TSXNJblpoYkhWbElqcDBjblZsTENKMllXeDFaVlI1Y0dVaU9pSkNiMjlzWldGdUluMHNJbVY0Y0dseVpYTmZZWFFpT25zaWRHbDBiR1VpT2lKRmVIQnBjbUYwYVc5dUlpd2laR1Z6WTNKcGNIUnBiMjRpT2lKTWFXTmxibk5sSUVWNGNHbHlZWFJwYjI0aUxDSjJZV3gxWlNJNklpSXNJblpoYkhWbFZIbHdaU0k2SWxOMGNtbHVaeUo5TENKb2FXUmtaVzVmWm1sbGJHUmZNU0k2ZXlKMGFYUnNaU0k2SWtocFpHUmxiaUJHYVdWc1pDQXhJaXdpZG1Gc2RXVWlPaUpvYVdSbElHMWxJaXdpZG1Gc2RXVlVlWEJsSWpvaVUzUnlhVzVuSWl3aWFYTklhV1JrWlc0aU9uUnlkV1Y5TENKcGJuUmZabWxsYkdSZk1TSTZleUowYVhSc1pTSTZJa2x1ZEdWblpYSWdSbWxsYkdRZ01TSXNJblpoYkhWbElqb3hNak1zSW5aaGJIVmxWSGx3WlNJNklrbHVkR1ZuWlhJaWZTd2ljbVZ4ZFdseVpXUmZabWxsYkdSZk1TSTZleUowYVhSc1pTSTZJbEpsY1hWcGNtVmtJRVpwWld4a0lERWlMQ0oyWVd4MVpTSTZJbkpsY1hWcGNtVWdiV1VnY21WeGRXbHlaV1FpTENKMllXeDFaVlI1Y0dVaU9pSlRkSEpwYm1jaWZTd2ljM1J5WDJacFpXeGtYekVpT25zaWRHbDBiR1VpT2lKVGRISnBibWNnUm1sbGJHUWdNU0lzSW5aaGJIVmxJam9pWVdKaklpd2lkbUZzZFdWVWVYQmxJam9pVTNSeWFXNW5JbjBzSW5SNGRGOW1hV1ZzWkY4eElqcDdJblJwZEd4bElqb2lWR1Y0ZENCR2FXVnNaQ0F4SWl3aWRtRnNkV1VpT2lKaFltTmNibmg1ZWlJc0luWmhiSFZsVkhsd1pTSTZJbFJsZUhRaWZYMHNJbWx6UVdseVoyRndVM1Z3Y0c5eWRHVmtJanAwY25WbExDSnBjMGRwZEU5d2MxTjFjSEJ2Y25SbFpDSTZkSEoxWlN3aWFYTlRibUZ3YzJodmRGTjFjSEJ2Y25SbFpDSTZkSEoxWlN3aWFYTk9aWGRMYjNSelZXbEZibUZpYkdWa0lqcDBjblZsZlgwPSIsImlubmVyU2lnbmF0dXJlIjoiZXlKc2FXTmxibk5sVTJsbmJtRjBkWEpsSWpvaVpqSlhVR3RzZVdsVFZsWjRjVGRMVTA1dFJFZFlOSHBaU0hORlRWWkVWbUpFTmtGQ1VXeHRibWN4Ykhob1kwOWhjVmh4TVRocFNVb3lhRzg1U1RaUmEzZHNOVEJTTVZSUGRGSktNRTEzYzNoMmEyZEdhMHhhY3pKaU5VTjRaRVUwYzFaSVIxbE1PRUZXVERkMFZXOXBSa1JtYjFGNmNXc3ZlRE5NWTFOSmJtbFRZM05OY2tKWU5taFFVbnBCVWxOMVNpOHhUMlo2ZURKSE5ISnJTbU56VVd4T1lrUlFOR1YzYVcxb1RVbEhVelo2Ym1KTGJITnliMUpuYWtWQ1dtRlVNRWhpWW1FemVGSkNXR0paZEZCdlFVSlVja2xzVVdGMlVISkhNRlZDUzB0VFJWZzFTRGxKY2paYU4yMUlhamx3VG5BclNVaG9ia2hDT1ZsTFVFRklRMDlWUTNKMFJGcFdRVkZ5TDFkWlNrNDFORXQwWVRkRFdUTmpXalZuSzBWdmNXTlZkV1E0UTBwaFZXMW9jMjlMUXpNMGNIcHRWRk5tVUVaeVlrSjJNSGhDTVdvNVlsbEtWelJNZGxneFZYaHZTRTU0V0RGQlBUMGlMQ0p3ZFdKc2FXTkxaWGtpT2lJdExTMHRMVUpGUjBsT0lGQlZRa3hKUXlCTFJWa3RMUzB0TFZ4dVRVbEpRa2xxUVU1Q1oydHhhR3RwUnpsM01FSkJVVVZHUVVGUFEwRlJPRUZOU1VsQ1EyZExRMEZSUlVGMWJGVktieXRLZFdsRVJtOW1kRkJ6TVhOMWFseHVhRmRrTjFsQlJYaHlja2h2WnpkVWIycERNR1Z4TVhCQmJGTlhSbEZ4WW1sbGVXTnVVVUU0Tm14V1VEaEhjV2t4YTJOeU5tazJUa0YwYTNST1RGRmpabHh1V1dsWFJIRkxNREoyZGxVM2FYUmxWVnBMWkZOa0swdFlabGhZVG13eE1rbHFUbXMxYkdRdlJGVnNNSGhTVlhOaEwwTm1VM1ZUUzJoaWQxTTNNSHByVTF4dU5FMUJhMHh1WmxSWlMzSnRjMmxoTUhjNFRVNVRaV3BHVVc1d1IwNUZhMVpsYzFsa1kyNWllV1puZGxsc1NIcHBLM0V5YkV0UVNtY3pOamt5TjJwT1NGeHVSV3A2Uld4TldtRnFSMnBFTkZjMmJsaFJNMVp1VmxZeFdVZHJNVnBqWkVwRWJXWXpTM0V5TUU1WGVESkdkemRWWlcxNllXMDBVQzlHV0c1eWMwaEZURnh1U1hGUk5YRmtSREJEYW5GbFJXSXJNWFZXTjA5cFNVeEthRUZFZFdGdFZWRjRhVGhXVTNOT2MxaHRlamxzUVRWUVFtTldjalJhY0hCTVQxWmpOMk5EZGx4dU5GRkpSRUZSUVVKY2JpMHRMUzB0UlU1RUlGQlZRa3hKUXlCTFJWa3RMUzB0TFZ4dUlpd2lhMlY1VTJsbmJtRjBkWEpsSWpvaVpYbEtlbUZYWkhWWldGSXhZMjFWYVU5cFNsaE9XRVowVFRBNVFsSXpRakJPTTJ4MVZsVTFVazR4VFRSTE1Ga3pUakZ3UmxSWFp6QlRhM1J6WTFkT1NsbFdTa0pNTVVweVZWVnZja3N6UlhabFdGSjNVbTFvVUdGR1FrMWtibVJVVWxWV01FMUlhRVpOZWs1NFVteE9XazlGU1hsTlNIQkRUa1pWTUUxRldubFJNMnhYWVZaQ01WUnRNVmxOVjFGMldUTndOazFxVmpWT01WcEVaVWhHTWxveGJFaE5NMmg1V1ZSR1VscFRkREZXVkVwMVZFaGtNVTVHUm5aTmEwNW9XVzVHYVZKdFdrTlRiV1JaWTNwa1JFOVlhRzVqYld4M1VsUlNOR05HVWxOTlJWcFVZMnN4VldKSGVIaFNNRlUwV20xb1ZGZHFWalZsVmxaVFYxVlJNMlJFU2xabFF6bFJaV3hPYlZOSFNsVmpNRlo2VFdzNWVVMXNWa0pNTW1SdVpXeEZNRlV5VmtKVlNFcHhWRWRLTkUweGFITk5iR3hNVlcwNE5XVkhNVEZXYXpGSFkydEdObEZyZERKVmFsSm9ZVVpTTkZvelpIaGtlbWgxVkZSS1ZGRjVPVFJoVmxadFZHMW9hMDFyTlhoYVdGWndZMWN4TUZKRVduaE5WMlJUVWtSb2QyRllWbFpsVjNoS1dqRkNiMDV1WkhGT2JFWTJZMVpXZDJGVlJsbE5la3BVVDFoQ1JGcHBkR3hsVkdReVVWaHdSVXQ2VmtKaFZHUjNVVEo0TkdWSGRGVlNWRkpZWWxaVmQwMXRVbk5YU0dSeFRUQmpNVmx1WXpsUVUwbHpTVzFrYzJJeVNtaGlSWFJzWlZWc2EwbHFiMmxaYlZKc1dsUlZNazVVV1hkWk1scHBUa1JPYWs5WFNYbFBSMHB0VDFSb2JGbFhUbWhhYlVVeVRrUlphV1pSUFQwaWZRPT0ifQ==
