name: 'Build and push a custom image with apko'
description: 'Composite action for building and pushing a custom image with apko'
inputs:
  context:
    description: 'Path to the context directory'
    required: true

  component:
    description: 'Name of the component (e.g. kotsadm, kurl-proxy, etc...)'
    required: true

  git-tag:
    description: 'Git tag'
    required: true

  image-name:
    description: 'Full destination image name'
    required: true

  registry-username:
    description: 'Username to login to registry'
    default: ''
    required: false

  registry-password:
    description: 'Password to login to registry'
    default: ''
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: ${{ inputs.component }}-melange-packages-*
        path: ./packages/
        merge-multiple: true

    - uses: actions/download-artifact@v4
      with:
        pattern: ${{ inputs.component }}-melange-rsa-pub-*
        merge-multiple: true

    - name: template apko config
      shell: bash
      run: |
        export GIT_TAG=${{ inputs.git-tag }}
        envsubst '${GIT_TAG}' < ${{ inputs.context }}/apko.yaml.tmpl > ${{ inputs.context }}/apko.yaml

    # pin to work around https://github.com/chainguard-images/actions/issues/160
    - uses: chainguard-images/actions/apko-publish@49e3bc2feb790da6c3a7f749b38c769174c4ad54
      with:
        apko-image: ghcr.io/wolfi-dev/sdk@sha256:b3c690e2aff7a6e6259632047b5d6133169204f7011b9936731cf3f403d5a8c1
        config: ${{ inputs.context }}/apko.yaml
        archs: amd64,arm64
        tag: ${{ inputs.image-name }}
        vcs-url: true
        generic-user: ${{ inputs.registry-username }}
        generic-pass: ${{ inputs.registry-password }}
