/*
Copyright 2019 Replicated, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/replicatedhq/kots/kotskinds/apis/kots/v1beta1"
	scheme "github.com/replicatedhq/kots/kotskinds/client/kotsclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// IdentityConfigsGetter has a method to return a IdentityConfigInterface.
// A group's client should implement this interface.
type IdentityConfigsGetter interface {
	IdentityConfigs(namespace string) IdentityConfigInterface
}

// IdentityConfigInterface has methods to work with IdentityConfig resources.
type IdentityConfigInterface interface {
	Create(ctx context.Context, identityConfig *v1beta1.IdentityConfig, opts v1.CreateOptions) (*v1beta1.IdentityConfig, error)
	Update(ctx context.Context, identityConfig *v1beta1.IdentityConfig, opts v1.UpdateOptions) (*v1beta1.IdentityConfig, error)
	UpdateStatus(ctx context.Context, identityConfig *v1beta1.IdentityConfig, opts v1.UpdateOptions) (*v1beta1.IdentityConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.IdentityConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.IdentityConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.IdentityConfig, err error)
	IdentityConfigExpansion
}

// identityConfigs implements IdentityConfigInterface
type identityConfigs struct {
	client rest.Interface
	ns     string
}

// newIdentityConfigs returns a IdentityConfigs
func newIdentityConfigs(c *KotsV1beta1Client, namespace string) *identityConfigs {
	return &identityConfigs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the identityConfig, and returns the corresponding identityConfig object, and an error if there is any.
func (c *identityConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.IdentityConfig, err error) {
	result = &v1beta1.IdentityConfig{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("identityconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IdentityConfigs that match those selectors.
func (c *identityConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.IdentityConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.IdentityConfigList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("identityconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested identityConfigs.
func (c *identityConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("identityconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a identityConfig and creates it.  Returns the server's representation of the identityConfig, and an error, if there is any.
func (c *identityConfigs) Create(ctx context.Context, identityConfig *v1beta1.IdentityConfig, opts v1.CreateOptions) (result *v1beta1.IdentityConfig, err error) {
	result = &v1beta1.IdentityConfig{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("identityconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(identityConfig).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a identityConfig and updates it. Returns the server's representation of the identityConfig, and an error, if there is any.
func (c *identityConfigs) Update(ctx context.Context, identityConfig *v1beta1.IdentityConfig, opts v1.UpdateOptions) (result *v1beta1.IdentityConfig, err error) {
	result = &v1beta1.IdentityConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("identityconfigs").
		Name(identityConfig.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(identityConfig).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *identityConfigs) UpdateStatus(ctx context.Context, identityConfig *v1beta1.IdentityConfig, opts v1.UpdateOptions) (result *v1beta1.IdentityConfig, err error) {
	result = &v1beta1.IdentityConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("identityconfigs").
		Name(identityConfig.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(identityConfig).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the identityConfig and deletes it. Returns an error if one occurs.
func (c *identityConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("identityconfigs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *identityConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("identityconfigs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched identityConfig.
func (c *identityConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.IdentityConfig, err error) {
	result = &v1beta1.IdentityConfig{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("identityconfigs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
