/*
Copyright 2019 Replicated, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1beta1 "github.com/replicatedhq/kots/kotskinds/apis/kots/v1beta1"
	scheme "github.com/replicatedhq/kots/kotskinds/client/kotsclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// InstallersGetter has a method to return a InstallerInterface.
// A group's client should implement this interface.
type InstallersGetter interface {
	Installers(namespace string) InstallerInterface
}

// InstallerInterface has methods to work with Installer resources.
type InstallerInterface interface {
	Create(*v1beta1.Installer) (*v1beta1.Installer, error)
	Update(*v1beta1.Installer) (*v1beta1.Installer, error)
	UpdateStatus(*v1beta1.Installer) (*v1beta1.Installer, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.Installer, error)
	List(opts v1.ListOptions) (*v1beta1.InstallerList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.Installer, err error)
	InstallerExpansion
}

// installers implements InstallerInterface
type installers struct {
	client rest.Interface
	ns     string
}

// newInstallers returns a Installers
func newInstallers(c *KotsV1beta1Client, namespace string) *installers {
	return &installers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the installer, and returns the corresponding installer object, and an error if there is any.
func (c *installers) Get(name string, options v1.GetOptions) (result *v1beta1.Installer, err error) {
	result = &v1beta1.Installer{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("installers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Installers that match those selectors.
func (c *installers) List(opts v1.ListOptions) (result *v1beta1.InstallerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.InstallerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("installers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested installers.
func (c *installers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("installers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a installer and creates it.  Returns the server's representation of the installer, and an error, if there is any.
func (c *installers) Create(installer *v1beta1.Installer) (result *v1beta1.Installer, err error) {
	result = &v1beta1.Installer{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("installers").
		Body(installer).
		Do().
		Into(result)
	return
}

// Update takes the representation of a installer and updates it. Returns the server's representation of the installer, and an error, if there is any.
func (c *installers) Update(installer *v1beta1.Installer) (result *v1beta1.Installer, err error) {
	result = &v1beta1.Installer{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("installers").
		Name(installer.Name).
		Body(installer).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *installers) UpdateStatus(installer *v1beta1.Installer) (result *v1beta1.Installer, err error) {
	result = &v1beta1.Installer{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("installers").
		Name(installer.Name).
		SubResource("status").
		Body(installer).
		Do().
		Into(result)
	return
}

// Delete takes name of the installer and deletes it. Returns an error if one occurs.
func (c *installers) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("installers").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *installers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("installers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched installer.
func (c *installers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.Installer, err error) {
	result = &v1beta1.Installer{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("installers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
