/*
Copyright 2019 Replicated, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1beta1 "github.com/replicatedhq/kots/kotskinds/apis/kots/v1beta1"
	scheme "github.com/replicatedhq/kots/kotskinds/client/kotsclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// InstallationsGetter has a method to return a InstallationInterface.
// A group's client should implement this interface.
type InstallationsGetter interface {
	Installations(namespace string) InstallationInterface
}

// InstallationInterface has methods to work with Installation resources.
type InstallationInterface interface {
	Create(*v1beta1.Installation) (*v1beta1.Installation, error)
	Update(*v1beta1.Installation) (*v1beta1.Installation, error)
	UpdateStatus(*v1beta1.Installation) (*v1beta1.Installation, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.Installation, error)
	List(opts v1.ListOptions) (*v1beta1.InstallationList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.Installation, err error)
	InstallationExpansion
}

// installations implements InstallationInterface
type installations struct {
	client rest.Interface
	ns     string
}

// newInstallations returns a Installations
func newInstallations(c *KotsV1beta1Client, namespace string) *installations {
	return &installations{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the installation, and returns the corresponding installation object, and an error if there is any.
func (c *installations) Get(name string, options v1.GetOptions) (result *v1beta1.Installation, err error) {
	result = &v1beta1.Installation{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("installations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Installations that match those selectors.
func (c *installations) List(opts v1.ListOptions) (result *v1beta1.InstallationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.InstallationList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("installations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested installations.
func (c *installations) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("installations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a installation and creates it.  Returns the server's representation of the installation, and an error, if there is any.
func (c *installations) Create(installation *v1beta1.Installation) (result *v1beta1.Installation, err error) {
	result = &v1beta1.Installation{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("installations").
		Body(installation).
		Do().
		Into(result)
	return
}

// Update takes the representation of a installation and updates it. Returns the server's representation of the installation, and an error, if there is any.
func (c *installations) Update(installation *v1beta1.Installation) (result *v1beta1.Installation, err error) {
	result = &v1beta1.Installation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("installations").
		Name(installation.Name).
		Body(installation).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *installations) UpdateStatus(installation *v1beta1.Installation) (result *v1beta1.Installation, err error) {
	result = &v1beta1.Installation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("installations").
		Name(installation.Name).
		SubResource("status").
		Body(installation).
		Do().
		Into(result)
	return
}

// Delete takes name of the installation and deletes it. Returns an error if one occurs.
func (c *installations) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("installations").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *installations) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("installations").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched installation.
func (c *installations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.Installation, err error) {
	result = &v1beta1.Installation{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("installations").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
