/*
Copyright 2019 Replicated, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1beta1 "github.com/replicatedhq/kots/kotskinds/apis/kots/v1beta1"
	scheme "github.com/replicatedhq/kots/kotskinds/client/kotsclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KurlValuesesGetter has a method to return a KurlValuesInterface.
// A group's client should implement this interface.
type KurlValuesesGetter interface {
	KurlValueses(namespace string) KurlValuesInterface
}

// KurlValuesInterface has methods to work with KurlValues resources.
type KurlValuesInterface interface {
	Create(*v1beta1.KurlValues) (*v1beta1.KurlValues, error)
	Update(*v1beta1.KurlValues) (*v1beta1.KurlValues, error)
	UpdateStatus(*v1beta1.KurlValues) (*v1beta1.KurlValues, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.KurlValues, error)
	List(opts v1.ListOptions) (*v1beta1.KurlValuesList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.KurlValues, err error)
	KurlValuesExpansion
}

// kurlValueses implements KurlValuesInterface
type kurlValueses struct {
	client rest.Interface
	ns     string
}

// newKurlValueses returns a KurlValueses
func newKurlValueses(c *KotsV1beta1Client, namespace string) *kurlValueses {
	return &kurlValueses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the kurlValues, and returns the corresponding kurlValues object, and an error if there is any.
func (c *kurlValueses) Get(name string, options v1.GetOptions) (result *v1beta1.KurlValues, err error) {
	result = &v1beta1.KurlValues{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kurlvalueses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KurlValueses that match those selectors.
func (c *kurlValueses) List(opts v1.ListOptions) (result *v1beta1.KurlValuesList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.KurlValuesList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kurlvalueses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kurlValueses.
func (c *kurlValueses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("kurlvalueses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a kurlValues and creates it.  Returns the server's representation of the kurlValues, and an error, if there is any.
func (c *kurlValueses) Create(kurlValues *v1beta1.KurlValues) (result *v1beta1.KurlValues, err error) {
	result = &v1beta1.KurlValues{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("kurlvalueses").
		Body(kurlValues).
		Do().
		Into(result)
	return
}

// Update takes the representation of a kurlValues and updates it. Returns the server's representation of the kurlValues, and an error, if there is any.
func (c *kurlValueses) Update(kurlValues *v1beta1.KurlValues) (result *v1beta1.KurlValues, err error) {
	result = &v1beta1.KurlValues{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kurlvalueses").
		Name(kurlValues.Name).
		Body(kurlValues).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *kurlValueses) UpdateStatus(kurlValues *v1beta1.KurlValues) (result *v1beta1.KurlValues, err error) {
	result = &v1beta1.KurlValues{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kurlvalueses").
		Name(kurlValues.Name).
		SubResource("status").
		Body(kurlValues).
		Do().
		Into(result)
	return
}

// Delete takes name of the kurlValues and deletes it. Returns an error if one occurs.
func (c *kurlValueses) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kurlvalueses").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kurlValueses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kurlvalueses").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched kurlValues.
func (c *kurlValueses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.KurlValues, err error) {
	result = &v1beta1.KurlValues{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("kurlvalueses").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
