/*
Copyright 2019 Replicated, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1beta1 "github.com/replicatedhq/kots/kotskinds/apis/kots/v1beta1"
	scheme "github.com/replicatedhq/kots/kotskinds/client/kotsclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// LicensesGetter has a method to return a LicenseInterface.
// A group's client should implement this interface.
type LicensesGetter interface {
	Licenses(namespace string) LicenseInterface
}

// LicenseInterface has methods to work with License resources.
type LicenseInterface interface {
	Create(*v1beta1.License) (*v1beta1.License, error)
	Update(*v1beta1.License) (*v1beta1.License, error)
	UpdateStatus(*v1beta1.License) (*v1beta1.License, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.License, error)
	List(opts v1.ListOptions) (*v1beta1.LicenseList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.License, err error)
	LicenseExpansion
}

// licenses implements LicenseInterface
type licenses struct {
	client rest.Interface
	ns     string
}

// newLicenses returns a Licenses
func newLicenses(c *KotsV1beta1Client, namespace string) *licenses {
	return &licenses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the license, and returns the corresponding license object, and an error if there is any.
func (c *licenses) Get(name string, options v1.GetOptions) (result *v1beta1.License, err error) {
	result = &v1beta1.License{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("licenses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Licenses that match those selectors.
func (c *licenses) List(opts v1.ListOptions) (result *v1beta1.LicenseList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.LicenseList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("licenses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested licenses.
func (c *licenses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("licenses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a license and creates it.  Returns the server's representation of the license, and an error, if there is any.
func (c *licenses) Create(license *v1beta1.License) (result *v1beta1.License, err error) {
	result = &v1beta1.License{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("licenses").
		Body(license).
		Do().
		Into(result)
	return
}

// Update takes the representation of a license and updates it. Returns the server's representation of the license, and an error, if there is any.
func (c *licenses) Update(license *v1beta1.License) (result *v1beta1.License, err error) {
	result = &v1beta1.License{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("licenses").
		Name(license.Name).
		Body(license).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *licenses) UpdateStatus(license *v1beta1.License) (result *v1beta1.License, err error) {
	result = &v1beta1.License{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("licenses").
		Name(license.Name).
		SubResource("status").
		Body(license).
		Do().
		Into(result)
	return
}

// Delete takes name of the license and deletes it. Returns an error if one occurs.
func (c *licenses) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("licenses").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *licenses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("licenses").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched license.
func (c *licenses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.License, err error) {
	result = &v1beta1.License{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("licenses").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
