name: 'Upload Playwright Report'
description: 'Uploads Playwright report and prints viewing instructions'
inputs:
  name:
    description: 'Name prefix for the artifact'
    required: true
  report-path:
    description: 'Path to the Playwright report directory'
    required: true

runs:
  using: "composite"
  steps:
    - id: upload-playwright-report
      uses: actions/upload-artifact@v4
      if: ${{ failure() }}
      with:
        name: ${{ inputs.name }}-playwright-report
        path: ${{ inputs.report-path }}

    - name: Print instructions to view Playwright report
      if: ${{ failure() && steps.upload-playwright-report.outputs.artifact-url != '' }}
      run: |
        echo -e "\e[1;33m┌──────────────────────────────────────────────────────────────────────────────────────────────────────┐\e[0m"
        echo -e "\e[1;33m                                  To view the Playwright test report:                                   \e[0m"
        echo -e "\e[1;33m                                                                                                        \e[0m"
        echo -e "\e[1;33m   1- Download & extract the report from:                                                               \e[0m"
        echo -e "\e[1;33m                                                                                                        \e[0m"
        echo -e "\e[1;34m      ${{ steps.upload-playwright-report.outputs.artifact-url }}                                        \e[0m"
        echo -e "\e[1;33m                                                                                                        \e[0m"
        echo -e "\e[1;33m   2- From inside the extracted directory, run:                                                         \e[0m"
        echo -e "\e[1;33m                                                                                                        \e[0m"
        echo -e "\e[1;32m      npx playwright show-report .                                                                      \e[0m"
        echo -e "\e[1;33m                                                                                                        \e[0m"
        echo -e "\e[1;33m└──────────────────────────────────────────────────────────────────────────────────────────────────────┘\e[0m"
      shell: bash