apiVersion: v1
kind: Service
metadata:
  name: kotsadm-web # ethan insists on keeping this (salah) :)
  labels:
    app: kotsadm-nginx
spec:
  type: NodePort
  ports:
  - name: http
    port: 30000
    targetPort: http
    nodePort: 30000
  selector:
    app: kotsadm-nginx
