apiVersion: v1
kind: Service
metadata:
  name: kotsadm-web-js
  labels:
    app: kotsadm-web
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 30000
    targetPort: http
  selector:
    app: kotsadm-web