FROM golang:1.16 as deps

ENV PROJECTPATH=/go/src/github.com/replicatedhq/kots/kotsadm/operator
WORKDIR $PROJECTPATH
COPY Makefile ./
COPY Makefile.build ./
COPY go.mod ./
COPY go.sum ./
COPY cmd ./cmd
COPY pkg ./pkg

RUN make build
