// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/handlers/interface.go

// Package mock_handlers is a generated GoMock package.
package mock_handlers

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockKOTSHandler is a mock of KOTSHandler interface.
type MockKOTSHandler struct {
	ctrl     *gomock.Controller
	recorder *MockKOTSHandlerMockRecorder
}

// MockKOTSHandlerMockRecorder is the mock recorder for MockKOTSHandler.
type MockKOTSHandlerMockRecorder struct {
	mock *MockKOTSHandler
}

// NewMockKOTSHandler creates a new mock instance.
func NewMockKOTSHandler(ctrl *gomock.Controller) *MockKOTSHandler {
	mock := &MockKOTSHandler{ctrl: ctrl}
	mock.recorder = &MockKOTSHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKOTSHandler) EXPECT() *MockKOTSHandlerMockRecorder {
	return m.recorder
}

// AirgapBundleExists mocks base method.
func (m *MockKOTSHandler) AirgapBundleExists(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AirgapBundleExists", w, r)
}

// AirgapBundleExists indicates an expected call of AirgapBundleExists.
func (mr *MockKOTSHandlerMockRecorder) AirgapBundleExists(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AirgapBundleExists", reflect.TypeOf((*MockKOTSHandler)(nil).AirgapBundleExists), w, r)
}

// AirgapBundleProgress mocks base method.
func (m *MockKOTSHandler) AirgapBundleProgress(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AirgapBundleProgress", w, r)
}

// AirgapBundleProgress indicates an expected call of AirgapBundleProgress.
func (mr *MockKOTSHandlerMockRecorder) AirgapBundleProgress(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AirgapBundleProgress", reflect.TypeOf((*MockKOTSHandler)(nil).AirgapBundleProgress), w, r)
}

// AppUpdateCheck mocks base method.
func (m *MockKOTSHandler) AppUpdateCheck(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppUpdateCheck", w, r)
}

// AppUpdateCheck indicates an expected call of AppUpdateCheck.
func (mr *MockKOTSHandlerMockRecorder) AppUpdateCheck(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppUpdateCheck", reflect.TypeOf((*MockKOTSHandler)(nil).AppUpdateCheck), w, r)
}

// CanInstallAppVersion mocks base method.
func (m *MockKOTSHandler) CanInstallAppVersion(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CanInstallAppVersion", w, r)
}

// CanInstallAppVersion indicates an expected call of CanInstallAppVersion.
func (mr *MockKOTSHandlerMockRecorder) CanInstallAppVersion(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanInstallAppVersion", reflect.TypeOf((*MockKOTSHandler)(nil).CanInstallAppVersion), w, r)
}

// CancelRestore mocks base method.
func (m *MockKOTSHandler) CancelRestore(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CancelRestore", w, r)
}

// CancelRestore indicates an expected call of CancelRestore.
func (mr *MockKOTSHandlerMockRecorder) CancelRestore(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelRestore", reflect.TypeOf((*MockKOTSHandler)(nil).CancelRestore), w, r)
}

// ChangeLicense mocks base method.
func (m *MockKOTSHandler) ChangeLicense(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ChangeLicense", w, r)
}

// ChangeLicense indicates an expected call of ChangeLicense.
func (mr *MockKOTSHandlerMockRecorder) ChangeLicense(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeLicense", reflect.TypeOf((*MockKOTSHandler)(nil).ChangeLicense), w, r)
}

// ChangePassword mocks base method.
func (m *MockKOTSHandler) ChangePassword(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ChangePassword", w, r)
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockKOTSHandlerMockRecorder) ChangePassword(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockKOTSHandler)(nil).ChangePassword), w, r)
}

// CheckAirgapBundleChunk mocks base method.
func (m *MockKOTSHandler) CheckAirgapBundleChunk(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CheckAirgapBundleChunk", w, r)
}

// CheckAirgapBundleChunk indicates an expected call of CheckAirgapBundleChunk.
func (mr *MockKOTSHandlerMockRecorder) CheckAirgapBundleChunk(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAirgapBundleChunk", reflect.TypeOf((*MockKOTSHandler)(nil).CheckAirgapBundleChunk), w, r)
}

// CollectSupportBundle mocks base method.
func (m *MockKOTSHandler) CollectSupportBundle(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CollectSupportBundle", w, r)
}

// CollectSupportBundle indicates an expected call of CollectSupportBundle.
func (mr *MockKOTSHandlerMockRecorder) CollectSupportBundle(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectSupportBundle", reflect.TypeOf((*MockKOTSHandler)(nil).CollectSupportBundle), w, r)
}

// ConfigureAppIdentityService mocks base method.
func (m *MockKOTSHandler) ConfigureAppIdentityService(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ConfigureAppIdentityService", w, r)
}

// ConfigureAppIdentityService indicates an expected call of ConfigureAppIdentityService.
func (mr *MockKOTSHandlerMockRecorder) ConfigureAppIdentityService(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigureAppIdentityService", reflect.TypeOf((*MockKOTSHandler)(nil).ConfigureAppIdentityService), w, r)
}

// ConfigureIdentityService mocks base method.
func (m *MockKOTSHandler) ConfigureIdentityService(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ConfigureIdentityService", w, r)
}

// ConfigureIdentityService indicates an expected call of ConfigureIdentityService.
func (mr *MockKOTSHandlerMockRecorder) ConfigureIdentityService(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigureIdentityService", reflect.TypeOf((*MockKOTSHandler)(nil).ConfigureIdentityService), w, r)
}

// ConfirmEmbeddedClusterManagement mocks base method.
func (m *MockKOTSHandler) ConfirmEmbeddedClusterManagement(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ConfirmEmbeddedClusterManagement", w, r)
}

// ConfirmEmbeddedClusterManagement indicates an expected call of ConfirmEmbeddedClusterManagement.
func (mr *MockKOTSHandlerMockRecorder) ConfirmEmbeddedClusterManagement(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmEmbeddedClusterManagement", reflect.TypeOf((*MockKOTSHandler)(nil).ConfirmEmbeddedClusterManagement), w, r)
}

// CreateAppFromAirgap mocks base method.
func (m *MockKOTSHandler) CreateAppFromAirgap(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateAppFromAirgap", w, r)
}

// CreateAppFromAirgap indicates an expected call of CreateAppFromAirgap.
func (mr *MockKOTSHandlerMockRecorder) CreateAppFromAirgap(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAppFromAirgap", reflect.TypeOf((*MockKOTSHandler)(nil).CreateAppFromAirgap), w, r)
}

// CreateApplicationBackup mocks base method.
func (m *MockKOTSHandler) CreateApplicationBackup(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateApplicationBackup", w, r)
}

// CreateApplicationBackup indicates an expected call of CreateApplicationBackup.
func (mr *MockKOTSHandlerMockRecorder) CreateApplicationBackup(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApplicationBackup", reflect.TypeOf((*MockKOTSHandler)(nil).CreateApplicationBackup), w, r)
}

// CreateApplicationRestore mocks base method.
func (m *MockKOTSHandler) CreateApplicationRestore(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateApplicationRestore", w, r)
}

// CreateApplicationRestore indicates an expected call of CreateApplicationRestore.
func (mr *MockKOTSHandlerMockRecorder) CreateApplicationRestore(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApplicationRestore", reflect.TypeOf((*MockKOTSHandler)(nil).CreateApplicationRestore), w, r)
}

// CreateGitOps mocks base method.
func (m *MockKOTSHandler) CreateGitOps(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateGitOps", w, r)
}

// CreateGitOps indicates an expected call of CreateGitOps.
func (mr *MockKOTSHandlerMockRecorder) CreateGitOps(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGitOps", reflect.TypeOf((*MockKOTSHandler)(nil).CreateGitOps), w, r)
}

// CreateInstanceBackup mocks base method.
func (m *MockKOTSHandler) CreateInstanceBackup(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateInstanceBackup", w, r)
}

// CreateInstanceBackup indicates an expected call of CreateInstanceBackup.
func (mr *MockKOTSHandlerMockRecorder) CreateInstanceBackup(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInstanceBackup", reflect.TypeOf((*MockKOTSHandler)(nil).CreateInstanceBackup), w, r)
}

// CurrentAppConfig mocks base method.
func (m *MockKOTSHandler) CurrentAppConfig(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CurrentAppConfig", w, r)
}

// CurrentAppConfig indicates an expected call of CurrentAppConfig.
func (mr *MockKOTSHandlerMockRecorder) CurrentAppConfig(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentAppConfig", reflect.TypeOf((*MockKOTSHandler)(nil).CurrentAppConfig), w, r)
}

// DeleteBackup mocks base method.
func (m *MockKOTSHandler) DeleteBackup(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteBackup", w, r)
}

// DeleteBackup indicates an expected call of DeleteBackup.
func (mr *MockKOTSHandlerMockRecorder) DeleteBackup(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBackup", reflect.TypeOf((*MockKOTSHandler)(nil).DeleteBackup), w, r)
}

// DeleteEmbeddedClusterNode mocks base method.
func (m *MockKOTSHandler) DeleteEmbeddedClusterNode(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteEmbeddedClusterNode", w, r)
}

// DeleteEmbeddedClusterNode indicates an expected call of DeleteEmbeddedClusterNode.
func (mr *MockKOTSHandlerMockRecorder) DeleteEmbeddedClusterNode(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEmbeddedClusterNode", reflect.TypeOf((*MockKOTSHandler)(nil).DeleteEmbeddedClusterNode), w, r)
}

// DeleteKurlNode mocks base method.
func (m *MockKOTSHandler) DeleteKurlNode(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteKurlNode", w, r)
}

// DeleteKurlNode indicates an expected call of DeleteKurlNode.
func (mr *MockKOTSHandlerMockRecorder) DeleteKurlNode(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKurlNode", reflect.TypeOf((*MockKOTSHandler)(nil).DeleteKurlNode), w, r)
}

// DeleteRedact mocks base method.
func (m *MockKOTSHandler) DeleteRedact(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteRedact", w, r)
}

// DeleteRedact indicates an expected call of DeleteRedact.
func (mr *MockKOTSHandlerMockRecorder) DeleteRedact(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRedact", reflect.TypeOf((*MockKOTSHandler)(nil).DeleteRedact), w, r)
}

// DeleteSupportBundle mocks base method.
func (m *MockKOTSHandler) DeleteSupportBundle(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteSupportBundle", w, r)
}

// DeleteSupportBundle indicates an expected call of DeleteSupportBundle.
func (mr *MockKOTSHandlerMockRecorder) DeleteSupportBundle(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSupportBundle", reflect.TypeOf((*MockKOTSHandler)(nil).DeleteSupportBundle), w, r)
}

// DeployAppVersion mocks base method.
func (m *MockKOTSHandler) DeployAppVersion(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeployAppVersion", w, r)
}

// DeployAppVersion indicates an expected call of DeployAppVersion.
func (mr *MockKOTSHandlerMockRecorder) DeployAppVersion(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeployAppVersion", reflect.TypeOf((*MockKOTSHandler)(nil).DeployAppVersion), w, r)
}

// DisableAppGitOps mocks base method.
func (m *MockKOTSHandler) DisableAppGitOps(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DisableAppGitOps", w, r)
}

// DisableAppGitOps indicates an expected call of DisableAppGitOps.
func (mr *MockKOTSHandlerMockRecorder) DisableAppGitOps(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableAppGitOps", reflect.TypeOf((*MockKOTSHandler)(nil).DisableAppGitOps), w, r)
}

// DockerHubSecretUpdated mocks base method.
func (m *MockKOTSHandler) DockerHubSecretUpdated(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DockerHubSecretUpdated", w, r)
}

// DockerHubSecretUpdated indicates an expected call of DockerHubSecretUpdated.
func (mr *MockKOTSHandlerMockRecorder) DockerHubSecretUpdated(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DockerHubSecretUpdated", reflect.TypeOf((*MockKOTSHandler)(nil).DockerHubSecretUpdated), w, r)
}

// DownloadAppVersion mocks base method.
func (m *MockKOTSHandler) DownloadAppVersion(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DownloadAppVersion", w, r)
}

// DownloadAppVersion indicates an expected call of DownloadAppVersion.
func (mr *MockKOTSHandlerMockRecorder) DownloadAppVersion(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadAppVersion", reflect.TypeOf((*MockKOTSHandler)(nil).DownloadAppVersion), w, r)
}

// DownloadFileFromConfig mocks base method.
func (m *MockKOTSHandler) DownloadFileFromConfig(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DownloadFileFromConfig", w, r)
}

// DownloadFileFromConfig indicates an expected call of DownloadFileFromConfig.
func (mr *MockKOTSHandlerMockRecorder) DownloadFileFromConfig(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadFileFromConfig", reflect.TypeOf((*MockKOTSHandler)(nil).DownloadFileFromConfig), w, r)
}

// DownloadSnapshotLogs mocks base method.
func (m *MockKOTSHandler) DownloadSnapshotLogs(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DownloadSnapshotLogs", w, r)
}

// DownloadSnapshotLogs indicates an expected call of DownloadSnapshotLogs.
func (mr *MockKOTSHandlerMockRecorder) DownloadSnapshotLogs(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadSnapshotLogs", reflect.TypeOf((*MockKOTSHandler)(nil).DownloadSnapshotLogs), w, r)
}

// DownloadSupportBundle mocks base method.
func (m *MockKOTSHandler) DownloadSupportBundle(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DownloadSupportBundle", w, r)
}

// DownloadSupportBundle indicates an expected call of DownloadSupportBundle.
func (mr *MockKOTSHandlerMockRecorder) DownloadSupportBundle(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadSupportBundle", reflect.TypeOf((*MockKOTSHandler)(nil).DownloadSupportBundle), w, r)
}

// DrainEmbeddedClusterNode mocks base method.
func (m *MockKOTSHandler) DrainEmbeddedClusterNode(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DrainEmbeddedClusterNode", w, r)
}

// DrainEmbeddedClusterNode indicates an expected call of DrainEmbeddedClusterNode.
func (mr *MockKOTSHandlerMockRecorder) DrainEmbeddedClusterNode(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DrainEmbeddedClusterNode", reflect.TypeOf((*MockKOTSHandler)(nil).DrainEmbeddedClusterNode), w, r)
}

// DrainKurlNode mocks base method.
func (m *MockKOTSHandler) DrainKurlNode(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DrainKurlNode", w, r)
}

// DrainKurlNode indicates an expected call of DrainKurlNode.
func (mr *MockKOTSHandlerMockRecorder) DrainKurlNode(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DrainKurlNode", reflect.TypeOf((*MockKOTSHandler)(nil).DrainKurlNode), w, r)
}

// ExchangePlatformLicense mocks base method.
func (m *MockKOTSHandler) ExchangePlatformLicense(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ExchangePlatformLicense", w, r)
}

// ExchangePlatformLicense indicates an expected call of ExchangePlatformLicense.
func (mr *MockKOTSHandlerMockRecorder) ExchangePlatformLicense(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangePlatformLicense", reflect.TypeOf((*MockKOTSHandler)(nil).ExchangePlatformLicense), w, r)
}

// GarbageCollectImages mocks base method.
func (m *MockKOTSHandler) GarbageCollectImages(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GarbageCollectImages", w, r)
}

// GarbageCollectImages indicates an expected call of GarbageCollectImages.
func (mr *MockKOTSHandlerMockRecorder) GarbageCollectImages(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GarbageCollectImages", reflect.TypeOf((*MockKOTSHandler)(nil).GarbageCollectImages), w, r)
}

// GenerateEmbeddedClusterNodeJoinCommand mocks base method.
func (m *MockKOTSHandler) GenerateEmbeddedClusterNodeJoinCommand(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GenerateEmbeddedClusterNodeJoinCommand", w, r)
}

// GenerateEmbeddedClusterNodeJoinCommand indicates an expected call of GenerateEmbeddedClusterNodeJoinCommand.
func (mr *MockKOTSHandlerMockRecorder) GenerateEmbeddedClusterNodeJoinCommand(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateEmbeddedClusterNodeJoinCommand", reflect.TypeOf((*MockKOTSHandler)(nil).GenerateEmbeddedClusterNodeJoinCommand), w, r)
}

// GenerateKurlNodeJoinCommandMaster mocks base method.
func (m *MockKOTSHandler) GenerateKurlNodeJoinCommandMaster(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GenerateKurlNodeJoinCommandMaster", w, r)
}

// GenerateKurlNodeJoinCommandMaster indicates an expected call of GenerateKurlNodeJoinCommandMaster.
func (mr *MockKOTSHandlerMockRecorder) GenerateKurlNodeJoinCommandMaster(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateKurlNodeJoinCommandMaster", reflect.TypeOf((*MockKOTSHandler)(nil).GenerateKurlNodeJoinCommandMaster), w, r)
}

// GenerateKurlNodeJoinCommandPrimary mocks base method.
func (m *MockKOTSHandler) GenerateKurlNodeJoinCommandPrimary(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GenerateKurlNodeJoinCommandPrimary", w, r)
}

// GenerateKurlNodeJoinCommandPrimary indicates an expected call of GenerateKurlNodeJoinCommandPrimary.
func (mr *MockKOTSHandlerMockRecorder) GenerateKurlNodeJoinCommandPrimary(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateKurlNodeJoinCommandPrimary", reflect.TypeOf((*MockKOTSHandler)(nil).GenerateKurlNodeJoinCommandPrimary), w, r)
}

// GenerateKurlNodeJoinCommandSecondary mocks base method.
func (m *MockKOTSHandler) GenerateKurlNodeJoinCommandSecondary(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GenerateKurlNodeJoinCommandSecondary", w, r)
}

// GenerateKurlNodeJoinCommandSecondary indicates an expected call of GenerateKurlNodeJoinCommandSecondary.
func (mr *MockKOTSHandlerMockRecorder) GenerateKurlNodeJoinCommandSecondary(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateKurlNodeJoinCommandSecondary", reflect.TypeOf((*MockKOTSHandler)(nil).GenerateKurlNodeJoinCommandSecondary), w, r)
}

// GenerateKurlNodeJoinCommandWorker mocks base method.
func (m *MockKOTSHandler) GenerateKurlNodeJoinCommandWorker(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GenerateKurlNodeJoinCommandWorker", w, r)
}

// GenerateKurlNodeJoinCommandWorker indicates an expected call of GenerateKurlNodeJoinCommandWorker.
func (mr *MockKOTSHandlerMockRecorder) GenerateKurlNodeJoinCommandWorker(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateKurlNodeJoinCommandWorker", reflect.TypeOf((*MockKOTSHandler)(nil).GenerateKurlNodeJoinCommandWorker), w, r)
}

// GetAdminConsoleUpdateStatus mocks base method.
func (m *MockKOTSHandler) GetAdminConsoleUpdateStatus(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetAdminConsoleUpdateStatus", w, r)
}

// GetAdminConsoleUpdateStatus indicates an expected call of GetAdminConsoleUpdateStatus.
func (mr *MockKOTSHandlerMockRecorder) GetAdminConsoleUpdateStatus(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminConsoleUpdateStatus", reflect.TypeOf((*MockKOTSHandler)(nil).GetAdminConsoleUpdateStatus), w, r)
}

// GetAirgapInstallStatus mocks base method.
func (m *MockKOTSHandler) GetAirgapInstallStatus(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetAirgapInstallStatus", w, r)
}

// GetAirgapInstallStatus indicates an expected call of GetAirgapInstallStatus.
func (mr *MockKOTSHandlerMockRecorder) GetAirgapInstallStatus(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAirgapInstallStatus", reflect.TypeOf((*MockKOTSHandler)(nil).GetAirgapInstallStatus), w, r)
}

// GetAirgapUploadConfig mocks base method.
func (m *MockKOTSHandler) GetAirgapUploadConfig(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetAirgapUploadConfig", w, r)
}

// GetAirgapUploadConfig indicates an expected call of GetAirgapUploadConfig.
func (mr *MockKOTSHandlerMockRecorder) GetAirgapUploadConfig(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAirgapUploadConfig", reflect.TypeOf((*MockKOTSHandler)(nil).GetAirgapUploadConfig), w, r)
}

// GetApp mocks base method.
func (m *MockKOTSHandler) GetApp(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetApp", w, r)
}

// GetApp indicates an expected call of GetApp.
func (mr *MockKOTSHandlerMockRecorder) GetApp(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApp", reflect.TypeOf((*MockKOTSHandler)(nil).GetApp), w, r)
}

// GetAppContents mocks base method.
func (m *MockKOTSHandler) GetAppContents(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetAppContents", w, r)
}

// GetAppContents indicates an expected call of GetAppContents.
func (mr *MockKOTSHandlerMockRecorder) GetAppContents(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppContents", reflect.TypeOf((*MockKOTSHandler)(nil).GetAppContents), w, r)
}

// GetAppDashboard mocks base method.
func (m *MockKOTSHandler) GetAppDashboard(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetAppDashboard", w, r)
}

// GetAppDashboard indicates an expected call of GetAppDashboard.
func (mr *MockKOTSHandlerMockRecorder) GetAppDashboard(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppDashboard", reflect.TypeOf((*MockKOTSHandler)(nil).GetAppDashboard), w, r)
}

// GetAppIdentityServiceConfig mocks base method.
func (m *MockKOTSHandler) GetAppIdentityServiceConfig(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetAppIdentityServiceConfig", w, r)
}

// GetAppIdentityServiceConfig indicates an expected call of GetAppIdentityServiceConfig.
func (mr *MockKOTSHandlerMockRecorder) GetAppIdentityServiceConfig(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppIdentityServiceConfig", reflect.TypeOf((*MockKOTSHandler)(nil).GetAppIdentityServiceConfig), w, r)
}

// GetAppRegistry mocks base method.
func (m *MockKOTSHandler) GetAppRegistry(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetAppRegistry", w, r)
}

// GetAppRegistry indicates an expected call of GetAppRegistry.
func (mr *MockKOTSHandlerMockRecorder) GetAppRegistry(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppRegistry", reflect.TypeOf((*MockKOTSHandler)(nil).GetAppRegistry), w, r)
}

// GetAppRenderedContents mocks base method.
func (m *MockKOTSHandler) GetAppRenderedContents(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetAppRenderedContents", w, r)
}

// GetAppRenderedContents indicates an expected call of GetAppRenderedContents.
func (mr *MockKOTSHandlerMockRecorder) GetAppRenderedContents(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppRenderedContents", reflect.TypeOf((*MockKOTSHandler)(nil).GetAppRenderedContents), w, r)
}

// GetAppStatus mocks base method.
func (m *MockKOTSHandler) GetAppStatus(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetAppStatus", w, r)
}

// GetAppStatus indicates an expected call of GetAppStatus.
func (mr *MockKOTSHandlerMockRecorder) GetAppStatus(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppStatus", reflect.TypeOf((*MockKOTSHandler)(nil).GetAppStatus), w, r)
}

// GetAppVersionDownloadStatus mocks base method.
func (m *MockKOTSHandler) GetAppVersionDownloadStatus(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetAppVersionDownloadStatus", w, r)
}

// GetAppVersionDownloadStatus indicates an expected call of GetAppVersionDownloadStatus.
func (mr *MockKOTSHandlerMockRecorder) GetAppVersionDownloadStatus(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppVersionDownloadStatus", reflect.TypeOf((*MockKOTSHandler)(nil).GetAppVersionDownloadStatus), w, r)
}

// GetAppVersionHistory mocks base method.
func (m *MockKOTSHandler) GetAppVersionHistory(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetAppVersionHistory", w, r)
}

// GetAppVersionHistory indicates an expected call of GetAppVersionHistory.
func (mr *MockKOTSHandlerMockRecorder) GetAppVersionHistory(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppVersionHistory", reflect.TypeOf((*MockKOTSHandler)(nil).GetAppVersionHistory), w, r)
}

// GetAutomatedInstallStatus mocks base method.
func (m *MockKOTSHandler) GetAutomatedInstallStatus(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetAutomatedInstallStatus", w, r)
}

// GetAutomatedInstallStatus indicates an expected call of GetAutomatedInstallStatus.
func (mr *MockKOTSHandlerMockRecorder) GetAutomatedInstallStatus(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAutomatedInstallStatus", reflect.TypeOf((*MockKOTSHandler)(nil).GetAutomatedInstallStatus), w, r)
}

// GetAutomaticUpdatesConfig mocks base method.
func (m *MockKOTSHandler) GetAutomaticUpdatesConfig(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetAutomaticUpdatesConfig", w, r)
}

// GetAutomaticUpdatesConfig indicates an expected call of GetAutomaticUpdatesConfig.
func (mr *MockKOTSHandlerMockRecorder) GetAutomaticUpdatesConfig(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAutomaticUpdatesConfig", reflect.TypeOf((*MockKOTSHandler)(nil).GetAutomaticUpdatesConfig), w, r)
}

// GetBackup mocks base method.
func (m *MockKOTSHandler) GetBackup(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetBackup", w, r)
}

// GetBackup indicates an expected call of GetBackup.
func (mr *MockKOTSHandlerMockRecorder) GetBackup(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackup", reflect.TypeOf((*MockKOTSHandler)(nil).GetBackup), w, r)
}

// GetDownstreamOutput mocks base method.
func (m *MockKOTSHandler) GetDownstreamOutput(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetDownstreamOutput", w, r)
}

// GetDownstreamOutput indicates an expected call of GetDownstreamOutput.
func (mr *MockKOTSHandlerMockRecorder) GetDownstreamOutput(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDownstreamOutput", reflect.TypeOf((*MockKOTSHandler)(nil).GetDownstreamOutput), w, r)
}

// GetEmbeddedClusterNode mocks base method.
func (m *MockKOTSHandler) GetEmbeddedClusterNode(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetEmbeddedClusterNode", w, r)
}

// GetEmbeddedClusterNode indicates an expected call of GetEmbeddedClusterNode.
func (mr *MockKOTSHandlerMockRecorder) GetEmbeddedClusterNode(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmbeddedClusterNode", reflect.TypeOf((*MockKOTSHandler)(nil).GetEmbeddedClusterNode), w, r)
}

// GetEmbeddedClusterNodes mocks base method.
func (m *MockKOTSHandler) GetEmbeddedClusterNodes(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetEmbeddedClusterNodes", w, r)
}

// GetEmbeddedClusterNodes indicates an expected call of GetEmbeddedClusterNodes.
func (mr *MockKOTSHandlerMockRecorder) GetEmbeddedClusterNodes(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmbeddedClusterNodes", reflect.TypeOf((*MockKOTSHandler)(nil).GetEmbeddedClusterNodes), w, r)
}

// GetEmbeddedClusterRoles mocks base method.
func (m *MockKOTSHandler) GetEmbeddedClusterRoles(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetEmbeddedClusterRoles", w, r)
}

// GetEmbeddedClusterRoles indicates an expected call of GetEmbeddedClusterRoles.
func (mr *MockKOTSHandlerMockRecorder) GetEmbeddedClusterRoles(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmbeddedClusterRoles", reflect.TypeOf((*MockKOTSHandler)(nil).GetEmbeddedClusterRoles), w, r)
}

// GetFileSystemSnapshotProviderInstructions mocks base method.
func (m *MockKOTSHandler) GetFileSystemSnapshotProviderInstructions(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetFileSystemSnapshotProviderInstructions", w, r)
}

// GetFileSystemSnapshotProviderInstructions indicates an expected call of GetFileSystemSnapshotProviderInstructions.
func (mr *MockKOTSHandlerMockRecorder) GetFileSystemSnapshotProviderInstructions(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileSystemSnapshotProviderInstructions", reflect.TypeOf((*MockKOTSHandler)(nil).GetFileSystemSnapshotProviderInstructions), w, r)
}

// GetGitOpsRepo mocks base method.
func (m *MockKOTSHandler) GetGitOpsRepo(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetGitOpsRepo", w, r)
}

// GetGitOpsRepo indicates an expected call of GetGitOpsRepo.
func (mr *MockKOTSHandlerMockRecorder) GetGitOpsRepo(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGitOpsRepo", reflect.TypeOf((*MockKOTSHandler)(nil).GetGitOpsRepo), w, r)
}

// GetGlobalSnapshotSettings mocks base method.
func (m *MockKOTSHandler) GetGlobalSnapshotSettings(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetGlobalSnapshotSettings", w, r)
}

// GetGlobalSnapshotSettings indicates an expected call of GetGlobalSnapshotSettings.
func (mr *MockKOTSHandlerMockRecorder) GetGlobalSnapshotSettings(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGlobalSnapshotSettings", reflect.TypeOf((*MockKOTSHandler)(nil).GetGlobalSnapshotSettings), w, r)
}

// GetIdentityServiceConfig mocks base method.
func (m *MockKOTSHandler) GetIdentityServiceConfig(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetIdentityServiceConfig", w, r)
}

// GetIdentityServiceConfig indicates an expected call of GetIdentityServiceConfig.
func (mr *MockKOTSHandlerMockRecorder) GetIdentityServiceConfig(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdentityServiceConfig", reflect.TypeOf((*MockKOTSHandler)(nil).GetIdentityServiceConfig), w, r)
}

// GetImageRewriteStatus mocks base method.
func (m *MockKOTSHandler) GetImageRewriteStatus(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetImageRewriteStatus", w, r)
}

// GetImageRewriteStatus indicates an expected call of GetImageRewriteStatus.
func (mr *MockKOTSHandlerMockRecorder) GetImageRewriteStatus(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImageRewriteStatus", reflect.TypeOf((*MockKOTSHandler)(nil).GetImageRewriteStatus), w, r)
}

// GetInstanceSnapshotConfig mocks base method.
func (m *MockKOTSHandler) GetInstanceSnapshotConfig(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetInstanceSnapshotConfig", w, r)
}

// GetInstanceSnapshotConfig indicates an expected call of GetInstanceSnapshotConfig.
func (mr *MockKOTSHandlerMockRecorder) GetInstanceSnapshotConfig(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstanceSnapshotConfig", reflect.TypeOf((*MockKOTSHandler)(nil).GetInstanceSnapshotConfig), w, r)
}

// GetKotsadmRegistry mocks base method.
func (m *MockKOTSHandler) GetKotsadmRegistry(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetKotsadmRegistry", w, r)
}

// GetKotsadmRegistry indicates an expected call of GetKotsadmRegistry.
func (mr *MockKOTSHandlerMockRecorder) GetKotsadmRegistry(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKotsadmRegistry", reflect.TypeOf((*MockKOTSHandler)(nil).GetKotsadmRegistry), w, r)
}

// GetKurlNodes mocks base method.
func (m *MockKOTSHandler) GetKurlNodes(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetKurlNodes", w, r)
}

// GetKurlNodes indicates an expected call of GetKurlNodes.
func (mr *MockKOTSHandlerMockRecorder) GetKurlNodes(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKurlNodes", reflect.TypeOf((*MockKOTSHandler)(nil).GetKurlNodes), w, r)
}

// GetLatestDeployableVersion mocks base method.
func (m *MockKOTSHandler) GetLatestDeployableVersion(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetLatestDeployableVersion", w, r)
}

// GetLatestDeployableVersion indicates an expected call of GetLatestDeployableVersion.
func (mr *MockKOTSHandlerMockRecorder) GetLatestDeployableVersion(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestDeployableVersion", reflect.TypeOf((*MockKOTSHandler)(nil).GetLatestDeployableVersion), w, r)
}

// GetLatestPreflightResultsForSequenceZero mocks base method.
func (m *MockKOTSHandler) GetLatestPreflightResultsForSequenceZero(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetLatestPreflightResultsForSequenceZero", w, r)
}

// GetLatestPreflightResultsForSequenceZero indicates an expected call of GetLatestPreflightResultsForSequenceZero.
func (mr *MockKOTSHandlerMockRecorder) GetLatestPreflightResultsForSequenceZero(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestPreflightResultsForSequenceZero", reflect.TypeOf((*MockKOTSHandler)(nil).GetLatestPreflightResultsForSequenceZero), w, r)
}

// GetLicense mocks base method.
func (m *MockKOTSHandler) GetLicense(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetLicense", w, r)
}

// GetLicense indicates an expected call of GetLicense.
func (mr *MockKOTSHandlerMockRecorder) GetLicense(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLicense", reflect.TypeOf((*MockKOTSHandler)(nil).GetLicense), w, r)
}

// GetOnlineInstallStatus mocks base method.
func (m *MockKOTSHandler) GetOnlineInstallStatus(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetOnlineInstallStatus", w, r)
}

// GetOnlineInstallStatus indicates an expected call of GetOnlineInstallStatus.
func (mr *MockKOTSHandlerMockRecorder) GetOnlineInstallStatus(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOnlineInstallStatus", reflect.TypeOf((*MockKOTSHandler)(nil).GetOnlineInstallStatus), w, r)
}

// GetPendingApp mocks base method.
func (m *MockKOTSHandler) GetPendingApp(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetPendingApp", w, r)
}

// GetPendingApp indicates an expected call of GetPendingApp.
func (mr *MockKOTSHandlerMockRecorder) GetPendingApp(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingApp", reflect.TypeOf((*MockKOTSHandler)(nil).GetPendingApp), w, r)
}

// GetPodDetailsFromSupportBundle mocks base method.
func (m *MockKOTSHandler) GetPodDetailsFromSupportBundle(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetPodDetailsFromSupportBundle", w, r)
}

// GetPodDetailsFromSupportBundle indicates an expected call of GetPodDetailsFromSupportBundle.
func (mr *MockKOTSHandlerMockRecorder) GetPodDetailsFromSupportBundle(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPodDetailsFromSupportBundle", reflect.TypeOf((*MockKOTSHandler)(nil).GetPodDetailsFromSupportBundle), w, r)
}

// GetPreflightCommand mocks base method.
func (m *MockKOTSHandler) GetPreflightCommand(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetPreflightCommand", w, r)
}

// GetPreflightCommand indicates an expected call of GetPreflightCommand.
func (mr *MockKOTSHandlerMockRecorder) GetPreflightCommand(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPreflightCommand", reflect.TypeOf((*MockKOTSHandler)(nil).GetPreflightCommand), w, r)
}

// GetPreflightResult mocks base method.
func (m *MockKOTSHandler) GetPreflightResult(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetPreflightResult", w, r)
}

// GetPreflightResult indicates an expected call of GetPreflightResult.
func (mr *MockKOTSHandlerMockRecorder) GetPreflightResult(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPreflightResult", reflect.TypeOf((*MockKOTSHandler)(nil).GetPreflightResult), w, r)
}

// GetRedact mocks base method.
func (m *MockKOTSHandler) GetRedact(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetRedact", w, r)
}

// GetRedact indicates an expected call of GetRedact.
func (mr *MockKOTSHandlerMockRecorder) GetRedact(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRedact", reflect.TypeOf((*MockKOTSHandler)(nil).GetRedact), w, r)
}

// GetRedactMetadataAndYaml mocks base method.
func (m *MockKOTSHandler) GetRedactMetadataAndYaml(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetRedactMetadataAndYaml", w, r)
}

// GetRedactMetadataAndYaml indicates an expected call of GetRedactMetadataAndYaml.
func (mr *MockKOTSHandlerMockRecorder) GetRedactMetadataAndYaml(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRedactMetadataAndYaml", reflect.TypeOf((*MockKOTSHandler)(nil).GetRedactMetadataAndYaml), w, r)
}

// GetRestoreAppsStatus mocks base method.
func (m *MockKOTSHandler) GetRestoreAppsStatus(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetRestoreAppsStatus", w, r)
}

// GetRestoreAppsStatus indicates an expected call of GetRestoreAppsStatus.
func (mr *MockKOTSHandlerMockRecorder) GetRestoreAppsStatus(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRestoreAppsStatus", reflect.TypeOf((*MockKOTSHandler)(nil).GetRestoreAppsStatus), w, r)
}

// GetRestoreDetails mocks base method.
func (m *MockKOTSHandler) GetRestoreDetails(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetRestoreDetails", w, r)
}

// GetRestoreDetails indicates an expected call of GetRestoreDetails.
func (mr *MockKOTSHandlerMockRecorder) GetRestoreDetails(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRestoreDetails", reflect.TypeOf((*MockKOTSHandler)(nil).GetRestoreDetails), w, r)
}

// GetRestoreStatus mocks base method.
func (m *MockKOTSHandler) GetRestoreStatus(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetRestoreStatus", w, r)
}

// GetRestoreStatus indicates an expected call of GetRestoreStatus.
func (mr *MockKOTSHandlerMockRecorder) GetRestoreStatus(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRestoreStatus", reflect.TypeOf((*MockKOTSHandler)(nil).GetRestoreStatus), w, r)
}

// GetSnapshotConfig mocks base method.
func (m *MockKOTSHandler) GetSnapshotConfig(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetSnapshotConfig", w, r)
}

// GetSnapshotConfig indicates an expected call of GetSnapshotConfig.
func (mr *MockKOTSHandlerMockRecorder) GetSnapshotConfig(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSnapshotConfig", reflect.TypeOf((*MockKOTSHandler)(nil).GetSnapshotConfig), w, r)
}

// GetSupportBundle mocks base method.
func (m *MockKOTSHandler) GetSupportBundle(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetSupportBundle", w, r)
}

// GetSupportBundle indicates an expected call of GetSupportBundle.
func (mr *MockKOTSHandlerMockRecorder) GetSupportBundle(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupportBundle", reflect.TypeOf((*MockKOTSHandler)(nil).GetSupportBundle), w, r)
}

// GetSupportBundleCommand mocks base method.
func (m *MockKOTSHandler) GetSupportBundleCommand(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetSupportBundleCommand", w, r)
}

// GetSupportBundleCommand indicates an expected call of GetSupportBundleCommand.
func (mr *MockKOTSHandlerMockRecorder) GetSupportBundleCommand(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupportBundleCommand", reflect.TypeOf((*MockKOTSHandler)(nil).GetSupportBundleCommand), w, r)
}

// GetSupportBundleFiles mocks base method.
func (m *MockKOTSHandler) GetSupportBundleFiles(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetSupportBundleFiles", w, r)
}

// GetSupportBundleFiles indicates an expected call of GetSupportBundleFiles.
func (mr *MockKOTSHandlerMockRecorder) GetSupportBundleFiles(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupportBundleFiles", reflect.TypeOf((*MockKOTSHandler)(nil).GetSupportBundleFiles), w, r)
}

// GetSupportBundleRedactions mocks base method.
func (m *MockKOTSHandler) GetSupportBundleRedactions(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetSupportBundleRedactions", w, r)
}

// GetSupportBundleRedactions indicates an expected call of GetSupportBundleRedactions.
func (mr *MockKOTSHandlerMockRecorder) GetSupportBundleRedactions(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupportBundleRedactions", reflect.TypeOf((*MockKOTSHandler)(nil).GetSupportBundleRedactions), w, r)
}

// GetUpdateDownloadStatus mocks base method.
func (m *MockKOTSHandler) GetUpdateDownloadStatus(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetUpdateDownloadStatus", w, r)
}

// GetUpdateDownloadStatus indicates an expected call of GetUpdateDownloadStatus.
func (mr *MockKOTSHandlerMockRecorder) GetUpdateDownloadStatus(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpdateDownloadStatus", reflect.TypeOf((*MockKOTSHandler)(nil).GetUpdateDownloadStatus), w, r)
}

// GetVeleroStatus mocks base method.
func (m *MockKOTSHandler) GetVeleroStatus(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetVeleroStatus", w, r)
}

// GetVeleroStatus indicates an expected call of GetVeleroStatus.
func (mr *MockKOTSHandlerMockRecorder) GetVeleroStatus(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVeleroStatus", reflect.TypeOf((*MockKOTSHandler)(nil).GetVeleroStatus), w, r)
}

// IgnorePreflightRBACErrors mocks base method.
func (m *MockKOTSHandler) IgnorePreflightRBACErrors(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IgnorePreflightRBACErrors", w, r)
}

// IgnorePreflightRBACErrors indicates an expected call of IgnorePreflightRBACErrors.
func (mr *MockKOTSHandlerMockRecorder) IgnorePreflightRBACErrors(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IgnorePreflightRBACErrors", reflect.TypeOf((*MockKOTSHandler)(nil).IgnorePreflightRBACErrors), w, r)
}

// InitGitOpsConnection mocks base method.
func (m *MockKOTSHandler) InitGitOpsConnection(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InitGitOpsConnection", w, r)
}

// InitGitOpsConnection indicates an expected call of InitGitOpsConnection.
func (mr *MockKOTSHandlerMockRecorder) InitGitOpsConnection(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitGitOpsConnection", reflect.TypeOf((*MockKOTSHandler)(nil).InitGitOpsConnection), w, r)
}

// ListApps mocks base method.
func (m *MockKOTSHandler) ListApps(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ListApps", w, r)
}

// ListApps indicates an expected call of ListApps.
func (mr *MockKOTSHandlerMockRecorder) ListApps(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListApps", reflect.TypeOf((*MockKOTSHandler)(nil).ListApps), w, r)
}

// ListBackups mocks base method.
func (m *MockKOTSHandler) ListBackups(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ListBackups", w, r)
}

// ListBackups indicates an expected call of ListBackups.
func (mr *MockKOTSHandlerMockRecorder) ListBackups(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBackups", reflect.TypeOf((*MockKOTSHandler)(nil).ListBackups), w, r)
}

// ListInstanceBackups mocks base method.
func (m *MockKOTSHandler) ListInstanceBackups(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ListInstanceBackups", w, r)
}

// ListInstanceBackups indicates an expected call of ListInstanceBackups.
func (mr *MockKOTSHandlerMockRecorder) ListInstanceBackups(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstanceBackups", reflect.TypeOf((*MockKOTSHandler)(nil).ListInstanceBackups), w, r)
}

// ListRedactors mocks base method.
func (m *MockKOTSHandler) ListRedactors(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ListRedactors", w, r)
}

// ListRedactors indicates an expected call of ListRedactors.
func (mr *MockKOTSHandlerMockRecorder) ListRedactors(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRedactors", reflect.TypeOf((*MockKOTSHandler)(nil).ListRedactors), w, r)
}

// ListSupportBundles mocks base method.
func (m *MockKOTSHandler) ListSupportBundles(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ListSupportBundles", w, r)
}

// ListSupportBundles indicates an expected call of ListSupportBundles.
func (mr *MockKOTSHandlerMockRecorder) ListSupportBundles(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSupportBundles", reflect.TypeOf((*MockKOTSHandler)(nil).ListSupportBundles), w, r)
}

// LiveAppConfig mocks base method.
func (m *MockKOTSHandler) LiveAppConfig(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LiveAppConfig", w, r)
}

// LiveAppConfig indicates an expected call of LiveAppConfig.
func (mr *MockKOTSHandlerMockRecorder) LiveAppConfig(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LiveAppConfig", reflect.TypeOf((*MockKOTSHandler)(nil).LiveAppConfig), w, r)
}

// Ping mocks base method.
func (m *MockKOTSHandler) Ping(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Ping", w, r)
}

// Ping indicates an expected call of Ping.
func (mr *MockKOTSHandlerMockRecorder) Ping(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockKOTSHandler)(nil).Ping), w, r)
}

// PreflightsReports mocks base method.
func (m *MockKOTSHandler) PreflightsReports(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PreflightsReports", w, r)
}

// PreflightsReports indicates an expected call of PreflightsReports.
func (mr *MockKOTSHandlerMockRecorder) PreflightsReports(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreflightsReports", reflect.TypeOf((*MockKOTSHandler)(nil).PreflightsReports), w, r)
}

// RedeployAppVersion mocks base method.
func (m *MockKOTSHandler) RedeployAppVersion(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RedeployAppVersion", w, r)
}

// RedeployAppVersion indicates an expected call of RedeployAppVersion.
func (mr *MockKOTSHandlerMockRecorder) RedeployAppVersion(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RedeployAppVersion", reflect.TypeOf((*MockKOTSHandler)(nil).RedeployAppVersion), w, r)
}

// RemoveApp mocks base method.
func (m *MockKOTSHandler) RemoveApp(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveApp", w, r)
}

// RemoveApp indicates an expected call of RemoveApp.
func (mr *MockKOTSHandlerMockRecorder) RemoveApp(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveApp", reflect.TypeOf((*MockKOTSHandler)(nil).RemoveApp), w, r)
}

// ResetAirgapInstallStatus mocks base method.
func (m *MockKOTSHandler) ResetAirgapInstallStatus(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ResetAirgapInstallStatus", w, r)
}

// ResetAirgapInstallStatus indicates an expected call of ResetAirgapInstallStatus.
func (mr *MockKOTSHandlerMockRecorder) ResetAirgapInstallStatus(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetAirgapInstallStatus", reflect.TypeOf((*MockKOTSHandler)(nil).ResetAirgapInstallStatus), w, r)
}

// ResetGitOps mocks base method.
func (m *MockKOTSHandler) ResetGitOps(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ResetGitOps", w, r)
}

// ResetGitOps indicates an expected call of ResetGitOps.
func (mr *MockKOTSHandlerMockRecorder) ResetGitOps(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetGitOps", reflect.TypeOf((*MockKOTSHandler)(nil).ResetGitOps), w, r)
}

// RestoreApps mocks base method.
func (m *MockKOTSHandler) RestoreApps(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RestoreApps", w, r)
}

// RestoreApps indicates an expected call of RestoreApps.
func (mr *MockKOTSHandlerMockRecorder) RestoreApps(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreApps", reflect.TypeOf((*MockKOTSHandler)(nil).RestoreApps), w, r)
}

// ResumeInstallOnline mocks base method.
func (m *MockKOTSHandler) ResumeInstallOnline(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ResumeInstallOnline", w, r)
}

// ResumeInstallOnline indicates an expected call of ResumeInstallOnline.
func (mr *MockKOTSHandlerMockRecorder) ResumeInstallOnline(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeInstallOnline", reflect.TypeOf((*MockKOTSHandler)(nil).ResumeInstallOnline), w, r)
}

// SaveInstanceSnapshotRetention mocks base method.
func (m *MockKOTSHandler) SaveInstanceSnapshotRetention(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SaveInstanceSnapshotRetention", w, r)
}

// SaveInstanceSnapshotRetention indicates an expected call of SaveInstanceSnapshotRetention.
func (mr *MockKOTSHandlerMockRecorder) SaveInstanceSnapshotRetention(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveInstanceSnapshotRetention", reflect.TypeOf((*MockKOTSHandler)(nil).SaveInstanceSnapshotRetention), w, r)
}

// SaveInstanceSnapshotSchedule mocks base method.
func (m *MockKOTSHandler) SaveInstanceSnapshotSchedule(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SaveInstanceSnapshotSchedule", w, r)
}

// SaveInstanceSnapshotSchedule indicates an expected call of SaveInstanceSnapshotSchedule.
func (mr *MockKOTSHandlerMockRecorder) SaveInstanceSnapshotSchedule(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveInstanceSnapshotSchedule", reflect.TypeOf((*MockKOTSHandler)(nil).SaveInstanceSnapshotSchedule), w, r)
}

// SaveSnapshotRetention mocks base method.
func (m *MockKOTSHandler) SaveSnapshotRetention(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SaveSnapshotRetention", w, r)
}

// SaveSnapshotRetention indicates an expected call of SaveSnapshotRetention.
func (mr *MockKOTSHandlerMockRecorder) SaveSnapshotRetention(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSnapshotRetention", reflect.TypeOf((*MockKOTSHandler)(nil).SaveSnapshotRetention), w, r)
}

// SaveSnapshotSchedule mocks base method.
func (m *MockKOTSHandler) SaveSnapshotSchedule(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SaveSnapshotSchedule", w, r)
}

// SaveSnapshotSchedule indicates an expected call of SaveSnapshotSchedule.
func (mr *MockKOTSHandlerMockRecorder) SaveSnapshotSchedule(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSnapshotSchedule", reflect.TypeOf((*MockKOTSHandler)(nil).SaveSnapshotSchedule), w, r)
}

// SetAppConfigValues mocks base method.
func (m *MockKOTSHandler) SetAppConfigValues(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAppConfigValues", w, r)
}

// SetAppConfigValues indicates an expected call of SetAppConfigValues.
func (mr *MockKOTSHandlerMockRecorder) SetAppConfigValues(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAppConfigValues", reflect.TypeOf((*MockKOTSHandler)(nil).SetAppConfigValues), w, r)
}

// SetAutomaticUpdatesConfig mocks base method.
func (m *MockKOTSHandler) SetAutomaticUpdatesConfig(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAutomaticUpdatesConfig", w, r)
}

// SetAutomaticUpdatesConfig indicates an expected call of SetAutomaticUpdatesConfig.
func (mr *MockKOTSHandlerMockRecorder) SetAutomaticUpdatesConfig(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAutomaticUpdatesConfig", reflect.TypeOf((*MockKOTSHandler)(nil).SetAutomaticUpdatesConfig), w, r)
}

// SetPrometheusAddress mocks base method.
func (m *MockKOTSHandler) SetPrometheusAddress(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPrometheusAddress", w, r)
}

// SetPrometheusAddress indicates an expected call of SetPrometheusAddress.
func (mr *MockKOTSHandlerMockRecorder) SetPrometheusAddress(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPrometheusAddress", reflect.TypeOf((*MockKOTSHandler)(nil).SetPrometheusAddress), w, r)
}

// SetRedactEnabled mocks base method.
func (m *MockKOTSHandler) SetRedactEnabled(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRedactEnabled", w, r)
}

// SetRedactEnabled indicates an expected call of SetRedactEnabled.
func (mr *MockKOTSHandlerMockRecorder) SetRedactEnabled(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRedactEnabled", reflect.TypeOf((*MockKOTSHandler)(nil).SetRedactEnabled), w, r)
}

// SetRedactMetadataAndYaml mocks base method.
func (m *MockKOTSHandler) SetRedactMetadataAndYaml(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRedactMetadataAndYaml", w, r)
}

// SetRedactMetadataAndYaml indicates an expected call of SetRedactMetadataAndYaml.
func (mr *MockKOTSHandlerMockRecorder) SetRedactMetadataAndYaml(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRedactMetadataAndYaml", reflect.TypeOf((*MockKOTSHandler)(nil).SetRedactMetadataAndYaml), w, r)
}

// ShareSupportBundle mocks base method.
func (m *MockKOTSHandler) ShareSupportBundle(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ShareSupportBundle", w, r)
}

// ShareSupportBundle indicates an expected call of ShareSupportBundle.
func (mr *MockKOTSHandlerMockRecorder) ShareSupportBundle(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShareSupportBundle", reflect.TypeOf((*MockKOTSHandler)(nil).ShareSupportBundle), w, r)
}

// StartPreflightChecks mocks base method.
func (m *MockKOTSHandler) StartPreflightChecks(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartPreflightChecks", w, r)
}

// StartPreflightChecks indicates an expected call of StartPreflightChecks.
func (mr *MockKOTSHandlerMockRecorder) StartPreflightChecks(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartPreflightChecks", reflect.TypeOf((*MockKOTSHandler)(nil).StartPreflightChecks), w, r)
}

// StartUpgradeService mocks base method.
func (m *MockKOTSHandler) StartUpgradeService(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartUpgradeService", w, r)
}

// StartUpgradeService indicates an expected call of StartUpgradeService.
func (mr *MockKOTSHandlerMockRecorder) StartUpgradeService(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartUpgradeService", reflect.TypeOf((*MockKOTSHandler)(nil).StartUpgradeService), w, r)
}

// SyncLicense mocks base method.
func (m *MockKOTSHandler) SyncLicense(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SyncLicense", w, r)
}

// SyncLicense indicates an expected call of SyncLicense.
func (mr *MockKOTSHandlerMockRecorder) SyncLicense(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncLicense", reflect.TypeOf((*MockKOTSHandler)(nil).SyncLicense), w, r)
}

// UpdateAdminConsole mocks base method.
func (m *MockKOTSHandler) UpdateAdminConsole(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateAdminConsole", w, r)
}

// UpdateAdminConsole indicates an expected call of UpdateAdminConsole.
func (mr *MockKOTSHandlerMockRecorder) UpdateAdminConsole(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAdminConsole", reflect.TypeOf((*MockKOTSHandler)(nil).UpdateAdminConsole), w, r)
}

// UpdateAppConfig mocks base method.
func (m *MockKOTSHandler) UpdateAppConfig(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateAppConfig", w, r)
}

// UpdateAppConfig indicates an expected call of UpdateAppConfig.
func (mr *MockKOTSHandlerMockRecorder) UpdateAppConfig(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAppConfig", reflect.TypeOf((*MockKOTSHandler)(nil).UpdateAppConfig), w, r)
}

// UpdateAppFromAirgap mocks base method.
func (m *MockKOTSHandler) UpdateAppFromAirgap(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateAppFromAirgap", w, r)
}

// UpdateAppFromAirgap indicates an expected call of UpdateAppFromAirgap.
func (mr *MockKOTSHandlerMockRecorder) UpdateAppFromAirgap(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAppFromAirgap", reflect.TypeOf((*MockKOTSHandler)(nil).UpdateAppFromAirgap), w, r)
}

// UpdateAppGitOps mocks base method.
func (m *MockKOTSHandler) UpdateAppGitOps(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateAppGitOps", w, r)
}

// UpdateAppGitOps indicates an expected call of UpdateAppGitOps.
func (mr *MockKOTSHandlerMockRecorder) UpdateAppGitOps(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAppGitOps", reflect.TypeOf((*MockKOTSHandler)(nil).UpdateAppGitOps), w, r)
}

// UpdateAppRegistry mocks base method.
func (m *MockKOTSHandler) UpdateAppRegistry(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateAppRegistry", w, r)
}

// UpdateAppRegistry indicates an expected call of UpdateAppRegistry.
func (mr *MockKOTSHandlerMockRecorder) UpdateAppRegistry(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAppRegistry", reflect.TypeOf((*MockKOTSHandler)(nil).UpdateAppRegistry), w, r)
}

// UpdateGlobalSnapshotSettings mocks base method.
func (m *MockKOTSHandler) UpdateGlobalSnapshotSettings(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateGlobalSnapshotSettings", w, r)
}

// UpdateGlobalSnapshotSettings indicates an expected call of UpdateGlobalSnapshotSettings.
func (mr *MockKOTSHandlerMockRecorder) UpdateGlobalSnapshotSettings(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGlobalSnapshotSettings", reflect.TypeOf((*MockKOTSHandler)(nil).UpdateGlobalSnapshotSettings), w, r)
}

// UpdateRedact mocks base method.
func (m *MockKOTSHandler) UpdateRedact(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateRedact", w, r)
}

// UpdateRedact indicates an expected call of UpdateRedact.
func (mr *MockKOTSHandlerMockRecorder) UpdateRedact(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRedact", reflect.TypeOf((*MockKOTSHandler)(nil).UpdateRedact), w, r)
}

// UploadAirgapBundleChunk mocks base method.
func (m *MockKOTSHandler) UploadAirgapBundleChunk(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UploadAirgapBundleChunk", w, r)
}

// UploadAirgapBundleChunk indicates an expected call of UploadAirgapBundleChunk.
func (mr *MockKOTSHandlerMockRecorder) UploadAirgapBundleChunk(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadAirgapBundleChunk", reflect.TypeOf((*MockKOTSHandler)(nil).UploadAirgapBundleChunk), w, r)
}

// UploadNewLicense mocks base method.
func (m *MockKOTSHandler) UploadNewLicense(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UploadNewLicense", w, r)
}

// UploadNewLicense indicates an expected call of UploadNewLicense.
func (mr *MockKOTSHandlerMockRecorder) UploadNewLicense(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadNewLicense", reflect.TypeOf((*MockKOTSHandler)(nil).UploadNewLicense), w, r)
}

// ValidateAppRegistry mocks base method.
func (m *MockKOTSHandler) ValidateAppRegistry(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ValidateAppRegistry", w, r)
}

// ValidateAppRegistry indicates an expected call of ValidateAppRegistry.
func (mr *MockKOTSHandlerMockRecorder) ValidateAppRegistry(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAppRegistry", reflect.TypeOf((*MockKOTSHandler)(nil).ValidateAppRegistry), w, r)
}
