name: 'Build and push kurl-proxy image'
description: 'Composite action for building and pushing kurl-proxy image'
inputs:
  image-name:
    description: 'Full destination kurl-proxy image name'
    required: true

  git-tag:
    description: 'Git tag'
    required: true

  registry-username:
    description: 'Username to login to registry'
    default: ''
    required: false

  registry-password:
    description: 'Password to login to registry'
    default: ''
    required: false

runs:
  using: "composite"
  steps:
    - name: template melange and apko configs
      shell: bash
      run: |
        export GIT_TAG=${{ inputs.git-tag }}
        envsubst '${GIT_TAG}' < kurl_proxy/deploy/melange.yaml.tmpl > kurl_proxy/deploy/melange.yaml
        envsubst '${GIT_TAG}' < kurl_proxy/deploy/apko.yaml.tmpl > kurl_proxy/deploy/apko.yaml

    - id: cache-dir
      shell: bash
      run: echo "cache_dir=$(go env GOMODCACHE)" >> "$GITHUB_OUTPUT"

    - uses: chainguard-dev/actions/melange-build@main
      with:
        config: kurl_proxy/deploy/melange.yaml
        archs: arm64
        sign-with-temporary-key: true
        cache-dir: ${{ steps.cache-dir.outputs.cache_dir }}

    - uses: chainguard-images/actions/apko-publish@main
      with:
        config: kurl_proxy/deploy/apko.yaml
        archs: arm64
        tag: ${{ inputs.image-name }}
        vcs-url: true
        generic-user: ${{ inputs.registry-username }}
        generic-pass: ${{ inputs.registry-password }}
