apiVersion: apps/v1
kind: Deployment
metadata:
  name: grid
spec:
  selector:
    matchLabels:
      app: grid
  template:
    metadata:
      labels:
        app: grid
    spec:
      containers:
        - name: grid
          image: selenium/standalone-chrome
          imagePullPolicy: IfNotPresent
          ports:
            - name: webdriver
              containerPort: 4444
            - name: web-interface
              containerPort: 7900
---

apiVersion: v1
kind: Service
metadata:
  name: grid
  labels:
    app: grid
spec:
  type: NodePort
  ports:
    - port: 4444
      name: webdriver
      targetPort: webdriver
      nodePort: 30000
  selector:
    app: grid
