export const NAMESPACE = "qakotsregression";
export const VENDOR_INITIAL_CHANNEL_SEQUENCE = 74;
export const VENDOR_UPDATE_CHANNEL_SEQUENCE = 75;
export const LICENSE_ID = "1tMWrUR7pLWGrkkCZH836acYzTT";
export const CUSTOMER_ID = "1tMWrYwxYdsx1J3JALhLQLFHJog";
export const CUSTOMER_NAME = "type=existing cluster, env=online, phase=upgraded install, rbac=minimal rbac";
export const CHANNEL_NAME = "type=existing cluster, env=online, phase=upgraded install, rbac=minimal rbac";
export const CHANNEL_ID = "1tMWX0EwStDm7mJlVYL1FpWZJzh";
export const CHANNEL_SLUG = "type-existing-cluster-env-on-3";
export const VELERO_VERSION = "v1.12.1";
export const VELERO_AWS_PLUGIN_VERSION = "v1.8.1";
export const IS_EC = false;
export const IS_EXISTING_CLUSTER = true;
export const IS_AIRGAPPED = false;
export const IS_AIRGAP_SUPPORTED = false;
export const IS_MINIMAL_RBAC = true;
