apiVersion: v1
kind: ServiceAccount
metadata:
  name: kurl-proxy
  namespace: default
  labels:
    kots.io/kotsadm: "true"
    kots.io/backup: velero
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: secret-manager
  labels:
    kots.io/kotsadm: "true"
    kots.io/backup: velero
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list", "create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kurl-proxy-tls-secrets
  namespace: default
  labels:
    kots.io/kotsadm: "true"
    kots.io/backup: velero
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-manager
subjects:
- kind: ServiceAccount
  name: kurl-proxy
  namespace: default
