apiVersion: v1
kind: Service
metadata:
  name: kurl-proxy-kotsadm
  labels:
    kots.io/kotsadm: \"true\"
    kots.io/backup: velero
spec:
  type: NodePort
  selector:
    app: kurl-proxy-kotsadm
  ports:
  - port: 8800
    targetPort: 8800
    nodePort: ${KOTSADM_UI_BIND_PORT:-8800}
