export const NAMESPACE = "qakotsregression";
export const VENDOR_INITIAL_CHANNEL_SEQUENCE = 16;
export const VENDOR_UPDATE_CHANNEL_SEQUENCE = 17;
export const LICENSE_ID = "1tUlnsPu0jiGnGRkXr1eMULyxg9";
export const CUSTOMER_ID = "1tUlnuE56n4IMxXB48NsJdsIcfG";
export const CUSTOMER_NAME = "type=existing cluster, env=airgapped, phase=upgraded install, rbac=cluster admin";
export const CHANNEL_NAME = "type=existing cluster, env=airgapped, phase=upgraded install, rbac=cluster admin";
export const CHANNEL_ID = "1tUkwrJYi35BfFp1jJUxIMOlkUa";
export const CHANNEL_SLUG = "type-existing-cluster-env-ai-1";
export const VELERO_VERSION = "v1.12.1";
export const VELERO_AWS_PLUGIN_VERSION = "v1.8.1";
export const IS_EC = false;
export const IS_EXISTING_CLUSTER = true;
export const IS_AIRGAPPED = true;
export const IS_AIRGAP_SUPPORTED = true;
export const IS_MINIMAL_RBAC = false;
export const DOWNLOAD_PORTAL_BASE64_PASSWORD = "RjlQNlZW";
