apiVersion: kots.io/v1beta1
kind: License
metadata:
  name: typeexistingclusterenvairgappedphaseupgradedinstallrbacclusteradmin
spec:
  appSlug: qakotsregression
  channelID: 1tUkwrJYi35BfFp1jJUxIMOlkUa
  channelName: type=existing cluster, env=airgapped, phase=upgraded install, rbac=cluster
    admin
  customerName: type=existing cluster, env=airgapped, phase=upgraded install, rbac=cluster
    admin
  endpoint: https://replicated.app
  entitlements:
    bool_field_1:
      title: Boolean Field 1
      value: true
      valueType: Boolean
    expires_at:
      description: License Expiration
      title: Expiration
      value: ""
      valueType: String
    hidden_field_1:
      isHidden: true
      title: Hidden Field 1
      value: hide me
      valueType: String
    int_field_1:
      title: Integer Field 1
      value: 123
      valueType: Integer
    required_field_1:
      title: Required Field 1
      value: require me required
      valueType: String
    str_field_1:
      title: String Field 1
      value: abc
      valueType: String
    txt_field_1:
      title: Text Field 1
      value: |-
        abc
        xyz
      valueType: Text
  isAirgapSupported: true
  isGitOpsSupported: true
  isNewKotsUiEnabled: true
  isSnapshotSupported: true
  licenseID: 1tUlnsPu0jiGnGRkXr1eMULyxg9
  licenseSequence: 9
  licenseType: prod
  signature: eyJsaWNlbnNlRGF0YSI6ImV5SmhjR2xXWlhKemFXOXVJam9pYTI5MGN5NXBieTkyTVdKbGRHRXhJaXdpYTJsdVpDSTZJa3hwWTJWdWMyVWlMQ0p0WlhSaFpHRjBZU0k2ZXlKdVlXMWxJam9pZEhsd1pXVjRhWE4wYVc1blkyeDFjM1JsY21WdWRtRnBjbWRoY0hCbFpIQm9ZWE5sZFhCbmNtRmtaV1JwYm5OMFlXeHNjbUpoWTJOc2RYTjBaWEpoWkcxcGJpSjlMQ0p6Y0dWaklqcDdJbXhwWTJWdWMyVkpSQ0k2SWpGMFZXeHVjMUIxTUdwcFIyNUhVbXRZY2pGbFRWVk1lWGhuT1NJc0lteHBZMlZ1YzJWVWVYQmxJam9pY0hKdlpDSXNJbU4xYzNSdmJXVnlUbUZ0WlNJNkluUjVjR1U5WlhocGMzUnBibWNnWTJ4MWMzUmxjaXdnWlc1MlBXRnBjbWRoY0hCbFpDd2djR2hoYzJVOWRYQm5jbUZrWldRZ2FXNXpkR0ZzYkN3Z2NtSmhZejFqYkhWemRHVnlJR0ZrYldsdUlpd2lZWEJ3VTJ4MVp5STZJbkZoYTI5MGMzSmxaM0psYzNOcGIyNGlMQ0pqYUdGdWJtVnNTVVFpT2lJeGRGVnJkM0pLV1drek5VSm1SbkF4YWtwVmVFbE5UMnhyVldFaUxDSmphR0Z1Ym1Wc1RtRnRaU0k2SW5SNWNHVTlaWGhwYzNScGJtY2dZMngxYzNSbGNpd2daVzUyUFdGcGNtZGhjSEJsWkN3Z2NHaGhjMlU5ZFhCbmNtRmtaV1FnYVc1emRHRnNiQ3dnY21KaFl6MWpiSFZ6ZEdWeUlHRmtiV2x1SWl3aWJHbGpaVzV6WlZObGNYVmxibU5sSWpvNUxDSmxibVJ3YjJsdWRDSTZJbWgwZEhCek9pOHZjbVZ3YkdsallYUmxaQzVoY0hBaUxDSmxiblJwZEd4bGJXVnVkSE1pT25zaVltOXZiRjltYVdWc1pGOHhJanA3SW5ScGRHeGxJam9pUW05dmJHVmhiaUJHYVdWc1pDQXhJaXdpZG1Gc2RXVWlPblJ5ZFdVc0luWmhiSFZsVkhsd1pTSTZJa0p2YjJ4bFlXNGlmU3dpWlhod2FYSmxjMTloZENJNmV5SjBhWFJzWlNJNklrVjRjR2x5WVhScGIyNGlMQ0prWlhOamNtbHdkR2x2YmlJNklreHBZMlZ1YzJVZ1JYaHdhWEpoZEdsdmJpSXNJblpoYkhWbElqb2lJaXdpZG1Gc2RXVlVlWEJsSWpvaVUzUnlhVzVuSW4wc0ltaHBaR1JsYmw5bWFXVnNaRjh4SWpwN0luUnBkR3hsSWpvaVNHbGtaR1Z1SUVacFpXeGtJREVpTENKMllXeDFaU0k2SW1ocFpHVWdiV1VpTENKMllXeDFaVlI1Y0dVaU9pSlRkSEpwYm1jaUxDSnBjMGhwWkdSbGJpSTZkSEoxWlgwc0ltbHVkRjltYVdWc1pGOHhJanA3SW5ScGRHeGxJam9pU1c1MFpXZGxjaUJHYVdWc1pDQXhJaXdpZG1Gc2RXVWlPakV5TXl3aWRtRnNkV1ZVZVhCbElqb2lTVzUwWldkbGNpSjlMQ0p5WlhGMWFYSmxaRjltYVdWc1pGOHhJanA3SW5ScGRHeGxJam9pVW1WeGRXbHlaV1FnUm1sbGJHUWdNU0lzSW5aaGJIVmxJam9pY21WeGRXbHlaU0J0WlNCeVpYRjFhWEpsWkNJc0luWmhiSFZsVkhsd1pTSTZJbE4wY21sdVp5SjlMQ0p6ZEhKZlptbGxiR1JmTVNJNmV5SjBhWFJzWlNJNklsTjBjbWx1WnlCR2FXVnNaQ0F4SWl3aWRtRnNkV1VpT2lKaFltTWlMQ0oyWVd4MVpWUjVjR1VpT2lKVGRISnBibWNpZlN3aWRIaDBYMlpwWld4a1h6RWlPbnNpZEdsMGJHVWlPaUpVWlhoMElFWnBaV3hrSURFaUxDSjJZV3gxWlNJNkltRmlZMXh1ZUhsNklpd2lkbUZzZFdWVWVYQmxJam9pVkdWNGRDSjlmU3dpYVhOQmFYSm5ZWEJUZFhCd2IzSjBaV1FpT25SeWRXVXNJbWx6UjJsMFQzQnpVM1Z3Y0c5eWRHVmtJanAwY25WbExDSnBjMU51WVhCemFHOTBVM1Z3Y0c5eWRHVmtJanAwY25WbExDSnBjMDVsZDB0dmRITlZhVVZ1WVdKc1pXUWlPblJ5ZFdWOWZRPT0iLCJpbm5lclNpZ25hdHVyZSI6ImV5SnNhV05sYm5ObFUybG5ibUYwZFhKbElqb2lZbWxhVTNSa1UzbGxjR0ZIZEZkVmJscFdaa051TmtwMGRtTlRhVlJUSzBoRGVWcGlTREpGUVU0clJtTlZRV0psY21Gek9VcFlVWEpKYjNoMmFtZzFNREpTTkU5cE9YSmhOamxXYzFGbFFsSnRPRnBzVUVaakswSXdTemxoTXpWcU5qRnlVMHh6VWpZMGFYaE5TVU41VDFOcVZVRktNVzQ1WjNCM1FrRlVSbUl5T1c1WFZsRXdUbkI0ZVRSalRrdzBSbFp2WmpKR1ZXVlJXSGRHYlVodmJubEViVFZzYm5oMVpERnZhRFIxYldwR1dFNXBLMjg0U3l0Q01GQkRia0ptSzFKRmMzVkxNR3RXWjJwR1NFMWlPVXBtYm5wdFdYQjFkVEZFTlN0VmVUbE5aM0ZCTDNsb01sQXpRM2RsY0RKcWJISkhiREJXUm1weU4zSXdXbEJaYzNwelR6RXplSEJTWjJGelEwTnJPV055VEZoRVUwRXhaWFkxTjJwT09XaHBiVVJHYVROWFoydFZaMXBFUzBNelJYaFFORTV4YzBacVZXWlBTSE5wZW1zck9XbEtiRFpJTVhWdGFURm9OSFJ0UVZJMVZEbG5QVDBpTENKd2RXSnNhV05MWlhraU9pSXRMUzB0TFVKRlIwbE9JRkJWUWt4SlF5QkxSVmt0TFMwdExWeHVUVWxKUWtscVFVNUNaMnR4YUd0cFJ6bDNNRUpCVVVWR1FVRlBRMEZST0VGTlNVbENRMmRMUTBGUlJVRjFiRlZLYnl0S2RXbEVSbTltZEZCek1YTjFhbHh1YUZka04xbEJSWGh5Y2todlp6ZFViMnBETUdWeE1YQkJiRk5YUmxGeFltbGxlV051VVVFNE5teFdVRGhIY1dreGEyTnlObWsyVGtGMGEzUk9URkZqWmx4dVdXbFhSSEZMTURKMmRsVTNhWFJsVlZwTFpGTmtLMHRZWmxoWVRtd3hNa2xxVG1zMWJHUXZSRlZzTUhoU1ZYTmhMME5tVTNWVFMyaGlkMU0zTUhwclUxeHVORTFCYTB4dVpsUlpTM0p0YzJsaE1IYzRUVTVUWldwR1VXNXdSMDVGYTFabGMxbGtZMjVpZVdabmRsbHNTSHBwSzNFeWJFdFFTbWN6TmpreU4ycE9TRnh1UldwNlJXeE5XbUZxUjJwRU5GYzJibGhSTTFadVZsWXhXVWRyTVZwalpFcEViV1l6UzNFeU1FNVhlREpHZHpkVlpXMTZZVzAwVUM5R1dHNXljMGhGVEZ4dVNYRlJOWEZrUkRCRGFuRmxSV0lyTVhWV04wOXBTVXhLYUVGRWRXRnRWVkY0YVRoV1UzTk9jMWh0ZWpsc1FUVlFRbU5XY2pSYWNIQk1UMVpqTjJORGRseHVORkZKUkVGUlFVSmNiaTB0TFMwdFJVNUVJRkJWUWt4SlF5QkxSVmt0TFMwdExWeHVJaXdpYTJWNVUybG5ibUYwZFhKbElqb2laWGxLZW1GWFpIVlpXRkl4WTIxVmFVOXBTbFZMTUhoR1RsUmtXbGRHUWxOTk1taFVUVzVzV1UxV2JHdFJhM2hOVTFob1dtSkdhSFprVjAweFZtczViMkpHYkRGVlJrSXlWV3BrTTFJeFJsTk9NRVphVFZWa2FtSjZaREZMTWpWMlYycGFTV0Z0V1hsaU0yaEVUakJLY0U1dFVrNU9WM0I2VjBSR00xSkdVVFZhYmxKb1ZGaE5jbEpJYnpGWFJVNHhXakp2TVZWSE5ESk5iazVZVjIxS2FGcHFTWGhOVkZWNVQwVk5NMUZXV20xaVZHUlRUVWRTUzFWdE1YbGthelZLVDBWMGJGbHFaM2xrUkZweFZrVTFkR0p0TVhoaGFtd3pZakp3ZG1KR1JtNVJNbFpYVFRGQ1dVNUZTbGhsUlVVMVpWaFdlbUpzU1haVFNHOXlUbFZLZDJGRlozcGpNSFEwWlZSTk1sZFdWbXRpUkUwMVpFZDBNMXBIZERGalJtaDVVbXByZDJSWFdtNVZibHAzVFZWa2NHSXphRTFVUmtaclUyNUtVMDVGWkVsbFZ6UjVWVlZvZDA1WGFHbFVWM1JQWkZSR00xSldaRFJOUjFFMFZURmthbUpET1Vwa1ZGVjRZMnRTTVZOdFdrWlRWR3hWWkcxR1FrMVZaRE5YVkdoVVpIcGFkVTVxVG10YWJHc3hWVmhrYUU5WFRYcGhNVlpoVGtWRmRsUkhTbFZaTTFWNVRERldlRlF3VWxWTlJWcEpWSHBGTlU5RmNIVlVSekY1VG10dmQwNUVXalZoTUVab1VsWkdVbU14UlRCaWJuQlZVMmwwUjJWWFl6bFFVMGx6U1cxa2MySXlTbWhpUlhSc1pWVnNhMGxxYjJsWmJWSnNXbFJWTWs1VVdYZFpNbHBwVGtST2FrOVhTWGxQUjBwdFQxUm9iRmxYVG1oYWJVVXlUa1JaYVdaUlBUMGlmUT09In0=
