name: 'Build and push a dep image with apko'
description: 'Composite action for building and pushing a dep image with apko'
inputs:
  apko-config:
    description: 'Path to apko config'
    required: true

  image-name:
    description: 'Full destination image name'
    required: true

  registry-username:
    description: 'Username to login to registry'
    default: ''
    required: false

  registry-password:
    description: 'Password to login to registry'
    default: ''
    required: false

  overwrite:
    description: 'Overwrite the existing image tag'
    default: 'false'
    required: false

runs:
  using: "composite"
  steps:
    - id: check-image-exists
      if: ${{ inputs.overwrite != 'true' }}
      shell: bash
      run: |
        set -euo pipefail
        if docker manifest inspect ${{ inputs.image-name }} > /dev/null 2>&1; then
          echo "Image already exists. Will not overwrite."
          echo "image-exists=true" >> "$GITHUB_OUTPUT"
        else
          echo "Image does not exist. Will build and push."
          echo "image-exists=false" >> "$GITHUB_OUTPUT"
        fi

    # pin to work around https://github.com/chainguard-images/actions/issues/160
    - uses: chainguard-images/actions/apko-publish@49e3bc2feb790da6c3a7f749b38c769174c4ad54
      if: ${{ inputs.overwrite == 'true' || steps.check-image-exists.outputs.image-exists == 'false' }}
      with:
        apko-image: ghcr.io/wolfi-dev/sdk@sha256:b3c690e2aff7a6e6259632047b5d6133169204f7011b9936731cf3f403d5a8c1
        config: ${{ inputs.apko-config }}
        archs: amd64,arm64
        tag: ${{ inputs.image-name }}
        vcs-url: true
        generic-user: ${{ inputs.registry-username }}
        generic-pass: ${{ inputs.registry-password }}
