version: 0.1
log:
  fields:
    service: registry
storage:
  filesystem:
    rootdirectory: __ROOT_DIR__
http:
  addr: localhost:__PORT__
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
