FROM repldev/ship-cluster-worker as deps

ADD . /go/src/github.com/replicatedhq/ship-cluster/worker
WORKDIR /go/src/github.com/replicatedhq/ship-cluster/worker

RUN make build
RUN cp ./bin/ship-cluster-worker /opt/ship-cluster-worker

ENTRYPOINT ["/opt/ship-cluster-worker"]
