FROM repldev/ship-cluster-worker as deps

RUN go get -u github.com/golang/dep/cmd/dep
ENV PROJECTPATH=/go/src/github.com/replicatedhq/ship-cluster/worker
WORKDIR $PROJECTPATH
ADD . $PROJECTPATH

RUN go get github.com/sqs/goreturns
RUN go get -u golang.org/x/lint/golint
ENV PROJECTPATH=/go/src/github.com/replicatedhq/ship-cluster/worker
WORKDIR $PROJECTPATH

EXPOSE 3000
EXPOSE 6060

RUN make build
RUN cp ./bin/ship-cluster-worker /opt/ship-cluster-worker
ENTRYPOINT ["/opt/ship-cluster-worker"]
