apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: kurl-proxy
build:
  artifacts:
  - image: kurl-proxy
    docker:
      dockerfile: okteto.Dockerfile
manifests:
  kustomize:
    paths:
    - kustomize/overlays/dev
profiles:
- name: base
  manifests:
    kustomize:
      paths:
      - kustomize/base
