apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kotsadm
spec:
  serviceName: kotsadm
  selector:
    matchLabels:
      app: kotsadm
  template:
    metadata:
      labels:
        app: kotsadm
    spec:
      restartPolicy: Always
      volumes:
        - name: kotsadmdata
          persistentVolumeClaim:
            claimName: kotsadmdata
      containers:
        - name: kotsadm
          image: kotsadm
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: "/kotsadmdata"
              name: kotsadmdata
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - name: http
              containerPort: 3000
            - name: debug
              containerPort: 9229
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

  volumeClaimTemplates:
  - metadata:
      name: kotsadmdata
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: 2Gi
