apiVersion: kots.io/v1beta1
kind: License
metadata:
  name: typeembeddedclusterenvonlinephasenewinstallrbacclusteradmin
spec:
  appSlug: qakotsregression
  channelID: 1qugCGIEo11cV22k2rkfq9WtGG0
  channelName: type=embedded cluster, env=online, phase=new install, rbac=cluster
    admin
  customerName: type=embedded cluster, env=online, phase=new install, rbac=cluster
    admin
  endpoint: https://replicated.app
  entitlements:
    bool_field_1:
      title: Boolean Field 1
      value: true
      valueType: Boolean
    expires_at:
      description: License Expiration
      title: Expiration
      value: ""
      valueType: String
    hidden_field_1:
      isHidden: true
      title: Hidden Field 1
      value: hide me
      valueType: String
    int_field_1:
      title: Integer Field 1
      value: 449
      valueType: Integer
    required_field_1:
      title: Required Field 1
      value: require me
      valueType: String
    str_field_1:
      title: String Field 1
      value: abc
      valueType: String
    txt_field_1:
      title: Text Field 1
      value: |-
        abc
        xyz
      valueType: Text
  isAirgapSupported: true
  isGitOpsSupported: true
  isSnapshotSupported: true
  licenseID: 1qugUMvdUjnJE7QO15oRkDvbyWj
  licenseSequence: 5
  licenseType: prod
  signature: eyJsaWNlbnNlRGF0YSI6ImV5SmhjR2xXWlhKemFXOXVJam9pYTI5MGN5NXBieTkyTVdKbGRHRXhJaXdpYTJsdVpDSTZJa3hwWTJWdWMyVWlMQ0p0WlhSaFpHRjBZU0k2ZXlKdVlXMWxJam9pZEhsd1pXVnRZbVZrWkdWa1kyeDFjM1JsY21WdWRtOXViR2x1WlhCb1lYTmxibVYzYVc1emRHRnNiSEppWVdOamJIVnpkR1Z5WVdSdGFXNGlmU3dpYzNCbFl5STZleUpzYVdObGJuTmxTVVFpT2lJeGNYVm5WVTEyWkZWcWJrcEZOMUZQTVRWdlVtdEVkbUo1VjJvaUxDSnNhV05sYm5ObFZIbHdaU0k2SW5CeWIyUWlMQ0pqZFhOMGIyMWxjazVoYldVaU9pSjBlWEJsUFdWdFltVmtaR1ZrSUdOc2RYTjBaWElzSUdWdWRqMXZibXhwYm1Vc0lIQm9ZWE5sUFc1bGR5QnBibk4wWVd4c0xDQnlZbUZqUFdOc2RYTjBaWElnWVdSdGFXNGlMQ0poY0hCVGJIVm5Jam9pY1dGcmIzUnpjbVZuY21WemMybHZiaUlzSW1Ob1lXNXVaV3hKUkNJNklqRnhkV2REUjBsRmJ6RXhZMVl5TW1zeWNtdG1jVGxYZEVkSE1DSXNJbU5vWVc1dVpXeE9ZVzFsSWpvaWRIbHdaVDFsYldKbFpHUmxaQ0JqYkhWemRHVnlMQ0JsYm5ZOWIyNXNhVzVsTENCd2FHRnpaVDF1WlhjZ2FXNXpkR0ZzYkN3Z2NtSmhZejFqYkhWemRHVnlJR0ZrYldsdUlpd2liR2xqWlc1elpWTmxjWFZsYm1ObElqbzFMQ0psYm1Sd2IybHVkQ0k2SW1oMGRIQnpPaTh2Y21Wd2JHbGpZWFJsWkM1aGNIQWlMQ0psYm5ScGRHeGxiV1Z1ZEhNaU9uc2lZbTl2YkY5bWFXVnNaRjh4SWpwN0luUnBkR3hsSWpvaVFtOXZiR1ZoYmlCR2FXVnNaQ0F4SWl3aWRtRnNkV1VpT25SeWRXVXNJblpoYkhWbFZIbHdaU0k2SWtKdmIyeGxZVzRpZlN3aVpYaHdhWEpsYzE5aGRDSTZleUowYVhSc1pTSTZJa1Y0Y0dseVlYUnBiMjRpTENKa1pYTmpjbWx3ZEdsdmJpSTZJa3hwWTJWdWMyVWdSWGh3YVhKaGRHbHZiaUlzSW5aaGJIVmxJam9pSWl3aWRtRnNkV1ZVZVhCbElqb2lVM1J5YVc1bkluMHNJbWhwWkdSbGJsOW1hV1ZzWkY4eElqcDdJblJwZEd4bElqb2lTR2xrWkdWdUlFWnBaV3hrSURFaUxDSjJZV3gxWlNJNkltaHBaR1VnYldVaUxDSjJZV3gxWlZSNWNHVWlPaUpUZEhKcGJtY2lMQ0pwYzBocFpHUmxiaUk2ZEhKMVpYMHNJbWx1ZEY5bWFXVnNaRjh4SWpwN0luUnBkR3hsSWpvaVNXNTBaV2RsY2lCR2FXVnNaQ0F4SWl3aWRtRnNkV1VpT2pRME9Td2lkbUZzZFdWVWVYQmxJam9pU1c1MFpXZGxjaUo5TENKeVpYRjFhWEpsWkY5bWFXVnNaRjh4SWpwN0luUnBkR3hsSWpvaVVtVnhkV2x5WldRZ1JtbGxiR1FnTVNJc0luWmhiSFZsSWpvaWNtVnhkV2x5WlNCdFpTSXNJblpoYkhWbFZIbHdaU0k2SWxOMGNtbHVaeUo5TENKemRISmZabWxsYkdSZk1TSTZleUowYVhSc1pTSTZJbE4wY21sdVp5QkdhV1ZzWkNBeElpd2lkbUZzZFdVaU9pSmhZbU1pTENKMllXeDFaVlI1Y0dVaU9pSlRkSEpwYm1jaWZTd2lkSGgwWDJacFpXeGtYekVpT25zaWRHbDBiR1VpT2lKVVpYaDBJRVpwWld4a0lERWlMQ0oyWVd4MVpTSTZJbUZpWTF4dWVIbDZJaXdpZG1Gc2RXVlVlWEJsSWpvaVZHVjRkQ0o5ZlN3aWFYTkJhWEpuWVhCVGRYQndiM0owWldRaU9uUnlkV1VzSW1selIybDBUM0J6VTNWd2NHOXlkR1ZrSWpwMGNuVmxMQ0pwYzFOdVlYQnphRzkwVTNWd2NHOXlkR1ZrSWpwMGNuVmxmWDA9IiwiaW5uZXJTaWduYXR1cmUiOiJleUpzYVdObGJuTmxVMmxuYm1GMGRYSmxJam9pY3k5MVNFOXJUVk5xWmxSMWFrMHJaMGw0VUVsRk1teEtUR2sxY0VseGJEWmpXRlpCWW1rMVVVSm9NREl5UkV4Q1lrc3hhbU5ETVU1SE1HVlZaMWhrWlRGWlEyZHFPRFZaY1hOdk1rVnJOVWRDWjJSWlNUYzRhek5SVDJaR1ZrZDJWR0UwYldsd1VHNTZRMU5EV0dGNVVFZFRRemxJTUV4TVlVTlpjRTVuV21wNmNXaE5VV2hEWjI5dE4ybDFPRGhITm5jNVZEZFpUV0ZFWVdoSVpUVktaRXRtYTBWa2RqaFdZVk4xWW1OYVVtMXVVMDlSYmxWTlFucEtUbnBGV1RGbk0ybFplV3M1TTNodVMzZDNURGRKZUVvMVJrSnVlVU5zYVU5TlNsRXZlREkxZW5scFpUWnllbFJyTjJwd2RYRlRhbGQwZWxoQk1FRllXVXRJVTNkNlpuVjJObk55WlZkc09FVXZia1Y2VWxFM1RrNTBhVEpGVEc5SVV6UTNiM1F3UkZCbFNqRkJjVmhOTlV4cldYaEtibE16VEV4VVUybGlNVTFWWlROQ1dGQlZiaXRRYWpoaWJWY3pjRlZRTml0TWVFOXVhRkZuUFQwaUxDSndkV0pzYVdOTFpYa2lPaUl0TFMwdExVSkZSMGxPSUZCVlFreEpReUJMUlZrdExTMHRMVnh1VFVsSlFrbHFRVTVDWjJ0eGFHdHBSemwzTUVKQlVVVkdRVUZQUTBGUk9FRk5TVWxDUTJkTFEwRlJSVUYxYkZWS2J5dEtkV2xFUm05bWRGQnpNWE4xYWx4dWFGZGtOMWxCUlhoeWNraHZaemRVYjJwRE1HVnhNWEJCYkZOWFJsRnhZbWxsZVdOdVVVRTRObXhXVURoSGNXa3hhMk55Tm1rMlRrRjBhM1JPVEZGalpseHVXV2xYUkhGTE1ESjJkbFUzYVhSbFZWcExaRk5rSzB0WVpsaFlUbXd4TWtscVRtczFiR1F2UkZWc01IaFNWWE5oTDBObVUzVlRTMmhpZDFNM01IcHJVMXh1TkUxQmEweHVabFJaUzNKdGMybGhNSGM0VFU1VFpXcEdVVzV3UjA1RmExWmxjMWxrWTI1aWVXWm5kbGxzU0hwcEszRXliRXRRU21jek5qa3lOMnBPU0Z4dVJXcDZSV3hOV21GcVIycEVORmMyYmxoUk0xWnVWbFl4V1Vkck1WcGpaRXBFYldZelMzRXlNRTVYZURKR2R6ZFZaVzE2WVcwMFVDOUdXRzV5YzBoRlRGeHVTWEZSTlhGa1JEQkRhbkZsUldJck1YVldOMDlwU1V4S2FFRkVkV0Z0VlZGNGFUaFdVM05PYzFodGVqbHNRVFZRUW1OV2NqUmFjSEJNVDFaak4yTkRkbHh1TkZGSlJFRlJRVUpjYmkwdExTMHRSVTVFSUZCVlFreEpReUJMUlZrdExTMHRMVnh1SWl3aWEyVjVVMmxuYm1GMGRYSmxJam9pWlhsS2VtRlhaSFZaV0ZJeFkyMVZhVTlwU2s5aWEwa3dWbTVHYjJSRmRERlVhMDVRVDFWR01XRXhaRTFPVjFKV1RsaE9NbFZwZEV0bFNGSjNWbFpPZUZsVWJIVk9NV3hTVEhwU01Gb3dVbXRYV0d3d1kzazVNMUpXY0ZCaVJ6VnBUVEpyZDAxWWFETlphbWhRWWxVMVVsSkdTbkZhUjBVeVkxUkdXR1J1YUV0aFNFWk1WRlJDYW1WR1dsRk9NRTR4WWtSbmVGVnVhSFppYldoUVlWZHNkVTB3TlVWbFNFWkdZV3N4VFZFemNFbFNlWFJ5WkZVd01HSXpWVE5qU0U1UVMzbHpORlZWYUdGa1NGbDRVbXBvVWxWNlVrdE5iVFF6WVZSQ2VsVnFTa2hTVjNCdFRrWmtiRmw2YUUxaFIxcHhZa1JrZVUxVldYbGtWVFZxVWxSV00wNUdSa3BVVm14M1ZXdG9OVkY2U2pWVmEyaGhXV3BzVW1OVk9VbGhhMFowWVZkek0ySklUbHBPUjBaSlYxZHdSVTlFVVRGVlIwWjBUMFJGTlZReGJITmpibEV3V201cmVHUnJXVEZpTWpGS1dqRldlR0ZFV2xkWmJUbERWRmRXYVUxdE1WSldhMUpDVTJwQ1JXUnRjRWhWYTFZMlVWVXhXRk5ZWkZkU01FWXlWMFJOZDFsdFdsbGFWWFJXWW14V2FGVldiekZqVms1b1YxaEdRazVVVVRCVk0wWktUMWMxZFU1dGVFZGFVemwwVmpCU2FXRkVVa2hsV0VwSlRrWmFhbFJFVm5CUFdGWnhXbFpzUjFacVVuVkxlbFpPVmxWTk0xcFhZemxRVTBselNXMWtjMkl5U21oaVJYUnNaVlZzYTBscWIybFpiVkpzV2xSVk1rNVVXWGRaTWxwcFRrUk9hazlYU1hsUFIwcHRUMVJvYkZsWFRtaGFiVVV5VGtSWmFXWlJQVDBpZlE9PSJ9
