apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotsadm
spec:
  template:
    spec:
      containers:
        - name: kotsadm
          env:
            - name: RQLITE_URI
              valueFrom:
                secretKeyRef:
                  name: kotsadm-rqlite # This secret is created in the migrations directory
                  key: uri
            - name: S3_BUCKET_NAME
              value: "shipbucket"
            - name: S3_ENDPOINT
              value: http://kotsadm-minio:4569/
            - name: S3_ACCESS_KEY_ID
              value: not-a-key
            - name: S3_SECRET_ACCESS_KEY
              value: not-a-secret
            - name: S3_BUCKET_ENDPOINT
              value: "true"
