apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kotsadm
spec:
  template:
    spec:
      containers:
        - name: kotsadm
          env:
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: kotsadm-postgres # This secret is created in the migrations directory
                  key: uri
