on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'

name: actionlint

jobs:
  actionlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check workflow files
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color
