name: kurl-addon-publish

on:
  workflow_dispatch:
    inputs:
      addon_version:
        type: string
        description: "Kots version."
        required: true
  release:
    types:
      - published

concurrency: kurl-addon-publish

jobs:
  generate-kots-addon:
    uses: ./.github/workflows/kurl-addon-kots-test.yaml
    with:
      addon_version: "${{ inputs.addon_version || github.ref_name }}"
      s3_prefix: ""
      priority: 1

  publish-kots-addon:
    runs-on: ubuntu-20.04
    needs: generate-kots-addon
    uses: ./.github/actions/kurl-addon-kots-publisher
    with:
      ADDON_VERSION: ${{ inputs.addon_version || github.ref_name }}
      ADDON_PACKAGE_URL: ${{ needs.generate-kots-addon.outputs.addon_package_url }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
