name: "Label '@actions/safe-to-test'"

on:
  pull_request:
    branches:
      - master

jobs:
  label:
    runs-on: ubuntu-latest

    # if not a fork
    if: github.event.pull_request.head.repo.full_name == github.repository

    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/label-safe-to-test.yml
