name: port-forward-test

on:
  push:
    branches:
      - "**"

jobs:
  build-web:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '10'

      - name: save private key
        run: sudo echo '${{ secrets.TESTIM_SSH_PRIVATE_KEY }}' > ./testim_id_rsa
      
      - name: chmod 
        run: sudo chmod 600 ./testim_id_rsa

      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.2
      
      - name: ssh
        run: |
          export privateIp=$(hostname -I | awk '{print $1}' | tr -d '\n') && \
          sudo ssh -oStrictHostKeyChecking=no -i ./testim_id_rsa -NfL $(privateIp):30081:10.128.0.11:8800 testim@34.121.160.197 && \
          export publicIp=$(curl https://ipinfo.io/ip) && \
          curl http://$publicIp:30081 -vk
