name: release-for-ec

on:
  push:
    branches:
      - release-for-ec-dispatch-workflow

permissions:
  contents: write

jobs:
  validate-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Validate tag format
        run: |
          TAG="v1.124.15-ec.0"
          if ! [[ "$TAG" =~ -ec\.[0-9]+$ ]]; then
            echo "Error: Tag must end with -ec.<digit> suffix (e.g. v1.92.0-ec.1)"
            exit 1
          fi
          echo "Tag format is valid: $TAG"

  # build-migrations-melange-packages:
  #   needs: [validate-tag]
  #   strategy:
  #     fail-fast: true
  #     matrix:
  #       runner: [
  #         {name: ubuntu-latest, arch: amd64},
  #         {name: arm64-runner-set, arch: arm64}
  #       ]
  #   runs-on: ${{ matrix.runner.name }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/build-custom-melange-package
  #       with:
  #         context: migrations/deploy
  #         component: kotsadm-migrations
  #         git-tag: v1.124.15-ec.0
  #         arch: ${{ matrix.runner.arch }}

  # build-migrations:
  #   runs-on: ubuntu-latest
  #   needs: [build-migrations-melange-packages]
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/build-custom-image-with-apko
  #       with:
  #         context: migrations/deploy
  #         component: kotsadm-migrations
  #         git-tag: v1.124.15-ec.0
  #         image-name: index.docker.io/kotsadm/kotsadm-migrations:v1.124.15-ec.0
  #         registry-username: ${{ secrets.DOCKERHUB_USER }}
  #         registry-password: ${{ secrets.DOCKERHUB_PASSWORD }}

  # build-kurl-proxy-melange-packages:
  #   needs: [validate-tag]
  #   strategy:
  #     fail-fast: true
  #     matrix:
  #       runner: [
  #         {name: ubuntu-latest, arch: amd64},
  #         {name: arm64-runner-set, arch: arm64}
  #       ]
  #   runs-on: ${{ matrix.runner.name }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/build-custom-melange-package
  #       with:
  #         context: kurl_proxy/deploy
  #         component: kurl-proxy
  #         git-tag: v1.124.15-ec.0
  #         arch: ${{ matrix.runner.arch }}

  # build-kurl-proxy:
  #   runs-on: ubuntu-latest
  #   needs: [build-kurl-proxy-melange-packages]
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/build-custom-image-with-apko
  #       with:
  #         context: kurl_proxy/deploy
  #         component: kurl-proxy
  #         git-tag: v1.124.15-ec.0
  #         image-name: index.docker.io/kotsadm/kurl-proxy:v1.124.15-ec.0
  #         registry-username: ${{ secrets.DOCKERHUB_USER }}
  #         registry-password: ${{ secrets.DOCKERHUB_PASSWORD }}

  # build-kotsadm-melange-packages:
  #   needs: [validate-tag]
  #   strategy:
  #     fail-fast: true
  #     matrix:
  #       runner: [
  #         {name: ubuntu-latest, arch: amd64},
  #         {name: arm64-runner-set, arch: arm64}
  #       ]
  #   runs-on: ${{ matrix.runner.name }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/build-custom-melange-package
  #       with:
  #         context: deploy
  #         component: kotsadm
  #         git-tag: v1.124.15-ec.0
  #         arch: ${{ matrix.runner.arch }}

  # build-kotsadm:
  #   runs-on: ubuntu-latest
  #   needs: [build-kotsadm-melange-packages]
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/build-custom-image-with-apko
  #       with:
  #         context: deploy
  #         component: kotsadm
  #         git-tag: v1.124.15-ec.0
  #         image-name: index.docker.io/kotsadm/kotsadm:v1.124.15-ec.0
  #         registry-username: ${{ secrets.DOCKERHUB_USER }}
  #         registry-password: ${{ secrets.DOCKERHUB_PASSWORD }}

  tag-helm-chart:
    runs-on: ubuntu-latest
    # needs: [build-migrations, build-kurl-proxy, build-kotsadm]
    steps:
      - name: Checkout Chart
        uses: actions/checkout@v4
        with:
          repository: replicatedhq/kots-helm
          token: ${{ secrets.GH_PAT }}
          ref: support-ec-tags
          
      - name: Tag Chart
        run: |
          git tag "v1.124.15-ec.0+${GITHUB_SHA:0:7}"
          git push origin "v1.124.15-ec.0+${GITHUB_SHA:0:7}"
