name: Require pull request labels

permissions:
  pull-requests: read

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

jobs:
  require-pr-labels:
    uses: replicatedhq/reusable-workflows/.github/workflows/pr-enforce-labels.yaml@main
  require-bug-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v2
        if: ${{ github.event.label.name == 'type::bug' }}
        with:
          mode: exactly
          count: 1
          labels: "bug::normal, bug::regression"
