name: sbom-build

on:
  workflow_dispatch:
    


jobs:
  sbom:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v2.1.6
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Initialize Yarn
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: make -C web deps

      - uses: sigstore/cosign-installer@v1.1.0

      - name: Get Cosign Key
        run: |
          echo $COSIGN_KEY | base64 -d > ./cosign.key
        env:
          COSIGN_KEY: ${{secrets.COSIGN_KEY}}

      - name: Generate SBOM
        run: |
          COSIGN_PASSWORD=$COSIGN_PASSWORD make sbom
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}


