name: Temp Terraform Checkout Test

on:
  push:
    branches:
      - '**'   # runs on any branch push
  pull_request:
    branches:
      - main   # runs on PRs targeting main

jobs:
  test-checkout:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.13.1
    steps:
      - name: Install git + ssh client
        run: apk add --no-cache git openssh-client

      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Verify Terraform works
        run: terraform version

      - name: Verify musl version (sanity check)
        # Don't fail the job if version probes return non-zero
        continue-on-error: true
        run: |
          arch="$(uname -m)"
          # If ldd is present, show its version; ignore non-zero exit
          if command -v ldd >/dev/null 2>&1; then
            ldd --version || true
          fi
          # musl loader prints version and may exit non-zero; that's OK
          "/lib/libc.musl-${arch}.so.1" --version || true
