name: trigger-regression-test

on:
  push:
    branches:
      - main

jobs:
  generate-tag:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get tags
      id: get_tag
      uses: ./actions/version-tag

    - name: Push tag
      env:
        GIT_TAG: ${{ steps.get_tag.outputs.GIT_TAG }}
      run: |
        git tag $GIT_TAG
        git push origin $GIT_TAG
