FROM node:8
EXPOSE 3000 9229

ADD ./package.json /src/package.json
ADD ./yarn.lock /src/yarn.lock
WORKDIR /src
RUN yarn install --silent --frozen-lockfile

ADD . /src/
WORKDIR /src

EXPOSE 8000
RUN make deps

RUN useradd -c 'kotsadm-web user' -m -d /home/kotsadm-web -s /bin/bash -u 1001 kotsadm-web
RUN chown -R kotsadm-web.kotsadm-web /src
USER kotsadm-web
ENV HOME /home/kotsadm-web

ENTRYPOINT ["make", "serve"]