FROM node:10
EXPOSE 3000 9229

WORKDIR /src
COPY ./package.json ./yarn.lock ./
RUN --mount=type=cache,target=/root/.yarn YARN_CACHE_FOLDER=/root/.yarn make deps

COPY . .

ENTRYPOINT ["make", "serve"]
