FROM node:10 as dev
EXPOSE 8080 9229

WORKDIR /src

COPY ./package.json ./yarn.lock ./
COPY Makefile ./
RUN --mount=type=cache,target=/root/.yarn YARN_CACHE_FOLDER=/root/.yarn make deps

COPY . .

FROM dev as builder
ARG OKTETO_NAMESPACE
RUN --mount=type=cache,target=./node_modules/.cache/webpack make build-local

FROM nginx:1.21.4-alpine as nginx
COPY --from=builder /src/dist /usr/share/nginx/html
COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 8080